### PR TITLE
Task 7,8,9

### PR DESCRIPTION
**Pull request by sharidas2210**

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Sruthilaya/Task7/project.json
Main.xaml:

1. I've noticed you're not using Log Message in your workflow. Understand it's easy to forget, but remember it’s important for understanding the flow path. This helps greatly when we need to maintain or troubleshoot. So, do ensure you're using it.

NoFile:

2. I can't find your Automation Hub URL. You gotta define this as per our organization's requirement. No sweat, just head to the "Project Settings" and you can slot it in there. 

**Score:**
Total: 5 points 

- Code completion: 1/2 (One file is missing)
- Execution: 2/2
- Annotations and comments: 1/1

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Sruthilaya/Task8/project.json
## Main.xaml
1. **Code Completion: 2** - The work file is complete but requires some improvements.
2. **Execution: 1.5** - The execution could be affected by the lack of logging information for error identification.
3. **Annotations and comments: 1** - Not many comments were found and meaningful variable name is missing for better understanding.

### Feedback:
- Remember to make use of `Log Message` activities. These become critical when the code moves beyond development stage for easy debugging and understanding the flow. Incorporate them at essential points in your workflow.
- Avoid having activities with default names. Always aim for intuitive and descriptive names to indicate their specific roles in the workflow. This makes code maintenance and debugging easier.

## NoFile
1. **Code Completion: 2** - The work file is complete but requires some additional information based on organization policy.
2. **Execution: 2** - The execution doesn't seem to be hampered due to the missing information but it might not conform to the organizational standards.
3. **Annotations and comments: 2** - As there is no file for review, comments or annotations score doesn't apply here.

### Feedback:
- Your organization requires you to define an `Automation Hub URL

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Sruthilaya/Task9/project.json
Based on my review, I have the following feedback for your code:

For "Main.xaml":

1. Log Message not used in workflow Main: Using Log Message activities can greatly help in understanding the flow path, particularly for maintenance and error tracking. It's a good practice to use them both during development and post-release.

For "NoFile":

1. Your organization requires your project to have an Automation Hub URL defined: You can easily fix this by going to the 'Project Settings' and adding the required information.

Score:

Code Completion: 1 (Some functionalities are missing)
Execution: 2 (No execution issues found)
Annotations and Comments: 1 (Log message activity is missing which is a key aspect of annotations)

Please take into account these constructive comments for enhancing the quality and readability of your code.

**Comment by krish952-creator** [comment]
@sharidas2210 
Task -7
Code verified.
Task -8
Code verified. Default activity names
image
Task -9
Code verified.

**Pull request merged**
