### PR TITLE
projects rpa challenge

### PR DESCRIPTION
**Pull request by lavanyachigurupati**

### CODE REVIEW

**Comment by vajrang-b** [comment]
There are 83 files changed in this pr
Please name pr properly

**Comment by vajrang-b** [comment]
@paruA32  review this please

**Review by paruA32 — COMMENTED** [review]
Hi Lavanya your code has issues 
1.Process transaction state 
you are not filling the other fields except for the name field
image

2.in the end state even if the process is not completed 
getting the congratulations text

**Comment by lavanyachigurupati** [comment]
ya sure will do that

**Pull request closed without merging**
