### PR TITLE
Task1_Display name in  Message

### PR DESCRIPTION
**Pull request by shaikMahaboob22**
Task1

### CODE REVIEW

**Comment by swathinelakurthi** [comment]
Activities are not named properly.
Screenshot 2023-08-03 202501

**Comment by shaikMahaboob22** [comment]
I Changed the Property of Message box and uploaded.

**Comment by shaikMahaboob22** [comment]
Task2_Addition or subtraction
Task2.1_Addirion of Strings

**Comment by shaikMahaboob22** [comment]
Task1,Task3,Task3.1 and Task5

**Comment by swathinelakurthi** [comment]
@shaikMahaboob22 
Task1: Changes verified.
Task2: Performed addition for multiplication.
image
Task3: Duplicate activity names
image
Task3.1: You must use Flow Decision instead of If.
Task5: one assign activity with date_time variable is enough to perform all operations.
image

**Comment by vajrang-b** [comment]
@shaikMahaboob22  update name of the pr with correct task names

**Comment by shaikMahaboob22** [comment]
I done all changes .
Task2 - Perform Correct calculation
Task3- Duplicate Activities removed
Task5- one assign activity is used perform all operations.

**Pull request closed without merging**
