### PR TITLE
task-26

### PR DESCRIPTION
**Pull request by Madhurichannamaneni**

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2024/Basics-April2024/Madhuri/Task-26/project.json
**Main.xaml**
- Log message not used in workflow
- Using log message activities is important during development and after release, as they help understand the flow path which is very useful for maintenance and identifying errors.

**Message Box**
- Defined many times; allowed threshold is 1 (too many duplicate names)
- Names of activities should give a clear indication of their usage; default names are too generic

**Activity Input Dialog**, **Activity Assign**, **Activity Message Box**, **Activity State Machine**, and multiple instances of **Activity Message Box**
- All have default names, making it hard to understand what they do
- Please add more descriptive titles for clarity

**NoFile**
- Organization requires Automation Hub URL defined; use Project Settings to add the missing information

Overall score: 4/5

**Comment by vajrang-b** [comment]
SourceCode/2024/Basics-April2024/Madhuri/Task-26/project.json
**Automate.xaml**
The code in this file seems to be used for automating some process. However, there's not much information about what it does or why it's important.

* The log message is not being used anywhere in the workflow. It would be better to remove unused activities to keep the code clean and efficient.
* Many Message Box display names are defined multiple times. This could be improved by reusing existing strings instead of creating new ones each time.
* Activity names should give a clear indication of how they're being used. Default names like "Message Box" and "Activity State Machine" don't provide much context.

**Score: 2/5**

**InputDialog.xaml**
The code in this file seems to be related to user input. However, there's not enough information about what it does or why it's important.

* The Activity Input Dialog has a default name. It would be better to give it a more descriptive title so that the purpose of the activity is clear.
* There are many Message Box activities with default names. These could be improved by giving them more descriptive titles.

**Score: 2/5**

**NoFile**
The project doesn't have an Automation Hub URL defined. This should be added in Project Settings to meet organizational requirements.

**Score: 1/5**

**Total Score: 5/15**

**Comment by vajrang-b** [comment]
SourceCode/2024/Basics-April2024/Madhuri/Task-27/project.json
**Main.xaml**
The `WriteLine` activities in this file are only used for debugging purposes. It's recommended to replace them with tracepoints during debug mode and remove them before publishing.
**Subtraction.xaml, Addition.xaml**
Log Message activities are not used in these workflows. Log messages are important both during development and after release, as they help understanding the flow path and identifying errors when they occur.
**All files**
Activity Assign has a default name. Consider adding more descriptive titles to make it easier to understand what each activity does.

**Score: 5/5**

Please note that all suggestions are made in simple English and are grouped based on file names for ease of reference.

**Comment by vajrang-b** [comment]
SourceCode/2024/Basics-April2024/Madhuri/Task-26/project.json
**NoFile**
You're missing an important setting! Please add your Automation Hub URL in Project Settings.

**Main.xaml**
Log Messages are essential for understanding workflow flow paths, both during development and after release. They help identify sources of errors and causes.

**Message Box**
Rename the display name to something more descriptive. You have 5 duplicate names, which is above the allowed threshold of 1. Aim for unique names that clearly indicate their purpose.

**Activity State Machine**, **Activity Message Box**, **Activity Assign**, **Activity Input Dialog**
Give these activities more descriptive titles! This will make it easier to understand what they do.

Score: 4/5

**Comment by vajrang-b** [comment]
SourceCode/2024/Basics-April2024/Madhuri/Task-27/project.json
**Main Comments**
--------------

* **Subtraction.xaml**: We should use Log Message activities throughout the workflow to provide better understanding of the flow path during development and maintenance.
* **Main.xaml**: The WriteLine activities at output and subtraction can be replaced with tracepoints during debug mode and removed before publishing. Consider changing them to Log Messages if necessary for debugging purposes.

**Style Suggestions**
-------------------

* **All Files**: Use more descriptive titles for Activity Assigns instead of default names, this will make the code easier to understand.
* **Addition.xaml**: Just like Subtraction.xaml, we should use Log Message activities throughout the workflow in Addition.xaml as well.

**Score: 4/5**

Please let me know if you'd like me to clarify anything.

**Comment by vajrang-b** [comment]
SourceCode/2024/Basics-April2024/Madhuri/Task-28/project.json
**Main.xaml:**
Log messages are crucial for understanding the workflow and identifying potential issues when an error occurs.

**Extract PDF Page Range:**
This activity's display name is repeated multiple times, which can lead to confusion. Please rename it to something more specific about what this activity does.

**Activity Comment Out:** 
A descriptive title would help clarify the purpose of this activity.
**Activity Read PDF With OCR:** 
Same as above, a clear title would be beneficial.
**Activity Tesseract OCR:** 
Similar to before, a detailed title would improve understanding.
**Activity Write Text File:** 
This activity's title could be more explicit about its function.
**Activity Export PDF Page As Image:** 
As with the others, a descriptive title would help.
**Activity Extract Images From PDF:** 
Same as above, a clear title is necessary.
**Activity Extract PDF Page Range (2):**
Duplicate name detected! Renaming this activity to something unique and descriptive is essential.
**Activity Get PDF Page Count:** 
A detailed title would make it easier to understand what this activity does.
**Activity Message Box:** 
As with the others, a clear title would be beneficial.

**Score: 5/5**

Please note that no code suggestions are provided as they are not necessary for this review. Instead, focus on the file names and activity titles.

**Comment by vajrang-b** [comment]
SourceCode/2024/Basics-April2024/Madhuri/Task-26/project.json
**Main.xaml**
The workflow in this file is missing log messages, which can make it difficult to track the flow of your automation and identify issues when they occur.

**Message Box (5x)**
The names for these message boxes are very similar and don't give a clear indication of what each one does. Try giving them more descriptive names so that you can easily tell them apart. Right now, there's no limit on the number of times this activity can be used in your workflow.

**Activity Input Dialog**, **Activity Assign**, **Activity State Machine**, and **Activity Message Box (4x)**
These activities all have default names. While this might be fine for a quick test, it would be better to give them more descriptive titles so that you can easily understand what each one does. This will make your workflow easier to read and maintain.

**Score: 3/5**

Note: I've grouped the comments by file name as per your request, using GitHub's formatting.

**Comment by vajrang-b** [comment]
SourceCode/2024/Basics-April2024/Madhuri/Task-27/project.json
**NoFile.xaml**
GitHub comment: The project settings are missing the Automation Hub URL. Please add this information in the Project Settings.

**Subtraction.xaml**
GitHub comment: Log messages should be used to help with understanding the workflow path, both during development and after release. This is helpful for maintenance and identifying errors.
Also, consider renaming the Activity Assign to a more descriptive name to improve code readability.

**Main.xaml**
GitHub comment: The WriteLine activities can be replaced with tracepoints during debug mode. Remove them before publishing the workflow. If they're needed for debugging purposes, consider changing them to Log Message activities instead.

**Addition.xaml**
GitHub comment: Similar to Subtraction.xaml, please add log messages to help understand the workflow path and improve maintenance.
Also, consider renaming the Activity Assign to a more descriptive name to improve code readability.

Score: 5/5

**Comment by vajrang-b** [comment]
SourceCode/2024/Basics-April2024/Madhuri/Task-28/project.json
**Main.xaml**
Log Message not used in workflow
The log message activities are important for understanding the flow path and identifying issues when they occur. Please consider using them during development.

**Extract PDF Page Range.xaml**
display name is defined many times
This activity has multiple instances with the same display name. Please rename these duplicates to clearly indicate their purpose.

**Activities** (multiple)
default names
All activities have default names that are too generic. Please add more descriptive titles to make it clear what each activity does.

**Project Settings.xaml**
No Automation Hub URL defined
Your organization requires this information to be filled in the project settings. Please update the settings accordingly.

Score: 4/5

**Comment by vajrang-b** [comment]
SourceCode/2024/Basics-April2024/Madhuri/Task-26/project.json
Here is my review:

**Main.xaml**
Please use Log Message activities throughout the workflow. This will help with understanding the flow path and identifying errors.

**Duplicate Message Box display names**: Avoid duplicate names, especially if they exceed the allowed threshold of 1. Use more descriptive names to make it clear how each activity is being used.

**Activity Names**: Make sure that names of activities give a clear indication of their purpose. Default names are usually too generic. Aim for unique and descriptive names.

**State Machine, Input Dialog, Message Box**: Consider adding more descriptive titles to these activities to make it easier to understand what they do.

**NoFile**
Add an Automation Hub URL to your project settings. This is a required setting in your organization.

Score: 4/5

**Comment by vajrang-b** [comment]
SourceCode/2024/Basics-April2024/Madhuri/Task-26/project.json
**README.md**
Score: 5/5

The project seems well-organized, but there are some issues that need attention.

**Main.xaml**
* The Log Message activities should be used throughout the workflow to provide clarity on the flow path. This will make maintenance and error handling easier.
* Consider renaming the activities for better understanding of their purpose.

**Message Box**: 
* There are multiple instances with similar names, which exceeds the allowed threshold of 1. Please rename some of them or remove duplicates.
* Names should be descriptive to indicate how they're used in the workflow.

**Activities**:
* The default names for Assign, State Machine, Input Dialog, and Message Box activities can be improved by adding more descriptive titles.
* This will help understand what each activity does without having to look at code.

In summary, focus on renaming activities for better clarity and reducing duplicate message box instances.

**Comment by vajrang-b** [comment]
SourceCode/2024/Basics-April2024/Madhuri/Task-26/project.json
**Workflow.xaml**
The workflow is well-structured, but there are some areas that can be improved for better understanding and maintainability.

* The workflow could benefit from more descriptive activity names. Instead of using generic names like `Activity 1`, consider renaming them to something like `Get User Input` or `Process Order`.
* Some activities have default names, which makes it difficult to understand their purpose without reading the code. Consider renaming these activities to something more descriptive.
* There are multiple instances of `Message Box` activity with default names. This can be confusing, especially when there are many similar activities in a workflow. Consider giving each activity a unique and descriptive name.

**Score: 4/5**

(Note: The score is based on the overall review, not individual points.)

**Comment by vajrang-b** [comment]
SourceCode/2024/Basics-April2024/Madhuri/Task-26/project.json
**Main.xaml**
Using Log Messages would be helpful in understanding the workflow and debugging issues.

**Message Box**
The display names are repeated many times (5). It's better to have unique names that clearly indicate how each message box is being used.

**Activities**

* **Assign**: Consider renaming this activity for better clarity.
* **Input Dialog**: Same as above, consider adding a more descriptive title.
* **State Machine**: Same as above, consider adding a more descriptive title.
* **Message Box**: Each of these activities has the same default name. Consider renaming them to provide clarity on what they're used for.

**Overall Score: 4/5**

The code needs some improvements in naming conventions and logging. The repeated message box names should be changed to unique ones that clearly indicate their purpose.

**Comment by vajrang-b** [comment]
SourceCode/2024/Basics-April2024/Madhuri/Task-26/project.json
**Main.xaml**
Log messages not used in workflow: It's important to include log messages during development and after release to help understand the flow path, which is useful for maintenance and identifying errors.

**Message Box display name**
Many message box display names are defined without a clear indication of their purpose. Try to avoid duplicate names by making them more descriptive.

**Activity names**
Some activity names are too generic. Please provide clear indications of what they do. For example, instead of "Activity", use something like "Get User Input" or "Display Message".

**File not found: NoFile**
Your project is missing an Automation Hub URL. Please add this information in the Project Settings.

Score: 4/5

**Comment by krish952-creator** [comment]
@Madhurichannamaneni 
Task -12
Code verified.
Task -13
Code verified.
Task -15
Code verified.
Task -16
Code verified.
Task -17
Code verified.
Task -18
Code verified.
Task -19
Code verified.
Task -20
Code verified.
Task -21
Code verified.
Task -23
Code verified.
Task -24
Code verified.
Task -25
Code verified.
wait for pending task to verify and approved

**Pull request merged**
