### PR TITLE
Task 10,11 and 13 Completed

### PR DESCRIPTION
**Pull request by Nazeernrb**
Task 10,11 and 13 Completed

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nazeer/Task10/project.json
{
    "NoFile":  [
                   {
                       "Review 1":  "Consider adding a URL to your Automation Hub in the project settings. This is required by the organization, and failing to do so may hinder project execution."
                   },
                   {
                       "Review 2":  "I've noticed that the UiPath.Testing.Activities package is included but not utilized in the code, you can remove it to reduce the project's size and potentially improve execution speed."
                   },
                   {
                       "Review 3":  "The UiPath.UIAutomation.Activities package is also included but I couldn't find any instance where it is used. Deleting it could improve process execution time."
                   }
               ],

    "Score":  {
                   "Code Completion": 2,
                   "Execution": 2,
                   "Annotations and Comments": 1
               }
}

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nazeer/Task11/project.json
Overall score: 1.5 out of 5

👉 Code Completion (1/2): Could not review completion as there are missing information. Remember to include the required project settings such as the Automation Hub URL. Settings are important for project execution.

👉 Execution (0/2): It's hard to predict how well the code will execute since some unnecessary dependency packages like UiPath.Testing.Activities and UiPath.UIAutomation.Activities are included. Removing these can improve execution time. 

👉 Annotations and Comments (0.5/1): No direct notes on comments or annotations, but cleaning up unused code can help make the project more readable and easier to understand.

Action Required: 
- Go to 'Project Settings' to add the necessary Automation Hub URL.
- Remember to remove unused packages to improve execution. 

Keep these points in mind and rock it next time!

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nazeer/Task13/project.json
File: NoFile

- Comment 1: You forgot to define an Automation Hub URL for your project. Please visit the 'Project Settings' and input the necessary information.
- Score: Code completion - 1, Execution - 1, Annotations and comments - 0.5

- Comment 2: The UiPath.Testing.Activities package isn't being used. Remove it to make your process run faster.
- Score: Code completion - 2, Execution - 2, Annotations and comments - 1

- Comment 3: UiPath.UIAutomation.Activities package is in the project but not in use. Removing this will help your process run quicker.
- Score: Code completion - 2, Execution - 2, Annotations and comments - 1

File: Main.xaml

- Comment 1: 'excelData' variable does not have the correct prefix. DataTable Variables should start with a 'dt_' prefix.
- Score: Code completion - 1, Execution - 1, Annotations and comments - 0.5

- Comment 2: 'ResultData' variable also misses the 'dt_' prefix for DataTable variables. Please adjust accordingly.
- Score: Code completion - 1, Execution - 1, Annotations and comments -

**Comment by krish952-creator** [comment]
@Nazeernrb 
Task -10
Code verified.
Task -11
Code verified.
Task -13
Code verified.

**Pull request merged**
