### PR TITLE
Task 28,29,30

### PR DESCRIPTION
**Pull request by ChandupriyaY**
Task 28,29,30

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_28/project.json
File: Main.xaml 

You're facing an error while trying to use 'WriteTextFile' activity. It seems that UIPath is unable to recognize this activity. Make sure you have the correct packages installed and updated. Come back after you've done it and let's try again.

Also, there exists a problem in workflow analysis due to these errors. Let's rectify these errors first and then proceed with the project analysis. Keep going.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_29/project.json
Hey there,

Looks like there's a problem with loading the specified file; i.e. `Main.xaml`. The error seems to be due to an unknown type for `KillProcess`. 

This usually happens when the version of UiPath Studio does not support the `KillProcess` activity or when the correct dependencies/packages are not installed. I'd suggest checking if you have installed the correct packages that the `KillProcess` belongs to and also verify if your UiPath Studio is updated to a version that supports this activity.

Secondly, I see that it's been mentioned that the project analysis cannot be performed because of some errors in the workflows. It would be helpful to know the specific errors to provide relevant solutions.

Sometimes, workflow errors also might be linked to missing dependencies or activities that are not properly implemented or defined in your script. So, ensure to first correct the `KillProcess` error and then try re-analyzing the project.
Keep us posted with any further questions or clearances you need.

Regards,
Your Teammate

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_30/project.json
Hey there, 

Let's fix a couple of issues with your code:

1. First issue is with loading the file at `C:\\VSTS_BA1\\_work\\1\\s\\SourceCode\\2023\\Sep2023\\Basics\\Chandupriya\\Task_30\\Main.xaml`. There seems to be an unrecognized type `{http://schemas.uipath.com/workflow/activities}ForEachRow`. The "ForEachRow" is commonly used in DataTable operations, double-check your activity and namespaces. Make sure that your project has proper dependencies installed (use `UiPath.System.Activities` package from Manage Packages).

2. Due to the error above, the project analysis cannot be performed. Fix the first issue and the analysis should work fine. 

Remember to recompile your project once the changes have been made to ensure all errors have been rectified. Also, double-check your XAML file, sometimes issues pop up due to version differences.

Make these changes and re-commit your code. 

Happy Coding!

**Comment by krish952-creator** [comment]
@ChandupriyaY 
Task -28
Code verified.
Task -29
Code verified.
Task -30
Code verified. Default activity names
 
image

**Pull request merged**
