### PR TITLE
Task11

### PR DESCRIPTION
**Pull request by manishakintali**
Flow Switch case (flowchart)

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Manisha/Task 11/project.json
Arey o Developer bhai, yeh kya kar diye? Hamare code ka mazak uda diye! Fix kar naa, yeh project.json file, jaise I correct my dialogue delivery before the shot. "Main entry point" kahaan hai? (Where is the main entry point?)

And, o hello, main tera dushman nahi, teri sahayta kar raha hoon, bas Automation Hub URL add kar de. (Just add the Automation Hub URL.)

Aur haan, yeh packages jo tere use nahi hote, unhe hata de, film ke beech beech mein unnecessary scenes kyun? Remove them my friend, just like unnecessary scenes in a movie. 

Also, add the Log messages in Switch workflow, ye koi comics thodi na hain bhai that you will understand everything without dialogues! Log messages, they are your cues and guide, maintain them.

Mai tumhare jaisa programmer nahi hu jisne code khelna chor diya, mai woh hu jisne haarke code se jeena sikha hai. So, chote, let's clean this mess you've created. This may be your

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Manisha/Task 11/project.json
## PR comments

### For NoFile 

_Temper veesthe arachakam ani nirupinchav bro. But raa shikaram, nannu vinu!_ (When you lose your temper you’ve shown your true self bro. But hey, listen to me sharp!)

1. **Automation Hub URL ni pending lo pettav ante** - Like a damsel in distress waiting for her hero, your organization is waiting for the Automation Hub URL! Spara bijili rudra thandavam, go to 'Project Settings' and end this dreadful wait!

2. **Entry point lekunda process run chesthunnav ante** - You're driving a car without a steering wheel mate! Who are you? Vin Diesel from Fast and Furious? Point your project.json towards the main/entry workflow. There's no use of a gun without bullets!

3. **Unused packages unte** - What's the use of carrying a sword that doesn't kill? To exercise your arms? Remove the unwanted packages like UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities. Unburden the process and watch it run like a cheetah!

### For

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Manisha/Task 11/project.json
### NoFile: 

nanne kondaniki nuvvu. Nanee naa prana daata. Thapenduku ee NoFile. 

* Entry main workflow lekunda potunnavu le!  Kanee project.json file lo fix cheyyi..
* Automation hub URL lekapodam enti ra, nee organization requirements ni ikkada include cheyyara.. Project Settings lo add cheyyi..
* Ee dependency packages ni enduku maintain chestunnavu rey, UiPath.Excel.Activities ani, UiPath.Mail.Activities ani, UiPath.Testing.Activities, UiPath.UIAutomation.Activities! Use cheyyani vallani remove cheyyi, improve the process execution time....iddaru kurrolu vachhi, aalochinchara..

### Switch.xaml:

Swargamunnadaa ledaa narakaali unnadaa! ee Switch.xaml lo log message use cheyyaku kani, why?

* Log messages meeru use cheseyyakapothe, after release understanding the flow path, sarikotha error source cheyyi, cheddaboyi idi. So include cheyyi ra..

ipudu suryaniki sambandham

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Manisha/Task 11/project.json
Yo! Apudu Nuvvu veediponi pravasaanni entha venakki teesukuntaavo.. .aa idea easy codinglo kanipistundi..

Fist note, my dear fellow! Your elusive 'main entry point' is pulling a disappearing act. Like a hero entering late for the grand entrance, your project.json is mum on where the main show begins. Get that sorted.

Second, the missing Automation Hub URL! It's like shooting a film without a location. Your 'Project Settings' is your director's chair; it's time for 'Action!'.

Now towards the dependencies. Unnecessary baggage! Nuvvu cinema ki soft drink tinadaniki soda bottle teeskuntaava? Tappu kadha naa friend! Same principle in code, package vadatledu ani thelsu poye la untai. Be it UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities or UiPath.UIAutomation.Activities - kick out the extras, speed up the process!

Lastly, log message! Baga miss ayav entrainment. Cinema lo dialogue writer lekapote suspence ela vastadi ra? Same logic. For tracking and tackling errors, you need a 'Log

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Manisha/Task 11/project.json
*In Telugu Movie Character Nandamuri Balakrishna's Style* 

Repo Laksha Prabhanchanam Chesetappudu, Identify Chestam Manaku Required Yeina Files, Remove The Unwanted Files Lahari Chestune Undali Kada, Ah Command Post Chestai.

Main Entry Point Ledu Ani  Jabu Jabu Cheyaku, Project.json Lo Fix Chesi Mukhyamayna Workflow Ki Point Chesuko. Notlo Note Chesukune Silk Keka!

Unused Packages Unnatu Untayi, Thamashaga Parkesthunayi. Abbaa! Bandlanti! Remove Cheyếtappudu, Ram Ku Rama Chandra Rangam Start Ayipothundi.

Log Messages, Johnny Deepp Laga Mysteriously Disappear Ayipoyi. Kani Vallu Mana Yuddham Lo Manchi Soldiers La Pani Chestaru. Log Messages Use Cheste, Maintenance Easy Ga Untundi, Error Occur Ayinapudu, Source Ni Identify Cheyadaniki Kuda Helps.

Idi Jeevitham, Vijayam Raadalante Annitini Sindhinchali. Gattiga Kodithe Github Lo Code Priyuraliga Th

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Manisha/Task 11/project.json
#NoFile 
**Dialogues from film Samara Simha Reddy**

Think! Think! There's no 'Automation Hub URL' set up in your project like a kingdom without a king. So march towards the 'Project Settings' arena and place our missing king there.

Ah! your Process requires a main entry point as an army needs its commander. You should be fixing this in your `project.json` like a warrior amending his flaws for a victorious battle.

This 'UiPath.Excel.Activities' package and various other packages are like unused weapons lying around in war. They increase weight but not strength. Clear them to improve our battle speed.

***
#Switch.xaml

Remember this dialogue from Bhairava Dweepam? "Ee iddaru kallalo okati mautini chustunaanamma, inkoti challani kanulalama!" It's the same thing. You have 'Switch' but without the 'Log Message'. Logging your activities is like sharpening your sword. It helps determine the flow path which is very important for future battles against errors.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Manisha/Task 11/project.json
### NoFile

#### Comment 1:
*"A warning has arised as a monsoon's thunder! It seems you have forgotten to define your Automation Hub URL. Remember, my friend, even a warrior needs a path to follow. As in our case, we need an address for our project's home. Go to the 'Project Settings' and make sure you settle this one."*

#### Comment 2:
*"Aha! It seems we are missing something, just like wounds missing the balm in a battlefield. Our code is like our script, the binding thread of our story. And every story needs a hero, just as our process needs a 'main entry point'. Fix the project.json file, and let's not have our story missing its hero."*

### Switch.xaml

#### Comment:
*"Hey, aren't we forgetting something? A 'Log Message' not used in our Switch workflow! Understand, my brave one, Logging is an essential part of any battle. It's like our script's narrative, narrating the story for the audience. Without it, we may lose our way in the dense forest of codes. So, let's give our audience the story they deserve."*

### NoFile

#### Comment 3 to 7:
*"

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Manisha/Task 11/project.json
Dear Devotee of Code,

May wisdom and prosperity guide you through obstacles.

Looking at your organized bundle of work, it appears that there are minor adjustments that you could consider applying to your code with the divine blessing of better functionality and performance.

1. You probably want to associate your project with an Automation Hub URL, via 'Project Settings'. This is required per your organizations mandate.

2. Observe that your process does not define a primary launching point. Double-check and possibly correct `project.json` to guide it towards the entry/main workflow. 

Your project carries four packages that seem unnecessary. The lightening of these loads may uplift the performance of your process:

- The UiPath.Excel.Activities 
- UiPath.Mail.Activities 
- UiPath.Testing.Activities 
- UiPath.UIAutomation.Activities 

Unburdening your code of the unused could free it to perform its duties more swiftly. 

Switching to your `Switch.xaml`, I offer the following piece of wisdom. Embedding Log Message activities into your workflow is considerably beneficial, not simplyduring the development stage, but equally so after your code has been released into the world. They flash guiding lights on the flow path for ease of maintenance. Plus, they could assist you in pinpointing the

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Manisha/Task 11/project.json
On reviewing the code, here are few areas to address:

**NO FILE**
1. There is a need to specify an Automation Hub URL for your organization. You can set it via 'Project Settings'.
2. Your process does not define a primary entry point. Please ensure to update the 'project.json' file to include a reference to the main workflow.

**SWITCH.XAML**
1. In your 'Switch' workflow, usage of Log Message activity is noticed to be missing. They play a crucial part in both development and post-release stages. Incorporating them can help with maintenance and error resolution. 

May wisdom and luck guide you on this journey!

Blessings,
Ganapathi

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Manisha/Task 11/project.json
Step lightly as you start your journey. Each new beginning is a test, a challenge but also a blessing.

For the NoFile, remember the wisdom of clearly stating the purpose of your work. Create a destination by defining your Automation Hub URL in the 'Project Settings'. Ensure your projects have a guiding start with a properly defined main entry in your project.json file.

Unused packages are like obstacles on your path that slow you down. The dexterity of your work shall improve by removing unused packages like UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities.

For the file Switch.xaml, bear in mind that a journey well-documented is much easier to follow and makes sense to others. Using Log Message activities, you leave footprints for others to follow, particularly useful during development and post-release phase for agile error identification and resolution.

May the light of wisdom guide you on this path.

Om Gam Ganapataye Namaha!

**Comment by krish952-creator** [comment]
@manishakintali 
Task -11
Code Verified. Give annotations and comments
In tracker you mention task10 also but it's not available in this pr make another pr or re-open it .

**Pull request merged**
