### PR TITLE
Task 123 are complated

### PR DESCRIPTION
**Pull request by sharidas2210**

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Sruthilaya/Task1/project.json
Main.xaml: 

Log Message not used in workflow Main. --> Let's fix this. Add some Log Message activities. They are helpful for tracking actions, for debugging during development, and for understanding the workflow path, so if something goes wrong we can easily find where the issue is. 

NoFile: 

Your organization requires your project to have an Automation Hub URL defined. --> Go to Project Settings and set the Automation Hub URL there. It is a must-do according to our organization's requirements.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Sruthilaya/Task2/project.json
Main.xaml:

1. Regarding the Log Message not used in Main workflow: Consider adding 'Log Message' activities throughout your workflow. These help track the flow of activities during development and debug issues after release. Simply, it's a way of noting down what's happening so you can understand or find problems later.

NoFile:

1. Concerning the missing Automation Hub URL: Your project is required to have this URL. You can add it via 'Project Settings'. It's like giving your project a home address so everyone knows where to find information about it.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Sruthilaya/Task3/project.json
That's great! No changes needed. Good job, keep up the good work!

**Comment by krish952-creator** [comment]
@sharidas2210 
Task -1
Code verified.
Task -2
Code verified.
Task -3
Code verified.

**Pull request merged**
