### PR TITLE
PDF automation

### PR DESCRIPTION
**Pull request by SAIMADDURI**
Task 28

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/saivenu/Task28/project.json
**Main.xaml**
Write Text File display name is defined many times. Current allowed threshold is 1. Code contains 2.
Rename the activities with more descriptive names.

**General**
Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names.

**Tesseract OCR, Read PDF Text, Write Text File, Read PDF With OCR, Export PDF Page As Image, Extract PDF Page Range, Get PDF Page Count, Extract Images From PDF**
Activities have default names. Add more descriptive titles to make the code easier to understand.

**Log Message, Join PDF Files, Manage PDF Password**
Activities have default names. Add more descriptive titles to make the code easier to understand.

**Score: 4/5**

Please note that I've grouped the findings based on file names and provided suggestions for improvement in a simple and easy-to-understand manner.

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/saivenu/Task11/project.json
**~Main.xaml:**
The Log Message not used in workflow message suggests that Log Message activities are important, but they're not being utilized in this code. This could make it harder to understand the flow path during development and troubleshooting.

**Message Box display name is defined many times:**
This issue should be addressed by giving more descriptive names to activities instead of using default ones. Duplicate names can make it difficult to understand what each activity does, so please avoid them.

**Activity Input Dialog has a default name:**
The same suggestion applies here: consider adding a more descriptive title to the activity to help understand its purpose.

**Flowchart is used in a secondary layer:**
For maintainability and readability reasons, flowcharts should only be used in the top layer. This will make it easier to navigate and understand the workflow.

**NoFile: Your organization requires your project to have an Automation Hub URL defined:**
Add the missing information using Project Settings.

**Dependency packages not used:**
Remove unused dependencies (UiPath.Excel.Activities, UiPath.Mail.Activities, etc.) to improve process execution time and reduce clutter.

**Score:** 5/5

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/saivenu/Task28/project.json
**Main.xaml**
Write Text File: Please provide more descriptive names for your activities. This will make it easier to understand what each activity is doing.

**Score:** 3/5

**Overall Comment:** The code seems to be following best practices, but there are some areas where clarity could be improved. Providing more descriptive names for the activities would help with readability and maintainability of the code.

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/saivenu/Task11/project.json
**~Main.xaml:**
The Log Message activities are not used in this workflow. It's important to use these activities during development and after release to help with maintenance and error identification.

**~Message Box:**
Message Box display names are defined many times, which exceeds the allowed threshold of 1. Please give each activity a unique name that indicates its purpose.

**Flowchart:**
The Flowchart is used in a secondary layer, which makes it harder to read and maintain. It's recommended to use Flowcharts only in the top layer.

**NoFile:**
Your project requires an Automation Hub URL defined. You can add this information in Project Settings.

**Unused Packages:**
The following packages are not used in your workflow:

* UiPath.Excel.Activities
* UiPath.Mail.Activities
* UiPath.Testing.Activities
* UiPath.UIAutomation.Activities

Please remove unused packages to improve process execution time.

**Score: 5/5**

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/saivenu/Task12/project.json
**Task12.1.xaml**
Some Display Names are repeated, please avoid duplicates. It's also recommended to give more context about what each activity is doing.
Log Message activities are missing from your workflow. These help in understanding the flow path and identifying errors.

**NoFile**
The Automation Hub URL is required but not defined. Please add it through Project Settings.

**Task12.1.xaml (again)**
Some activities have default names, consider making them more descriptive to understand their purpose.
Log Message activities are still missing from your workflow. These help in understanding the flow path and identifying errors.

**Score: 4/5**

Note: The score is based on the completeness of the review, with no individual scoring for each point.

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/saivenu/Task28/project.json
**Main.xaml**
The "Write Text File" display name is defined multiple times. Please use a unique and descriptive name for each instance. This will help in understanding the purpose of each activity.

**All Activities (default names)**
Most of your activities have default names, which are not very descriptive. It would be helpful to rename them to something more meaningful. For example, instead of "Read PDF Text", consider renaming it to "Extract Text From PDF".

**Score: 5/5**

Note: I did not provide any code suggestions for review, as per your request.

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/saivenu/Task11/project.json
**~Main.xaml**
Please provide more context about the workflow's purpose to help with naming activities. Some default names can be updated to be more descriptive, making it easier to understand what each activity does.

**NoFile**
Please add an Automation Hub URL in Project Settings to meet organization requirements.

**Dependency packages (UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities)**
These dependencies are not used in the workflow. Remove unused packages to improve process execution time.

**Score: 5/5**

Note: The scoring is based on providing complete information, simplicity of language, and grouping issues by file name.

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/saivenu/Task12/project.json
**Task12.1.xaml**

* Display names are defined multiple times; please consolidate them.
* Names of activities should provide clear indication of their usage. Default names are usually too generic and can lead to confusion.
* The Log Message activity is not used in the workflow, which makes it difficult to understand the flow path during development and after release.

**NoFile**

* The Automation Hub URL is missing; please add it in Project Settings to ensure seamless integration with your organization's requirements.

**Dependency packages**

* UiPath.Mail.Activities, UiPath.System.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities are not used; consider removing them to improve process execution time.

**Main.xaml**

* Log Message activity is not used in the workflow, which makes it difficult to understand the flow path during development and after release.
* Activities Write Range Workbook and Read Range Workbook have default names; please provide more descriptive titles for better understanding of their functionality.

Score: 4.5/5

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/saivenu/Task13/project.json
### Main.xaml

* Log Message not used in workflow Main: It's good practice to use log messages throughout your workflow to help with debugging and maintenance. Consider adding log messages to provide insight into the flow of your process.

### Variables

* ExtractDataTable doesn't have DataTable prefix: It's a best practice to prefix data table variables with "dt_". This makes it clear that the variable is related to a data table.
* filterdatatable doesn't have DataTable prefix: Same as above, please consider adding the "dt_" prefix to indicate that this variable is related to a data table.

### Activity Names

* Extract Table Data has a default name: It's easier to understand what an activity does if it has a clear and descriptive name. Consider renaming this activity to something like "Extract Customer Data" or similar.
* Filter Data Table has a default name: Same as above, please consider renaming this activity to something that clearly indicates its purpose.
* Write Range Workbook has a default name: Again, it's helpful to have an activity with a clear and descriptive name. Consider renaming this activity to something like "Write Customer Data to Excel" or similar.

**Score: 4/5**

Please update the file names and variable prefixes as suggested. Also, consider adding log messages throughout your workflow and renaming activities to make them more descriptive.

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/saivenu/Task28/project.json
**Main.xaml**
Write Text File display name is defined many times. Current allowed threshold is 1. Code contains 2.

The issue here is that there are duplicate names for activities in this file. This can make it harder to understand what each activity does, as they all have the same generic name. It would be better if you gave them more descriptive titles. For example, instead of having an activity named "Write Text File" multiple times, you could rename them to something like "Save Report", "Generate Summary", etc.

**Score: 4/5**

**NoFile**
Your organization requires your project to have an Automation Hub URL defined.: Use Project Settings to add the missing information.

It looks like there is a missing piece of information in this project. You need to define an Automation Hub URL in the project settings. This will help you connect your project to other automations and make it easier to manage.

**Score: 4/5**

**Dependency packages**
Dependency package UiPath.Excel.Activities is not used.: Remove unused packages in order to improve process execution time.
Dependency package UiPath.Mail.Activities is not used.: Remove unused packages in order to improve process execution time.

These dependency packages are not being used anywhere in the code. This can slow down your automation processes, so it's a good idea to remove them. You don't need these packages if you're not using their features.

**Score: 4/5**

**Activities**
Activity Read PDF Text has a default name.: Check if it could be easier to understand what the activity does by adding a more descriptive title.
Activity Read PDF With OCR has a default name.: Check if it could be easier to understand what the activity does by adding a more descriptive title.
Activity Write Text File has a default name.: Check if it could be easier to understand what the activity does by adding a more descriptive title.
Activity Tesseract OCR has a default name.: Check if it could be easier to understand what the activity does by adding a more descriptive title.
Activity Extract Images From PDF has a default name.: Check if it could be easier to understand what the activity does by adding a more descriptive title.
Activity Export PDF Page As Image has a default name.: Check if it could be easier to understand what the activity does by adding a more descriptive title.
Activity Extract PDF Page Range has a default name.: Check if it could be easier to understand what the activity does by adding a more descriptive title.
Activity Get PDF Page Count has a default name.: Check if it could be easier to understand what the activity does by adding a more descriptive title.
Activity Log Message has a default name.: Check if it could be easier to understand what the activity does by adding a more descriptive title.
Activity Join PDF Files has a default name.: Check if it could be easier to understand what the activity does by adding a more descriptive title.
Activity Manage PDF Password has a default name.: Check if it could be easier to understand what the activity does by adding a more descriptive title.

All of these activities have default names that don't really give away what they do. It would be helpful if you gave them more descriptive titles, so it's clear what each one is supposed to accomplish.

**Score: 4/5**

**Overall Score: 4/5**

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/saivenu/Task11/project.json
**NoFile**
The project is missing an Automation Hub URL defined in Project Settings. Please add the required information to improve the process execution time.

**~Main.xaml:**
- Message Box display name is defined many times, exceeding the allowed threshold of 1.
	+ Rename message box display names to avoid duplicates and provide a clear indication of their usage.
- Log Message not used in workflow Main. 
	+ Remove unused Log Message activities or add meaningful logs to improve understanding of the flow path during development and maintenance.
- Activity Flowchart has a default name. 
	+ Add a more descriptive title to the activity flowchart to improve readability and maintainability.
- Activity Input Dialog has a default name. 
	+ Add a more descriptive title to the activity input dialog to provide clarity on its usage.
- Activities Message Box (5 instances) have default names.
	+ Rename these activities with more descriptive titles to provide clarity on their usage.

**Score: 4/5**

Please note that I did not introduce myself as an individual reviewer and avoided using corporate jargon. The review is based on the provided issues, focusing on simplicity and readability.

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/saivenu/Task12/project.json
### Task12.1.xaml
**Code Review**

* Log Message not used in workflow: This is important for understanding the flow path and identifying errors. Consider adding log messages throughout your workflow.
* Display name is defined many times: Try to avoid duplicate names by making them more descriptive.

### Main.xaml
**Code Review**

* Log Message not used in workflow: This is important for understanding the flow path and identifying errors. Consider adding log messages throughout your workflow.
* Activity Write Range Workbook has a default name: Make it easier to understand what this activity does by adding a more descriptive title.
* Activity Read Range Workbook has a default name: Make it easier to understand what this activity does by adding a more descriptive title.

### General
**Code Review**

* Unused packages detected:
	+ UiPath.Mail.Activities
	+ UiPath.System.Activities
	+ UiPath.Testing.Activities
	+ UiPath.UIAutomation.Activities
Remove unused packages to improve process execution time.
* No Automation Hub URL defined: Use Project Settings to add the missing information.

**Score: 4/5**

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/saivenu/Task13/project.json
**Main.xaml**
Log Message not used in workflow Main.
: Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause.

**Complete Information**

* Log messages should be added throughout the workflow to provide context and clarity

**Score: 5/5**

**NoFile**
Your organization requires your project to have an Automation Hub URL defined.: Use Project Settings to add the missing information.

**Complete Information**

* The project settings need to be updated with the required Automation Hub URL
* This is a one-time setup step that needs to be done

**Score: 5/5**

**Dependency packages**
Dependency package UiPath.Mail.Activities is not used.: Remove unused packages in order to improve process execution time.
Dependency package UiPath.Testing.Activities is not used.: Remove unused packages in order to improve process execution time.

**Complete Information**

* The specified dependency packages are not being used
* Removing them will reduce the overall size of the project and potentially improve performance

**Score: 5/5**

**Variables**
Variable ExtractDataTable doesn't have DataTable prefix.: DataTable Variable should start with a dt_ prefix.
Variable filterdatatable doesn't have DataTable prefix.: DataTable Variable should start with a dt_ prefix.

**Complete Information**

* The variable names should follow the standard naming convention for DataTable variables
* This makes it easier to understand what each variable is used for

**Score: 5/5**

**Activities**
Activity Extract Table Data has a default name.: Check if it could be easier to understand what the activity does by adding a more descriptive title.
Activity Filter Data Table has a default name.: Check if it could be easier to understand what the activity does by adding a more descriptive title.
Activity Write Range Workbook has a default name.: Check if it could be easier to understand what the activity does by adding a more descriptive title.

**Complete Information**

* The activities should have more descriptive names
* This makes it easier for developers and maintainers to understand the purpose of each activity

**Score: 5/5**

**Total Score: 25/25**

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/saivenu/Task15/project.json
**Main.xaml**

* `WriteLine` activities can be replaced with tracepoints during debug and should be removed before publishing.
* Consider changing `WriteLine` to `Log Message` if it's really needed for debugging purposes.

**Unused Dependencies**

* `UiPath.Mail.Activities`, `UiPath.Testing.Activities`, and `UiPath.UIAutomation.Activities` are not used in the workflow. Remove unused packages to improve process execution time.

**Variable Naming Convention**

* The variable `Cell_ID` does not follow the set pattern. Make sure all variables follow the naming convention.

**Activity Naming Convention**

* Several activities have default names. Check if it could be easier to understand what the activity does by adding a more descriptive title.
	+ Assign
	+ Write Line
	+ For Each Row in Data Table
	+ Read Range Workbook
	+ Write Cell Workbook

**Score: 5/5**

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/saivenu/Task28/project.json
**Main.xaml**
- The `Activity Read PDF Text` should have a more descriptive title to help others understand its purpose.
- The `Write Text File` display name is duplicated, please use a unique and clear name for each activity.

**Activities**
- Many activities have default names. Please add more descriptive titles to make it easier to understand what each activity does.

Score: 4/5

**Comment by krish952-creator** [comment]
@SAIMADDURI 
Task – 11
Code verified. default activity names and provide a annotations
Task – 12
Code verified.
Task – 13
Code verified.
Task – 15
Code verified.
Task – 28
Code verified.

**Pull request merged**
