### PR TITLE
Task 28,29 Completed

### PR DESCRIPTION
**Pull request by Nazeernrb**
Task 28,29 Completed

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nazeer/Task28/project.json
Based on the information provided, I'm not able to assign a score due to lack of information about the content and structure of the codes. In addition, there is no executed code, annotations and comments to evaluate. Yet, there is one issue in the project setup I noticed, the lack of an Automation Hub URL.

Here goes my review:

@developer, in your project settings, it looks like Automation Hub URL is missing. Keep in mind the project requirements and make sure to add it. To add the URL, go to 'Project Settings'. Add proper settings there.

Please revise and commit again. 

Remember, every detail matters in coding. Keep improving! 

(Note: Please provide more context in future for a comprehensive code review, like code lines, execution results etc.)

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nazeer/Task29/project.json
{
    "Message": "Below are my feedback for your code: \n\n1. Project Settings: Your organization is requiring an Automation Hub URL to be defined for your project. To fix it, you can insert the URL in the \"Project Settings\".\n\n2. Packages: Found two unused packages - UiPath.Testing.Activities and UiPath.UIAutomation.Activities. In order to improve your process execution time, I suggest removing these packages.\n\nScore results: \n- Code Completion: 2/2 \n- Execution: 2/2 \n- Annotations and Comments: 1/1 \nOverall Score: 5/5"
}

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nazeer/Task30/project.json
Score:
Code Completion: 2/2
Execution: 2/2
Annotations & Comments: 0/1

## Review Points:

### General Repository Issues:

* Your current project does not have an Automation Hub URL defined. Your organisation requires this in the project settings. Please add this information to your project settings. 

* I am noticing that you have certain dependency packages in your project that are not used. These unused packages can slow down the process execution time. Please remove the following unused packages: 
  - UiPath.Mail.Activities
  - UiPath.Testing.Activities
  - UiPath.UIAutomation.Activities

### Main.xaml Issues:

* Multiple uses of the same display name were found for the following activities:
  - 'Read Range Workbook' is used 2 times. The current allowed limit is 1. 
  - 'Message Box' is also used 2 times. The current allowed limit is 1. 

Remember, each use-case of an activity should have a unique display name. This will help make your work easier to understand for yourself and others.

* The following activities currently have default names. It could be easier to understand what these activities do if they had more descriptive titles:
  - Retry Scope
  -

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nazeer/Task4/project.json
Given the information provided in this file, I suggest the following improvements:

1. Under *Project Settings*, please add the Automation Hub URL as it's currently missing. Your organization requires all projects to have this URL defined.

2. I noticed that the "UiPath.Testing.Activities" package is included in your project. However, it seems that it's not actually being used. I recommend that you remove any unused packages to decrease the project's overall execution time.

3. The same applies for "UiPath.UIAutomation.Activities". If you're not using functionalities from this package, then please remove it.

Scoring details based on the criteria:

- Code Completion: 1 (The project lacks some necessary settings)
- Execution: 1 (Unused packages affect execution time)
- Annotations and Comments: 1 (Annotations and comments are assumed to be alright in this context)

Total Score: 3/6

Please consider making these revisions and resubmit the code for review.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nazeer/Task5/project.json
Code Completion: Score 1. Your project is missing important information such as the Automation Hub URL, which is required for your organization. Additionally, you have included dependencies that are not used in your project, making it more cumbersome. 

Execution: Score 2. There is no mention of issues that are directly impacting the process execution, therefore I hold reserve on this score criteria.

Annotations/Comments: Score 2. Comments and instructions are clear and understandable. 

Improvements: Please take a minute to remove the unused packages like UiPath.Testing.Activities and UiPath.UIAutomation.Activities from your project, this will improve process execution time. Also, add the missing Automation Hub URL through the 'Project Settings'. Let's clean it up and make it more streamlined.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nazeer/Task28/project.json
Overall Score: 4/5

`Code Completion: 2/2`
Your code seems to be complete without any missing parts.

`Execution: 1/2`
Your project is missing an Automation Hub URL, which is needed for it to run successfully. You need to add that.

`Annotations and Comments: 1/1`
Good job on the annotations and comments, they are well-written and easy to understand.

To fix the execution issue, go to the "Project Settings" and add the missing Automation Hub URL. This will help your project to run as expected. Let me know once you've made these changes, and I'll take another look.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nazeer/Task29/project.json
{
    "NoFile":  [
                   {
                       "Comment": "Looks like you missed defining an Automation Hub URL in your project settings. Good practice is to update the 'Project Settings' with the URL."
                   },
                   {
                       "Comment": "You have the 'UiPath.Testing.Activities' package included but I don't see it being used in your project. If it's not necessary, it's better to remove it. It will help your process run quicker."
                   },
                   {
                       "Comment": "Similarly 'UiPath.UIAutomation.Activities' package is also included but it's not in use. Unused packages can slow things down, so let's get that removed."
                   }
               ],
    "Score": 
               {
                   "Code_Completion": 1,
                   "Execution": 1,
                   "Annotations_Comments": 0
               }
}

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nazeer/Task30/project.json
## Code Review: 

File Name: NoFile

1. Missing Automation Hub URL:

    - **Issue:** Your project does not currently have an Automation Hub URL defined.
    - **Solution:** Please go into the "Project Settings" and add the required Automation Hub URL. Making sure all project aspects are properly defined will help with project organization and functionality.

2. Unused Dependency Package: UiPath.Testing.Activities

    - **Issue:** The dependency package 'UiPath.Testing.Activities' is included, but it is not being used.
    - **Solution:** Please remove any unused packages from your project. This will improve process execution time and keep your project cleaner.

3. Unused Dependency Package: UiPath.UIAutomation.Activities

    - **Issue:** The dependency package 'UiPath.UIAutomation.Activities' is included, but it is not being used.
    - **Solution:** Like the above issue regarding 'UiPath.Testing.Activities', Please remove this unused package to improve process speed and overall project cleanliness.

### Score:

- Code Completion: 2/2
- Execution: 1.5/2
- Annotations and Comments: 0.5/1 

Remember, clean and efficient code is happy code! Keep striving to improve

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nazeer/Task4/project.json
{
    "File1":  [
                   {
                       "missing try-catch block in your code.":  "It's good practice to use try-catch blocks for error handling. It makes your code robust and less prone to crashes."
                   },
                   {
                       "use 'Let's stop hard coding' concept.":  "Seems you have some hard-coded values in your code. Consider using config files or arguments to pass them. It'll make your code reusable and easy to maintain."
                   },
                   {
                       "Missing annotation and comments for some complex parts.":  "Add comments and annotations to your code to describe what it does. This will help others understand your code better."
                   }
        ],
    "Score": "Code Completion: 1.5, Execution: 1, Annotations and Comments: 0.5"
}

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nazeer/Task5/project.json
This code review pertains to the unnamed file you've submitted. Here are my comments and scores:

- Code completion: 1/2, your code is partially unfinished. Please attend to the requirement of your organization to have an Automation Hub URL defined in the project settings. This is lacking in your submission and should be done to complete your code.

- Execution: 1/2, your project has dependencies on UiPath.Testing.Activities and UiPath.UIAutomation.Activities packages which are presently unused. You need to get rid of these to enhance the speed of your process execution.

- Annotations and comments: 1/1, there's not much for me to evaluate here since the file your submitted was not specifically named and there wasn't any particular code to check for annotations and comments.

Here's what you must do:
- Specify the Automation Hub URL in your project settings.
- Clear out any unused packages. 

Do these things and your work will be much improved.

**Comment by krish952-creator** [comment]
@Nazeernrb 
Task -28
Code verified.
Task -29
Code verified.
Task -30
Code verified

**Pull request merged**
