### PR TITLE
Task1

### PR DESCRIPTION
**Pull request by Praveenkasetti**

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Praveen/Task1/project.json
**Main.xaml**
Log messages are essential for understanding the workflow's flow path during development and after release. It helps with maintenance and identifying the source and cause of errors.

* Make sure to use log message activities throughout the workflow.
* This will make it easier to debug and maintain your automation in the future.

**Activity Message Box**
The default name of this activity doesn't give much information about its purpose. Consider renaming it to something more descriptive, like "Show Error Message" or "Display Confirmation".

**Activity Input Dialog**
Like the previous activity, the default name here also lacks context. Rename it to something that clearly indicates what it's intended for, such as "Get User Input" or "Request Confirmation from User".

**Score: 5/5**

Please make sure to address these points and resubmit your pull request for review.

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Praveen/Task1/project.json
**Main.xaml**
Log Message not used in workflow Main.: Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause.

Recommendation: Add log messages throughout the workflow to better understand its behavior and make it easier to troubleshoot issues that may arise.

**Overall Score: 5/5**

Please let me know if you need any further assistance.

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Praveen/Task2/project.json
**Main.xaml**
Input Dialog display name is defined many times. Current allowed threshold is 1. Code contains 2.
Rename input dialog activities to provide a clear indication of how they are being used, e.g., "Get User Input" instead of just "InputDialog".

**Assign**
Assign display name is defined many times. Current allowed threshold is 1. Code contains 3.
Rename assign activities to provide a clear indication of what value is being assigned, e.g., "Set Customer ID" instead of just "Assign".

**Message Box**
Message Box display name is defined many times. Current allowed threshold is 1. Code contains 2.
Rename message box activities to provide a clear indication of the message being displayed, e.g., "Display Error Message" instead of just "MessageBox".

**Activities with default names**
Activity Assign has a default name.: Check if it could be easier to understand what the activity does by adding a more descriptive title. (Multiple instances)
Rename these activities to provide a clear indication of what value is being assigned, e.g., "Update Order Status" instead of just "Assign".

**Activities with default names**
Activity Message Box has a default name.: Check if it could be easier to understand what the activity does by adding a more descriptive title. (Multiple instances)
Rename these activities to provide a clear indication of the message being displayed, e.g., "Display Confirmation Message" instead of just "MessageBox".

**Activities with default names**
Activity Log Message has a default name.: Check if it could be easier to understand what the activity does by adding a more descriptive title. (Multiple instances)
Rename these activities to provide a clear indication of the log message being written, e.g., "Log Order Status Update" instead of just "LogMessage".

**Activities with default names**
Activity Input Dialog has a default name.: Check if it could be easier to understand what the activity does by adding a more descriptive title. (Multiple instances)
Rename these activities to provide a clear indication of what input is being requested, e.g., "Get Order Details" instead of just "InputDialog".

**Score: 4/5**
The code review suggests that there are many opportunities for improvement in terms of naming conventions and readability. By renaming the activities with more descriptive names, it will be easier to understand the purpose of each activity.

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Praveen/Task7/project.json
**Main.xaml**
The `Log Message` activity is not being used in your workflow `Main`. This can make it harder to understand the flow of your process, especially during development or when debugging issues.

* Review suggestion: Make sure you're actually using these log messages elsewhere in your workflow. If not, consider removing unused activities to declutter your code and improve performance.
**Score:** 5/5

Let me know if there's anything else I can help with!

**Comment by krish952-creator** [comment]
@Praveenkasetti 
Task -1
Code verified. Provide a annotations and change default activity names
 
image

Task -2
Code verified. Provide a annotations and change default activity names

**Pull request merged**
