### PR TITLE
Task_6_7_8_9_Completed

### PR DESCRIPTION
**Pull request by PRAVEENRAJA1699**

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/oct2023/Basics/Praveenraja S V/Task_6/project.json
## Score
Code Completion: 1  
Execution: 1  
Annotations and Comments: 0  

## Review  

#### NoFile:  

- Your project is missing the required Automation Hub URL. Please add this information in the 'Project Settings'.
- There's an unused package in your project - 'UiPath.UIAutomation.Activities'. Unused packages can slow down process execution, so please remove any that you're not using.

#### Main.xaml:

- You haven't used any 'Log Message' activities in your 'Main' workflow. These should be used during development and after release. They help us to understand the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the reason for it. Please add 'Log Message' activities where necessary. 

Please attend to these points and resubmit your project.

**Comment by vajrang-b** [comment]
SourceCode/2023/oct2023/Basics/Praveenraja S V/Task_7/project.json
File: NoFile
Your project needs to have an Automation Hub URL, you can input this through the 'Project Settings' part.

Also, there's an unused package in your code, UiPath.Testing.Activities. Removing this will help your porcess run faster.

The UiPath.UIAutomation.Activities package is also unused and should be eliminated for better efficiency. 

File: Main.xaml
I've noticed there's no Log Message activity used in Main workflow. Incorporating these can be beneficial during not only development but also post-launch. It will aid in understanding the flow path, which will be important for maintenance. Plus, if an error crops up, it's easier to pinpoint the source and reason behind it with log messages.

Code Completion Score: 1.5 because of the unused packages and no automation hub url defined
Execution Score: 2 - No details available suggesting any runtime issues.
Annotations and Comments Score: 1 - Log message activity is missing which is important for understanding process flow.

**Comment by vajrang-b** [comment]
SourceCode/2023/oct2023/Basics/Praveenraja S V/Task_8/project.json
Scores :
Code completion: 1.5
Execution: 1.5
Annotations and comments: 0.5 

Files and code review comments:

1. NoFile
   - It seems you've missed defining an Automation Hub URL. Hop on over to the "Project Settings" and add the necessary info.
   - Found some unused packages ('UiPath.Testing.Activities' and 'UiPath.UIAutomation.Activities'). Trimming these would speed up your process execution.

2. Main.xaml
   - Remember to use Log Message in your workflow. This helps to understand the process better, makes maintenance easier and aids in spotting the source when you encounter errors. 

Fix these and your code would hit the mark!

**Comment by vajrang-b** [comment]
SourceCode/2023/oct2023/Basics/Praveenraja S V/Task_9/project.json
### Comment posted for PR on file `NoFile` 

#### `Your organization requires your project to have an Automation Hub URL defined.`
Fix: Plug the blank by adding the required URL in the 'Project Settings'. It's a quick fix.

#### `Dependency package UiPath.UIAutomation.Activities is not used.`
Fix: Clear out the waste and remove unnecessary packages. This can help your process run a little faster.

### Comment posted for PR on file `Main.xaml`

#### `Log Message not used in workflow Main.`
Fix: Use `Log Message` in your workflow. It's your friend to trace what's happening in your code, finding issues will be simpler when they pop up.

#### `Variable First_Name does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$`
Fix: Keep a check on your variable names, make sure they follow the set pattern.

#### `Variable Second_Name does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$`
Fix: Keep a check on your variable names, make sure they follow the set pattern.

Performance Score:
* Code Completion: 1.5/2
* Execution: 1/

**Comment by krish952-creator** [comment]
@PRAVEENRAJA1699 
Task-6
Code verified.
Task-7
Code verified.
Task-8
Code verified.
Task-9
Code verified.

**Pull request merged**
