### PR TITLE
Task14,15,16,17,19

### PR DESCRIPTION
**Pull request by sharidas2210**
Task 19 MOdified.

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Sruthilaya/Task14/project.json
Score: 

- Code Completion: 1/2
- Execution: 1/2
- Annotations and Comments: 0/1

Review:

1. In overall project setup, the Automation Hub URL seems to be missing. Make sure to add this in the Project Settings. It's a company policy and project cannot proceed to production without it.

2. In 'Main.xaml', I noticed that the variables 'ExtractDataTable' and 'DtFilter' are not prefixed with 'dt_'. You should fix these variable naming inconsistencies. All DataTable variables should start with a 'dt_' prefix. This would greatly improve the readability and maintainability of the code. 

Code quality improvement is a continuous task. Thanks for your understanding. Keep coding.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Sruthilaya/Task15/project.json
1. NoFile:
- Issue: Your project lacks an Automation Hub URL. Your organization requires this.
- Solution: You can fix this easily. Go to 'Project Settings', and add the missing information there.

2. Main.xaml:
- Issue: The 'Do display name' is defined twice, but it should only be defined once. The current allowable limit is 1, not 2.
- Solution: Please rectify the names of your activities to reflect how they're used. Default names can be confusing because they're too vague. Also, remember not to use duplicate names.

- Issue: The variable 'Resultdt' is inappropriate because it doesn't have the DataTable prefix.
- Solution: Make sure that your DataTable Variable begins with a 'dt_' prefix. 

Scores:
- Code Completion: 1/2 (Missing Automation Hub URL, 'Do display name' repetitive, and 'Resultdt' missing DataTable prefix)
- Execution: 2/2 (No execution issues found)
- Annotations and Comments: 0/1 (No comments or annotations found) 

Please make these changes and resubmit your PR. 

Thank you.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Sruthilaya/Task16/project.json
Main.xaml: 
- Variable 'Empbuilddt' needs an update. DataTable Variables should start with 'dt_' prefix. So, change 'Empbuilddt' to 'dt_Empbuilddt'. 

NoFile: 
- Project lacks an Automation Hub URL. Go to "Project Settings" to add it.

Score: 
- Code completion: 1.5
- Execution: 1.5
- Annotations and Comments: 0.5

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Sruthilaya/Task17/project.json
File: Main.xaml

1. It's noticed there are 2 instances where the Log Message display name is defined, whereas per our standard practice it should be defined only once. Make sure activity names are unique, short, and meaningful. Use different names, so it's easy to identify activities immediately when we look at the workflow.

Score: Code Completion - 2

2. Next, the variable 'Employeedt' doesn't follow the DataTable prefix. As per the naming convention, DataTable variables should start with 'dt_'. So, change 'Employeedt' to 'dt_Employeedt'.

Score: Annotations and Comments - 1 

3. Also found a couple of Log Message activities that have a default name. It's a good practice to give your activities descriptive names. It helps to understand what the activity does without having to check the properties panel or the full code. So, consider renaming these activities to something more intuitive.

Score: Annotations and Comments - 0.5

Overall score: Execution - 2, Code Completion - 2, Annotations and Comments - 1.5

File: Not specified

Your organization requires your project to have an Automation Hub URL defined. If it's missing, you can add it using 'Project

**Comment by krish952-creator** [comment]
@sharidas2210 
Task -14
Code verified.
Task -15
Code verified.
Task -16
Code verified
Task -17
Code verified. Default activity names
 
image

Task -19
Code verified.

**Pull request merged**
