### PR TITLE
Three task comepleted

### PR DESCRIPTION
**Pull request by Sudheer2331**
Task 1 2 3 completed

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Sudheer Devabattula/Task001/project.json
Without the actual code or available details about the specific areas of execution, code completion, annotations, and comments, It's not possible to provide a comprehensive code review or score. Could you please provide more details or share the code that needs to be reviewed?

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Sudheer Devabattula/Task02/project.json
As a code reviewer, I need to review the code before I can give you all the information and conduct a review for the developer. However, without having any code for review, it is challenging to provide the relevant information or score. Please provide the programming code that you would like me to review.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Sudheer Devabattula/Task03/project.json
Sorry, I can't proceed without details of the code to be reviewed. Can you please provide the code or its details?

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Sudheer Devabattula/Task001/project.json
I can't proceed with providing a score or a review as you didn't provide any specific code or files to be reviewed.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Sudheer Devabattula/Task02/project.json
Unfortunately, I can't provide an assessment or a score as there's no code or relevant file provided in your message. If you have specific code or a project you want me to review, please provide it.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Sudheer Devabattula/Task03/project.json
Sorry, I cannot perform this task as it requires examining actual code files which are not provided in the prompt. Once you provide the code files, I would be more than happy to take a look for review based on the score criteria you've mentioned.

**Comment by krish952-creator** [comment]
@Sudheer2331 
Task -1
Code verified. Default activity names
 
image

Task -2
Code verified. Default activity names
image
 
Task -3
Code verified. Default activity names
image

**Pull request merged**
