### PR TITLE
Task 15

### PR DESCRIPTION
**Pull request by Khantil12**
Concatenate the name from the excel and writing full name

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 15/project.json
Your code completion score is 2 out of 2: Good work completing your code and offering a fully-functional solution.

Your execution score is 1.5 out of 2: Your code seems to work effectively for its purpose, but there are issues related to unused dependencies, which could impact execution time and overall performance. 

Your annotations and comments score is 0.5 out of 1: There seems to be a lack of logging activity in your workflow, which would help understand the flow path for future maintenance or in event errors occur. Moreover, WriteLine activity used should ideally be replaced by tracepoints during debug. 

Suggested improvements based on file review:

**NoFile:**
1. Please define an Automation Hub URL in your 'Project Settings'. This is required by your organisation.
2. Try to remove unused packages like UiPath.Mail.Activities, UiPath.MicrosoftOffice365.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities. Eliminating these will improve your process execution time.

**Main.xaml:**
1. Incorporate 'Log Message' activities in your workflow, particularly in 'Main'. It will aid in maintenance and will help identify errors, if they happen. 
2. 'WriteLine' activity at 'Full name

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 15/project.json
#### NoFile

1. Your project lacks an Automation Hub URL, as required by your organisation. Add this missing information via 'Project Settings'.
2. Several dependency packages (UiPath.Mail.Activities, UiPath.MicrosoftOffice365.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities) aren't being used in your code. Get rid of these to boost your process execution time.

#### Main.xaml

1. In your Main workflow, you haven't used the Log Message. Log Message activities are crucial – they make understanding the flow path easier during both the development stage and after the project has been launched. This also assists in quickly pinpointing any errors.
2. WriteLine activity has been noted at Full name output. If you're debugging, consider replacing these with tracepoints. If WriteLine is essential for debugging, you may want to swap it to Log Message. Remember to remove WriteLines before publishing.
3. Your variable 'Output1' doesn't have the DataTable prefix. Adding a dt_ prefix could be useful.

#### Score

1. Code Completion: 1.5/2
2. Execution: 1.5/2
3. Annotations and comments: 0.5/1

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 16/project.json
Github PR Comments:

POST to: `<GithubPR>/path_to_pr_1`
Comment:
"Relative to NoFile:
Firstly, add an Automation Hub URL for your project via 'Project Settings'. 
Also, I noticed you have a few dependency packages (UiPath.Mail.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities) that don't seem to be utilized. Get rid of these to speed up processing. 
Scores: Completion - 1.5, Execution - 2, Annotation - 0.5"

POST to: `<GithubPR>/path_to_pr_1`
Comment:
"Relative to Main.xaml:
Enhance your workflow by employing Log Message activities. These assist in unraveling the flow path, a handy tool for troubleshooting. 
Remember also: DataTable Variables ought to start with 'dt_'. 

Revise your variables to follow the preset naming pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$.

Lastly, updating your 'Output Data Table' activity title might make its purpose clearer.
Scores: Completion - 1.5, Execution - 1.5, Annotation - 0.5"

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 16/project.json
Scores:
Code Completion: 2
Execution: 1.5
Annotations and Comments: 1

Comments:

NoFile:
1. You need to add your Automation Hub URL in the "Project Settings". Your organization requires it for their info record.
2. You have some packages like UiPath.Mail.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities which are not being used. By getting rid of them, the execution time will get better.

Main.xaml:
1. There's a lack of usage of 'Log Message' activities in your Main workflow. These are helpful in understanding the project flow during both development and after release.
2. Variable naming is off. Variables like 'Output' that hold DataTable should start with 'dt_' as prefix.
3. Another variable 'Output_1' does not match the desired pattern "^(dt_)?([A-Z]|[a-z])+([0-9])*$". Please review your variable naming practices to ensure they are consistent and follow the proper pattern.
4. Just noticed an activity 'Output Data Table' that has a default name. It always helps if you replace the default name with something more descriptive.

Review these points and act accordingly to improve your code quality and execution time.

**Comment by krish952-creator** [comment]
@Khantil12 
Task-12
Task not available in this pr. check it
Task-14
Task not available in this pr. check it
Task -15
Code verified.
Task -16
Code verified.
Task -17
Code verified.

**Pull request merged**
