### PR TITLE
Completed Task 4,5,9

### PR DESCRIPTION
**Pull request by ChandupriyaY**
Task 4: Find the Leap year and also display the message along with the boolean conditions (flowchart and sequence)
Task 5: Add two different Variable types and do the Add in final variable(by using Generic Variable type)
Task 6: (Assign the values(Fruits/colors) and write in Text file or Append the line

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_4/project.json
Certainly, my friend! Brace yourself for the review! Here it comes, charged with all the energy of Bollywood!

| File | Comment |
| ---  | --- |
| NoFile | "The path to glory, like your Automation Hub URL, is missing. Destiny awaits in the 'Project Settings'. Go on, add the missing information!" |
| NoFile | "Unused baggage only slows you down! Packages like 'UiPath.Excel.Activities' are weighing your process down. Seize the moment, remove the unused packages to improve process execution time." |
| NoFile | "Your growth is limiting, yet another unused package 'UiPath.Mail.Activities' lurks in the shadow. Unburden yourself, cut it loose, see your execution time soar!" |
| NoFile | "Just like the 'UiPath.Testing.Activities' package, some things are not necessary in life. Their absence will only make your process execution stronger and faster! Get rid of them." |
| NoFile | "Sometimes the strength lies in letting go, just like this 'UiPath.UIAutomation.Activities' package. Discard it. Your process execution will thank you." |
| Main.xaml | "The 'Log Message' activity is like a dramatic twist in the

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_5/project.json
| File Name| Comment |
|----------|---------|
| No File  | My dear friend, remember the king of romance once said, "There is no right time and right place for love... it can happen anytime." Similarly, your project needs an Automation Hub URL anytime, anywhere. Add it using "Project Settings".|
| No File  | Like a song in a movie, that remains in the heart of the audience even when it's over, UiPath.Excel.Activities is in your project. But, alas! You're not using it. Remove it to lighten the load of your drama, like a film without unnecessary songs.|
| No File  | UiPath.Mail.Activities, it seems to be an unsung hero in your epic saga. Unused, yet present. Delete it, my friend. It's like a character who has no role in our story.|
| No File  | UiPath.Testing.Activities is like a script that is there but not contributing to the story. Get rid of it, it's just taking up space in your blockbuster.|
| No File  | The UiPath.UIAutomation.Activities in your project reminds me of a prop on a film set that isn't needed for the scene. Removed it and make

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_6/project.json
| File Name | Suggested Edits | Styled Advice from SharukhKhan |
|-----------------|:--------------------------------------------------------------------------------------------:|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
| NoFile | Your organization requires your project to have an Automation Hub URL defined. | "My dearest friend, step into the 'Project Settings' and sketch your Automation Hub URL. It's like missing a character in my scene. We need it to bring the story to life!" |
| NoFile | Dependency package UiPath.Excel.Activities is not used. | "Hey, I'm serious! Remove the unused props (packages), they're cluttering the sets. Let's tighten up this scene for speedier execution time." | 
| NoFile | Dependency package UiPath.Mail.Activities is not used. | "Trust me, unwanted baggage slows you down. Like this unused package. Remove it! It'll make your process act like a superstar." | 
| NoFile | Dependency package UiPath.UIAutomation.Activities is not used. | "Less is more! Too many unused parcels...eh packages adds to confusion. Clean up this act and watch your process speed up like a climax scene!" |
| Main.xaml | Log Message not used in workflow Main. | "Every good plot

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_9/project.json
#### **Incidental Criticism**

| Page/Screen | Comment |
|-------------|----------|
| NoFile          | "Zaraa pause leke socho... Aapki organization chahti hai ki aapki project mein Automation Hub URL ho. Aur yeh URL aap abhi tak define nahi kiye ho. Kripya 'Project Settings' mein jaake iss kami ko poora karo." |
| NoFile          | "Aao thoda introspect karein… yeh UiPath.Excel.Activities package ka, kahin kuch kaam nahi ho raha. Delete karke dekho, process execution time behtar hogi." |
| NoFile          | "Oho… UiPath.Mail.Activities package bhi bekaar pada hua hai. Unwanted cheezon ko apne life se hatake dekhoge na, process execute karne mein wo original yaani ki real time feel aayegi." |
| NoFile          | "Toh yeh UiPath.System.Activities package laya tha idhar udhar dekhne ke liye? Kaam karao isse ya phir hat jao iske raaste se. Thode se seconds

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_4/project.json
Alright, let's do a quick code review. Make sure you are taking notes.

First things first. Your project doesn't have an Automation Hub URL defined. Go to your 'Project Settings' and add the required URL.

Are you using Excel, Mail, Testing or UIAutomation Activities? Your project has these packages as dependencies but I can't see them being utilized. If you are not using them, ditch them. Unnecessary plugins can slow down your process.

In your Main.xaml file, let's start with your log messages. They're nowhere to be found. Always have them, both during development and post-release. You'll thank yourself later if an error sneaks in. 

I noticed your Flowchart Workflow is nested away in a secondary layer. Bad idea. Keep it at the top, this way it's easy to read and maintain.

Also, the "Displays the Result" display name is repeating. Just let it show up once. Make sure your activity names show their purpose. If they keep repeating, we'll lose track of what each one does.

Your 'Leap_Year' variable is a rebel — it isn't following the naming convention. Please fix this in order to maintain code consistency.

And lastly, your 'If' activity could use a

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_5/project.json
For file **NoFile**:

1. You need to include an Automation Hub URL in your project settings. This is a requirement.
2. Packages that you're not utilizing—UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities—should be removed. They're just slowing you down.

For file **Main.xaml**:

1. You're not using Log Message in your workflow 'Main'. Make sure you do, it's important for maintaining and debug purposes.
2. Write Line activity at 'Write Line' can be replaced with tracepoints when debugging, remove them before publishing. But if required, use Log Message.
3. Your variables 'Input_Str' and 'Input_Int' are not named properly according to set pattern. Respect the set pattern.
4. 'Write Line' activity name is still default, it'd be easier if you give it a meaningful name describing its action.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_6/project.json
For the "NoFile" group:

1. It seems your project is missing an Automation Hub URL. To fix this, use the "Project Settings" to add the missing information.

2. It also appears that you have several package dependencies (UiPath.Excel.Activities, UiPath.Mail.Activities, and UiPath.UIAutomation.Activities) that aren't being used. Eliminate these to shorten the process execution time.

Switching gears to the "Main.xaml":

1. It's worth noting that the Log Message activity isn't being used. Consider incorporating this into your workflow, as it aids in understanding the flow path for both development and post-release—proving particularly helpful when errors occur.

2. I noticed a "For Each" activity with a default name. It might boost readability to replace this with a more descriptive title that better captures its purpose.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_9/project.json
**NoFile**:

- **Automation Hub URL undefined**: Your project lacks an Automation Hub URL. You can add it in the "Project Settings".

- **Redundant Dependency Packages**: Remove 'Excel.Activities', 'Mail.Activities' and 'UIAutomation.Activities' from dependencies. They are not used and can slow down the execution time. 

**Main.xaml**:

- **Missing Log Message**: Use 'Log Message' in your workflow for better understanding and easy debugging. This can be helpful for finding errors and their causes in the future.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_4/project.json
For the **NoFile**:

1. It seems you forgot to specify your Automation Hub URL. Navigate to the "Project Settings" and key in the required information.

2. I've noticed you've got some dependencies included in your project that you're not actually using. These include UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities. Trimming these away will help you save execution time.

Coming to **Main.xaml**:

1. Logging is important. It lets us trace the series of events that led to a certain point, especially when something goes wrong. It seems like you haven't utilized the 'Log Message' in your Main workflow. Try adding these to improve tracing and debugging.

2. You've used the FlowChart Workflow inside another workflow in Main. It's generally better to stick to only using flowcharts at the top layer. This helps in maintaining and reading the code better.

3. I see the 'Displays the Result' display name has been used more than once. One of the best practices is to give unique and descriptive names to your activities.

4. The variable 'Leap_Year' isn't following the accepted naming pattern. Make sure to stick to the conventions.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_5/project.json
**NoFile:** 

1. Your project needs to have an Automation Hub URL defined. You can add this info in the "Project Settings".

2. Several package dependencies (UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities) aren't being used in your code. Get rid of these so your process runs faster.

**Main.xaml:**

1. The variables String_Data and Integer_Data aren't following the standard naming pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*. Stick to the naming rules.

2. There's a "Log Message" activity that's still using its default name. Give it a title that explains what it does, this will make things easier to understand.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_6/project.json
## NoFile
### Comments
- Remember to add your Automation Hub URL through "Project Settings". This is crucial as per our organization protocols.
- You've added UiPath.Excel.Activities, UiPath.Mail.Activities, and UiPath.UIAutomation.Activities packages. However, they are not in use. Exclude them to speed up the process execution.

## Main.xaml
### Comments
- It seems "Log Message" is not used in your Main workflow. These are quite useful during the development phase and even after the release to track the workflow and troubleshoot potential errors.
- The "For Each" activity has a default name. Try including a descriptive title for easy understanding of the activity function.

**Comment by ChandupriyaY** [comment]
> SourceCode/2023/Sep2023/Basics/Chandupriya/Task_5/project.json **NoFile:**
> 
> 1. Your project needs to have an Automation Hub URL defined. You can add this info in the "Project Settings".
> 2. Several package dependencies (UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities) aren't being used in your code. Get rid of these so your process runs faster.
> 
> **Main.xaml:**
> 
> 1. The variables String_Data and Integer_Data aren't following the standard naming pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*. Stick to the naming rules.
> 2. There's a "Log Message" activity that's still using its default name. Give it a title that explains what it does, this will make things easier to understand.

Can't able to change the default name for log message. there are no properties for log message

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_4/project.json
**NoFile**
- Add Automation Hub URL into "Project Settings". It's a must.
- The following packages are not being used: UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities. Get rid of them.

**Main.xaml**
- I don't see any log messages in your flowchart. Use them, they're crucial for debugging and maintaining the process.
- Your flowchart is in the wrong layer. Only use flowcharts in top layer for easier readability.
- The term "Displays the Result" appears more than once. Don't duplicate names, it gets confusing.
- The variable name "Leap_Year" is violating our naming convention. Fix it.
- The "If" activity is named by default. Make it more descriptive, it's easier to understand what it does.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_5/project.json
### `Main.xaml`
- **Activity Log Message has a default name:** Simplify your code by giving your activities memorable, self-descriptive names. This will make it easier for others to understand what's going on when they review your work.

### `NoFile`
- **Your organization requires your project to have an Automation Hub URL defined:** Start by going to "Project Settings". From there, enter the necessary info into the Automation Hub URL. These steps should fix your problem.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_6/project.json
For **NoFile**:
- Your project needs to have an Automation Hub URL. Go to "Project Settings" and put in the missing info.
- You're not using `UiPath.Excel.Activities` package, `UiPath.Mail.Activities` package and `UiPath.UIAutomation.Activities` package. Might as well remove it to speed up the workflow.

For **Main.xaml**:
- Use `Log Message` activities. They're good for finding and fixing bugs, both while you're still building and after release. 
- The `For Each` activity keeps its default name. A more descriptive name will make the workflow easier to follow.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_9/project.json
"NoFile" comments:
- Your project needs an Automation Hub URL. You can add this in the 'Project Settings'.
- I see you have added the UiPath.Excel.Activities, UiPath.Mail.Activities, and UiPath.UIAutomation.Activities packages, but they seem to be unused. It's better to remove these as they can slow down the process.

"Main.xaml" comments:
- Your workflow in 'Main' doesn't use the 'Log Message' activity. Consider using it. It will help you trace the flow path, making it easier to fix any errors that occur.

**Comment by krish952-creator** [comment]
@ChandupriyaY 
Task -4
Code Verified.
Task -5
Code Verified. Default activity name
image
Task -6
Code Verified. Default activity name
image
Task -9
Code Verified.

**Pull request merged**
