### PR TITLE
Task 1,2,3 

### PR DESCRIPTION
**Pull request by Nazeernrb**

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nazeer/Task1/project.json
{
    "NoFile":  [
                    {
                        "Feedback": "You haven't set up an Automation Hub URL. Go to 'Project Settings', you'll find where to add it there."
                    },
                    {
                        "Feedback": "Looks like you're not using UiPath.Excel.Activities package. Alright, let's remove it. It'll help your bot run faster."
                    },
                    {
                        "Feedback": "Seems like UiPath.Mail.Activities package is collecting dust here. Sweep it away, every bit helps to improve speed."
                    },
                    {
                        "Feedback": "UiPath.Testing.Activities package is not being touched. Get it off the shelf and your bot will be zippier."
                    },
                    {
                        "Feedback": "Haven't spotted you using UiPath.UIAutomation.Activities package. Let's do away with it for a quicker run."
                    }
               ],
    "Main.xaml":  [
                      {
                          "Feedback": "You're not logging enough. It's good to shout out progress or issues via Log Message. It'll be handy when something goes south."
                      },
                      {
                          "Feedback": "Input Dialog could use a better name. I bet you can come up with something descriptive."
                      },

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nazeer/Task2/project.json
```
# NoFile Review

## Dependency Packages
The code has several dependency packages (UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities) that are not used. Kindly remove them to help improve process execution time

## Project Requirements
Your project doesn't have an Automation Hub URL defined, which is a requirement in your organization. Please go to "Project Settings" and add the missing information.

# Main.xaml Review

## Activity Names
There seems to be multiple instances of "Input Dialog" and "Log Message" with the same display names. Activity names should be clear and distinct to avoid ambiguity. Please avoid using duplicate names.

Further more, there are several activities with default names. It's highly recommended to provide a unique, descriptive name for each activity. It makes it easier to understand the purpose of the activity. Update the names for these activities accordingly.

# Scoring

Code Completion: 2   
Execution: 2   
Annotations and Comments: 1   
```

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nazeer/Task3/project.json
Score criteria:

Code Completion: 2/2 - Good job, you have completed tasks from your assigned coding work.
Execution: 1/2 - Your code executed correctly, but there are unused packages which could hamper process execution time.
Annotations & Comments: 0/1 - Your activities have default names. Make them descriptive to give a clear understanding of what they do.

Total Score: 3/5

Attached are the reviews based on your files:

**NoFile:**

1. Looks like your project doesn't have an Automation Hub URL defined. Just go to the "Project Settings" and paste the URL there.
   
2. I noticed that you included the UiPath.Excel.Activities, UiPath.Mail.Activities, and UiPath.UIAutomation.Activities packages, but you didn't use any of them. It's a good idea to remove all unused packages, as this will make your process run faster.

**Main.xaml: **

1. Your "Assign", "Write Text File", and "Log Message" activities have default names. Help yourself and others understand your workflow better by assigning descriptive names to your activities. For example, instead of "Assign", you could use "Assign_VariableName_ToValue".

Make these modifications and your score would improve

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nazeer/Task4/project.json
Here are the scores for code completion, Execution, and annotations and comments respectively: 1.5, 1.9, 0.6.

Feedback for NoFile:

1. Define an Automation Hub URL in your project settings.
2. Non-utilized packages such as UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities need to be removed, in the interest of enhancing process execution duration.

Feedback for Main.xaml lines of code:

1. Activities like 'Assign' and 'Message Box' have multiple instances with same names. Activities names must be more descriptive and unique.
2. Variables such as 'intYear_Input' and 'Boolean_Value' do not comply with the allowed naming pattern. Kindly adjust them to adhere to standard naming conventions.
3. Activities such as 'Log Message', 'Input Dialog', 'If', 'Assign', and 'Message Box' all bear default names. It's essential that they're given more descriptive titles aiding comprehension of their functionality. 

Kindly take these pointers into consideration when revising your code. This will help in enhancing its structure, readability, and efficiency.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nazeer/Task5/project.json
Code Review Comment:

> For file: Flowchart.xaml

1. No use of Log Message in the workflow. This is important for understanding the flow path, especially during maintenance and error tracking. Please add them as needed.
2. Replace WriteLine activities with tracepoints, if used for debugging purpose only. Remove those before final publishing. 
3. 'Assign' display name is found 3 times in your code. Avoid duplicate names, one is the expected limit.
4. Some activities are found with their default names. Please give a clear and descriptive name to each activity to understand their purpose better.

> For file: NoFile

1. Your project is missing an Automation Hub URL. Define it in the Project Settings.
2. Identified some unused packages (UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities). Please remove the unused packages to optimize the process execution.

> For file: Main.xaml

1. No use of Log Message. They help in maintaining the workflow and tracking the error source, consider using them.

Review Scores:
- Code Completion: 1.5. Please address the above points for better code completion.
- Execution: 1.5. Removing unused resources and improving

**Comment by krish952-creator** [comment]
@Nazeernrb 
Task -1
Code verified. Default activity names
 
image

Task -2
Code verified. Default activity names and check the addtion method
 
image

Task -3
Code verified. Default activity names
 
image

Task -4
Code verified. Default activity names
 
image

Task -5
Code verified. Default activity names
image

**Pull request merged**
