### PR TITLE
Task1 , Task 2

### PR DESCRIPTION
**Pull request by ChiragJindal1231998**

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Chirag/Task 5/project.json
## NoFile

---

**Score:**

- Code Completion: 1
- Execution: 1
- Annotations and comments: 0.5

**Review:**

- Automation Hub URL is missing. Please add this from the 'Project Settings'.
- You've included packages UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities, but they're not used. Remove them to boost your code execution.

---

## Main.xaml

---

**Score:**

- Code Completion: 1.5
- Execution: 1.5
- Annotations and comments: 0.5

**Review:**

- Found Flowchart used in a secondary layer, this should be used only in top layer for better readability.
- 'Assign' display name appears more than once, having 3 occurrences. Avoid duplicate names to make your activity clear.
- Your activities Assign, Flowchart, Message Box, Log Message all have default names. Consider changing these to contain more specific details about the tasks and improve readability.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Chirag/Task1/project.json
Score: 5

Review for "NoFile":
- Please include an Automation Hub URL for this project. You can find this under "Project Settings".
- I noticed there are several dependency packages (UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities) not being used in your project. Removing them could speed up your process.

Review for "Main.xaml":
- Try to use "Log Message" more often. It's useful for following the flow path, and especially for identifying source of errors.
- The "Input Dialog" and "Message Box" activities still have their default names. Try to give them names that better explain what they do.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Chirag/Task2/project.json
Score: 

Code Completion: 2

Execution: 2

Annotations and Comments: 0 

Hey there, 

Great job on your code, It runs fine and is complete. However, there are some tweaks needed to meet the best practices, let me walk you through them one by one -

1. First things first, your project must have an Automation Hub URL defined. Here's how to do it: Simply go to \"Project Settings\" and add the missing information.

2. Always good to keep our code clean, Right? There are a few dependency packages (UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities) not used in your code, let's just remove them to speed the process execution. 

3. You have used duplicate names for activities (both 'Input Dialog' and 'Log Message') multiple times. Avoid doing this. Every activity should be named clearly and distinctly, it should tell us what it is about - helps a lot when doing any code modifications in future. 

4. Also, there are some activities with default names ('Input Dialog' and 'Log Message'). How about making them more descriptive to understand their role better? 

Implement these and we're good

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Chirag/Task3/project.json
Overall, your code seems to be functioning correctly. Execution seems alright, so your score for execution is a solid 2.

However, there are a few areas that need improvement:

1. It seems that you have included several packages (UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.UIAutomation.Activities) that are not used in your project. These unutilized dependencies just bulk up your code and can slow down execution. Make sure to only include packages that you actually need. I suggest cleaning up your dependencies.

2. The UiPath project doesn't have an Automation Hub URL linked. This is not good practice as having a URL makes it much easier to access, share, and manage the project. Please go to Project Settings and add the necessary URL.

3. Most activities are using default names. In order to make your code more readable, give each activity a descriptive name that describes its purpose. This is especially important for Write Text File activities, as you have 10 occurrences with the default name. Also, Assign activity needs a clearer name.

4. There is a lack of Log Message activities. These are important for understanding the flow of your program, especially during debugging. Add more log messages wherever they are needed.

In terms of annotation and

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Chirag/Task4/project.json
### NoFile

- Your project lacks a defined Automation Hub URL, which is a requirement for your organization. Head over to "Project Settings" and add the necessary information.

- There are dependency packages (UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities) in your project that are not used. It's always a good idea to remove unused packages – it can significantly improve your process execution time.

### Main.xaml

- You've defined 'Log Message' & 'Message Box' display names multiple times - exceeding the allowed threshold is 1. Remember, unique names for each activity allow for better understanding of how it functions. So, avoid duplicate names.

- Two of your variables, 'year_input' & 'Boolean_Variable', do not respect the naming pattern. Always use consistent naming patterns for variables – it aids in readability.

- Several activities ('Input Dialog', 'Log Message', 'If', 'Assign', 'Message Box') have been left with their default names. It's best if you give them more descriptive names to make your code readable, understandable, and maintainable.

**Score**: Code completion - 2, Execution - 2, Annotations and comments - 1.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Chirag/Task 5/project.json
Score:

- Code Completion: 1.5 
- Execution: 1.5 
- Annotations and Comments: 0.5

## Main.xaml

- Flowchart should not be used in a secondary layer in Main for clarity and maintenance purposes. Please fix this. 

- 'Assign' activity is used with default names. I can see this happening 3 times. Please fix the names to be more unique and explanatory.

- I see Message Box and Log Message activities with default names. These default names are too generic and do not give a clear idea of their functionality. Please rename them with more descriptive titles.

- Similarly, the Flowchart activity needs a specific name describing its role in the automation. Please add a more descriptive title.

## NoFile

- It seems there are some packages (UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities) declared, but not being used. That can make the process run slower than necessary. Please remove these unused dependencies.

- Your project does not have a defined Automation Hub URL, which seems to be required by the organization. You can add this information in the 'Project Settings'.

In general, improving these aspects enhances the project's readability and

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Chirag/Task1/project.json
Code Review Comments:

For the 'NoFile' category:
1. Add the Automation Hub URL in your project settings. It's straightforward. Go to 'Project Settings' and put the URL there.
2. You've added extra packages like UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities. But, you're not using them. Always keep your code lean. Remove these packages if they're not needed for this project.

For 'Main.xaml':
1. I see you're not using Log Message anywhere. Remember, it's highly useful for any project. It helps in understanding the flow path, makes maintenance easier, and is a key tool for trouble-shooting. Add the Log Message where it's required.
2. The Input Dialog and Message Box activities need to have meaningful names. It'll make your code easier to understand. So, add a more descriptive title to these activities.

Scores:
1. Code Completion: 1.5/2 (Work on your code organization)
2. Execution: 1.5/2 (Include Log Message for better execution)
3. Annotations and Comments: 0.5/1 (Need descriptive names for activities)

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Chirag/Task2/project.json
Based on the details provided, here's a simplified review of the code.

For the "NoFile" section,
- You need to add the Automation Hub URL to your project settings. This is a requirement by your organization. It's quick to fix this, just jump to the project settings and fill it in.
- You've included some packages in your project but they aren't actually used anywhere (that is UiPath.Excel.Activities, UiPath. Mail.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities). These extra packages don't do you any good, they just weigh your process down and make it slower. Get rid of them.

On the "Main.xaml" section,
- Your usage of names could do with some improvement. For instance, you have used 'Input Dialog' and 'Log Message' multiple times. Keeping unique and meaningful names makes it easy for you (and others) to understand what each part of the code is doing. Fix that up.
- Also, you've left some activities with the default name (for example, Input Dialog, Log Message). Customize these names so they give us a hint of what the activity does. 

Scores would be:
- Code completion: 1.5 (Due to missing Automation

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Chirag/Task3/project.json
Here's a simple overview:

NoFile:
1. Your project is missing an Automation Hub URL. Go into "Project Settings" and fill it in.
2. You have some packages that you aren't using. Get rid of UiPath.Excel.Activities, UiPath.Mail.Activities and UiPath.UIAutomation.Activities to help your process run faster.

Main.xaml:
1. You're not using any Log Messages, these can be really handy for tracking what went wrong when something breaks. Try using them.
2. You're using the same name for the Write Text File activity way too much. Activities need specific names so it's clear what they are doing. You've used the same name 10 times, but you should only use it once.
3. A majority of your activities have default names. Take a moment to give them a name that reflects what they're doing so it's easier to follow along.

Score:
- Code Completion: 2/2
- Execution: 1/2 (due to the lack of log messages, the execution is unclear)
- Annotations and Comments: 0/1 (due to poor naming of activities which undermines readability) 

Review and make these changes to improve your score. Happy coding!

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Chirag/Task4/project.json
**Score:**

- Code Completion: 2/2
- Execution: 1/2
- Annotations and Comments: 0/1

**Review:**

For the file with no name, it is missing an Automation Hub URL, which your project needs. You can add the URL in "Project Settings". Also, there are five packages linked to your project that are not being used (UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities). You should remove these to make the process faster.

For the file named "Main.xaml", change the names of your activities for "Log Message" and "Message Box" to something more specific. Right now, they have been used more than just once and it's confusing. Also, your variables "year_input" and "Boolean_Variable" need to follow the given naming style. Here is how your variables should look like: ^(dt_)?([A-Z]|[a-z])+([0-9])$.

The activities "Input Dialog", "Log Message", "If", "Assign", "Message Box" don't have good names. Just try to give them names that make sense based on what they do. For example, instead of

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Chirag/Task6/project.json
Code Completion: 1.5/2 - Some items need attention like linking your project to Automation Hub URL and removing unused dependency packages.

Execution: 2/2 - No issue with the code execution has been detected.

Annotations and Comments: 0.5/1 - Activities in the workflow Main have default names. To improve code understanding, use descriptive names that represent the activity function.

Overall Score: 4/5 - Your PR has been partially successful. However, improvements before the final submission would be recommended.

Solutions:

1. Link project to Automation Hub URL - Go to "Project Setting", there you should find a place to add your URL.

2. Unused Packages - You have imported some packages which are not used in your program (`UiPath.Excel.Activities`, `UiPath.Mail.Activities`, and `UiPath.UIAutomation.Activities`). You need to remove those.

3. Descriptive names for activities - Giving meaningful, descriptive labels or names to your activities like `for each`, `Assign`, and `Append line` would make your code cleaner and easier to understand.

4. Log Message not used - It's recommended to use Log Message activities during development and after the project has been deployed. They help you understand the flow path which is necessary

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Chirag/Task7/project.json
"NoFile":
- Automation Hub URL: Don't forget to include the Automation Hub URL in your Project Settings. Your organization requires this.

- Unused Packages: Pivot. Clear out UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities. You're not using these, but they bloat execution time. Trim the fat.

"Main.xaml":
- Log Messages: Speak up. There's zero Log Message use in 'Main'. These highlight your milestone during and post-development. Trust me, if an error crops up, you can trace back easier with these breadcrumbs.

- Generic Activity Names Lurking: Got a rogue Message Box name repeating 5 times. Cool it on the multiples. Activity names should be clear & unique. Don't risk the confusion.

- Default Names: You've got a lot of 'Message Box' and 'Assign' activities hiding behind their default names. A quick rename could save you head scratches in the future. Be more descriptive, less generic.

Score:
- Code Completion: 1.5/2 (Complete, but with unused packages & missing Automation Hub URL)
- Execution: 1/2 (Potential improvement with removal of unused packages)
- Annotations and Comments:

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Chirag/Task8/project.json
Score:

Code completion: 1.5
Execution: 2
Annotations and comments: 0.5

Feedback:

NoFile - Your project is missing an Automation Hub URL. It's much needed for your organization. To fix this, go to "Project Settings" and add the missing information. You also have several unused packages that just slow your process execution time. You want things quick and lean. So, get rid of UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities.

Main.xaml - It seems like you've forgotten to log messages in your Main workflow. These are important to keep things easy to track, maintain, and debug. Add those in. Also, you're repeating Message Box display name too many times—5 times when you're only allowed 1. Need to change these names and make them more descriptive. On the same note, your Assign activity and your Message Box activities need improved names. Get more creative and descriptive for clarity. Work on these and you're good to go. 

Remember, the key here is clarity and efficiency. Strive for that and you're gold.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Chirag/Task9/project.json
Based on the code review:

Overall Score: 
- Code Completion: 1.5/2
- Execution: 1.5/2
- Annotations and Comments: 0.5/1 

Details: 

NoFile: few package dependencies are not used in your project (UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.UIAutomation.Activities). These unused packages can slow down your process, remove them to make it faster. Also, add an Automation Hub URL to your project in the 'Project Settings'.

Main.xaml: Remember to use 'Log Message' in your workflow, it helps us understand the flow better, especially when we need to fix an error. I noticed you repeated the name 'Input Dialog' and 'Assign' in your activities. Give them unique names that describe their purpose. Also, several activities have default names. It's good practice to rename them to something more descriptive. Helps us understand what the activity does.

Remember to fix these points in your next commit.

**Comment by krish952-creator** [comment]
@ChiragJindal1231998 
Task -1
Code verified. Default activity names
 
image

Task -2
Code verified. Default activity names
 
image

Task -3
Code verified. Default activity names
 
image

Task -4
Code verified. Default activity names
image

 
Task -5
Code verified. Default activity names
 
image

Task -6
Code verified. Default activity names
 
image

Task -7
Code verified. Default activity names
 
image

Task -8
Code verified. Default activity names
 
image

Task -9
Code verified. Default activity names
 
image

**Pull request merged**
