### PR TITLE
Task 28

### PR DESCRIPTION
**Pull request by Supriyar6040**
Used all PDF activites and stored results into a text file.

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Supriya/Task28/project.json
**Main.xaml**
- The `Tesseract OCR` activity has a default name. Could you consider renaming it to something more descriptive?
- The same applies to the `Activity Log Message`. Adding a clear and concise name would make the code easier to understand.

**Score: 4/5**

Please provide more information about the purpose of these activities, so I can give a more accurate review.

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Supriya/Task27/project.json
**Subtraction.xaml**
* Log Message not used in workflow Subtraction: It's important to add log messages during development and after release as they help understanding the flow path which is very useful for maintenance and when an error occurs.
* Activity Assign has a default name: Consider adding a more descriptive title to make it easier to understand what the activity does.

**Main.xaml**
* WriteLine activity usage at Write Line to display Addresult: Replace with tracepoints during debug. Remove before publishing. You can also consider changing WriteLine to Log Message if needed for debugging purposes.
* WriteLine activity usage at Write Line to Sub Result: Same as above, replace with tracepoints and remove before publishing.

**General**
* Dependency packages UiPath.Mail.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities are not used: Remove unused packages to improve process execution time.

**Variable and Argument Names**
* Argument Num1 does not respect the set pattern ^in_(dt_)?(A-Z|a-z)+(0-9)*$: Make sure all arguments follow the naming convention.
* Variable Num1 has the same name as an existing argument: Define unique names for variables and arguments.

**File Naming Convention**
* Activity For Each Row in Data Table has a default name: Add a more descriptive title to make it easier to understand what the activity does.
* Activity Log Message has a default name: Same as above, add a more descriptive title.

**Score: 5/5**

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Supriya/Task28/project.json
@main
* Add more descriptive titles for activities to improve readability. For example, you can rename `Activity Tesseract OCR` to something like `Recognize Text with Tesseract OCR`.

@dataAccess
No issues found.

@excel
* Remove unused dependencies (UiPath.Excel.Activities) to improve process execution time.

@mail
* Remove unused dependencies (UiPath.Mail.Activities) to improve process execution time.

**Score: 4/5**

Please note that I ignored the "NoFile" issue as per your request, and only provided suggestions for improvement in a simple and easy-to-understand language.

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Supriya/Task27/project.json
**Main.xaml**
WriteLine activities are used for debugging purposes only and should be removed before publishing.
Consider changing them to Log Message activities if needed.

**Subtraction.xaml**
Log Message activities are not used in the workflow, which makes it harder to understand the flow path during development and after release. Add log messages to help with maintenance and error tracking.
Assign activity has a default name, make sure to add a more descriptive title.

**Addition.xaml**
The same issues as Subtraction.xaml apply here, use Log Message activities for better debugging and error tracking, and add a more descriptive title to the Assign activity.

**General comments**

* Unused packages (UiPath.Mail.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities) should be removed to improve process execution time.
* Variable names should be unique and follow the naming convention (^in_(dt_)?(A-Z|a-z)+(0-9)*$).
* Activity names can be more descriptive to make it easier to understand what they do.

**Score: 5/5**

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Supriya/Task28/project.json
**Main.xaml**
The `Activity Tesseract OCR` and `Activity Log Message` have default names. Consider renaming them with more descriptive titles to improve readability.

**Score: 5/5**

**No issues found in this file**

---

**Score: 4.5/5**

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Supriya/Task29/project.json
**Main.xaml**
- Sequence display names should be unique and descriptive. You have 3 duplicate names. Please rename them to something like "Sequence - Step 1", "Sequence - Step 2" etc.

**Kill Excel**
- Same issue as above, you have 2 duplicate sequence display names. Rename them to something meaningful.

**Read Input File**
- Same issue as above, you have 2 duplicate sequence display names. Rename them to something meaningful.

**Throw**
- This activity has a default name. Consider renaming it to something like "Throw Error" or "Raise Exception". It will be easier for others (or yourself) to understand the purpose of this activity.

**Log Message**
- You have multiple activities with default names. Please rename them to something descriptive, such as "Log Successful Execution", "Error Handling Log" etc.

Score: 5/5

**Comment by krish952-creator** [comment]
@Supriyar6040 
Task – 27
Code verified.
Task – 28
Code verified.
Task – 29
Code verified.

**Pull request merged**
