### PR TITLE
Task 7, Task 8, Task 9

### PR DESCRIPTION
**Pull request by rajendrayarlagaddausa333**

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Rajendra/Task7/project.json
**main.xaml**
WriteLine activity usage at Display item in a message box: Write Line activity can be replaced with tracepoints during debug. They should be removed before publishing. Consider also changing WriteLine to Log Message if it is really needed for debugging purposes.

**No suggestions provided**

Score: 5/5

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Rajendra/Task8/project.json
**Main.xaml**
Please use Log Message activities throughout your workflow, `Main`. This will help you understand the flow path and identify the source and cause of any errors during development and after release.

**Variable Array_list_names**
Please make sure this variable follows the set pattern `^(dt_)?(A-Z|a-z)+(0-9)*$|_out_[A-Za-z][A-Za-z0-9]*$. This is a naming convention for all variables in your project.

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Rajendra/Task9/project.json
**Main.xaml**
WriteLine activity usage at Write Line: Write Line activity can be replaced with tracepoints during debug. They should be removed before publishing. Consider also changing WriteLine to Log Message if it is really needed for debugging purposes.

**No issues found**

**Score: 5/5**

Please remove the unused Write Line activities and consider using Log Message activities instead for better debugging purposes.

**Comment by krish952-creator** [comment]
@rajendrayarlagaddausa333 
Task – 7
Code verified.
Task – 8
Code verified.
Task – 9
Code verified.

**Pull request merged**
