### PR TITLE
Task 12

### PR DESCRIPTION
**Pull request by RajashekharPuligilla**
Finding Min and Max Values from Array of Integer

### CODE REVIEW

**Comment by vajrang-b** [comment]
{
    "Main.xaml":  [
                      {
                          "The sequence Sequence is redundant.":  "Redundant sequences should not be used, since they only make the workflow cluttered. For removing redundant sequences, use the Remove Surrounding Sequence option of the Context Menu in UiPath Studio. "
                      },
                      {
                          "Do display name is defined many times. Current allowed threshold is 1. Code contains 2.":  "Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names. "
                      },
                      {
                          "Variable Result doesn\u0027t have DataTable prefix.":  "DataTable Variable should start with a dt_ prefix. "
                      },
                      {
                          "Variable Output doesn\u0027t have DataTable prefix.":  "DataTable Variable should start with a dt_ prefix. "
                      },
                      {
                          "Activity Comment Out has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ],
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   }
               ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "Variable ExtractDataTable doesn\u0027t have DataTable prefix.":  "DataTable Variable should start with a dt_ prefix. "
                      },
                      {
                          "Activity Use Application/Browser has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Variable Result doesn\u0027t have DataTable prefix.":  "DataTable Variable should start with a dt_ prefix. "
                      },
                      {
                          "Activity Extract Table Data has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Filter Data Table has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "WriteLine activity usage at Write Line.":  "Write Line activity can be replaced with tracepoints during debug. They should be removed before publishing. Consider also changing WriteLine to Log Message if it is really needed for debugging purposes. "
                      },
                      {
                          "Assign display name is defined many times. Current allowed threshold is 1. Code contains 2.":  "Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names. "
                      },
                      {
                          "Variable NameDetails doesn\u0027t have DataTable prefix.":  "DataTable Variable should start with a dt_ prefix. "
                      },
                      {
                          "Activity For Each Row in Data Table has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Assign has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Write Line has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Assign has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "Variable StnDetails doesn\u0027t have DataTable prefix.":  "DataTable Variable should start with a dt_ prefix. "
                      },
                      {
                          "Activity Output Data Table has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Build Data Table has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Variable PrsnDe doesn\u0027t have DataTable prefix.":  "DataTable Variable should start with a dt_ prefix. "
                      },
                      {
                          "Activity Assign has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Build Data Table has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Multiple Assign has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Add Data Row has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Output Data Table has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Log Message has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "Variable Std_Details does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$|_out_[A-Za-z][A-Za-z0-9_]*$":  "Make sure all the variables follow the naming convention. "
                      },
                      {
                          "Variable Dt_DataTable does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$|_out_[A-Za-z][A-Za-z0-9_]*$":  "Make sure all the variables follow the naming convention. "
                      },
                      {
                          "Variable Dt_DataTable doesn\u0027t have DataTable prefix.":  "DataTable Variable should start with a dt_ prefix. "
                      },
                      {
                          "Activity Generate Data Table From Text has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Read Text File has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   }
               ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "Variable ExtractDataTable doesn\u0027t have DataTable prefix.":  "DataTable Variable should start with a dt_ prefix. "
                      },
                      {
                          "Activity Use Application/Browser has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Variable Result doesn\u0027t have DataTable prefix.":  "DataTable Variable should start with a dt_ prefix. "
                      },
                      {
                          "Activity Extract Table Data has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Filter Data Table has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "WriteLine activity usage at Write Line.":  "Write Line activity can be replaced with tracepoints during debug. They should be removed before publishing. Consider also changing WriteLine to Log Message if it is really needed for debugging purposes. "
                      },
                      {
                          "Assign display name is defined many times. Current allowed threshold is 1. Code contains 2.":  "Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names. "
                      },
                      {
                          "Variable NameDetails doesn\u0027t have DataTable prefix.":  "DataTable Variable should start with a dt_ prefix. "
                      },
                      {
                          "Activity For Each Row in Data Table has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Assign has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Write Line has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Assign has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "Variable StnDetails doesn\u0027t have DataTable prefix.":  "DataTable Variable should start with a dt_ prefix. "
                      },
                      {
                          "Activity Output Data Table has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Build Data Table has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Variable PrsnDe doesn\u0027t have DataTable prefix.":  "DataTable Variable should start with a dt_ prefix. "
                      },
                      {
                          "Activity Build Data Table has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Assign has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Multiple Assign has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Add Data Row has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Output Data Table has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Log Message has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "Variable Dt_DataTable doesn\u0027t have DataTable prefix.":  "DataTable Variable should start with a dt_ prefix. "
                      },
                      {
                          "Variable Std_Details does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$|_out_[A-Za-z][A-Za-z0-9_]*$":  "Make sure all the variables follow the naming convention. "
                      },
                      {
                          "Variable Dt_DataTable does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$|_out_[A-Za-z][A-Za-z0-9_]*$":  "Make sure all the variables follow the naming convention. "
                      },
                      {
                          "Activity Generate Data Table From Text has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Read Text File has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   }
               ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "Variable ExtractDataTable doesn\u0027t have DataTable prefix.":  "DataTable Variable should start with a dt_ prefix. "
                      },
                      {
                          "Activity Use Application/Browser has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Variable Result doesn\u0027t have DataTable prefix.":  "DataTable Variable should start with a dt_ prefix. "
                      },
                      {
                          "Activity Extract Table Data has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Filter Data Table has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "WriteLine activity usage at Write Line.":  "Write Line activity can be replaced with tracepoints during debug. They should be removed before publishing. Consider also changing WriteLine to Log Message if it is really needed for debugging purposes. "
                      },
                      {
                          "Assign display name is defined many times. Current allowed threshold is 1. Code contains 2.":  "Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names. "
                      },
                      {
                          "Variable NameDetails doesn\u0027t have DataTable prefix.":  "DataTable Variable should start with a dt_ prefix. "
                      },
                      {
                          "Activity For Each Row in Data Table has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Assign has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Write Line has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Assign has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Variable PrsnDe doesn\u0027t have DataTable prefix.":  "DataTable Variable should start with a dt_ prefix. "
                      },
                      {
                          "Activity Build Data Table has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Assign has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Multiple Assign has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Add Data Row has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Output Data Table has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Log Message has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   }
               ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   }
               ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   }
               ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "Variable StnDetails doesn\u0027t have DataTable prefix.":  "DataTable Variable should start with a dt_ prefix. "
                      },
                      {
                          "Activity Build Data Table has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Output Data Table has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   }
               ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   }
               ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   }
               ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   }
               ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   }
               ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ]
}

**Comment by krish952-creator** [comment]
@RajashekharPuligilla 
Task -12
Code verified.
Task -13
Code verified.
Task -14
Code verified.
Task -15
Code verified.
Provide input file in necessary tasks.

**Pull request merged**
