### PR TITLE
Task_12

### PR DESCRIPTION
**Pull request by Pravin38**
Find the Max value from list of Array of Numbers.

### CODE REVIEW

**Comment by vajrang-b** [comment]
{
    "Sequence.xaml":  [
                          {
                              "Variable Min is not used.":  "Remove variables that are not used. "
                          },
                          {
                              "Assign display name is defined many times. Current allowed threshold is 1. Code contains 3.":  "Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names. "
                          },
                          {
                              "Variable int_NumList does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$|_out_[A-Za-z][A-Za-z0-9_]*$":  "Make sure all the variables follow the naming convention. "
                          },
                          {
                              "Activity Assign has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                          },
                          {
                              "Activity Assign has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                          },
                          {
                              "Activity For Each has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                          },
                          {
                              "Activity If has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                          },
                          {
                              "Activity Assign has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                          },
                          {
                              "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                          },
                          {
                              "Activity Log Message has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                          }
                      ],
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "File Main is empty.":  "Consider removing unused files. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "Sequence.xaml":  [
                          {
                              "Variable Min is not used.":  "Remove variables that are not used. "
                          },
                          {
                              "Assign display name is defined many times. Current allowed threshold is 1. Code contains 3.":  "Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names. "
                          },
                          {
                              "Variable int_NumList does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$|_out_[A-Za-z][A-Za-z0-9_]*$":  "Make sure all the variables follow the naming convention. "
                          },
                          {
                              "Activity Assign has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                          },
                          {
                              "Activity Assign has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                          },
                          {
                              "Activity For Each has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                          },
                          {
                              "Activity If has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                          },
                          {
                              "Activity Assign has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                          },
                          {
                              "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                          },
                          {
                              "Activity Log Message has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                          }
                      ],
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "File Main is empty.":  "Consider removing unused files. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "Sequence.xaml":  [
                          {
                              "Log Message display name is defined many times. Current allowed threshold is 1. Code contains 2.":  "Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names. "
                          },
                          {
                              "Read Range display name is defined many times. Current allowed threshold is 1. Code contains 2.":  "Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names. "
                          },
                          {
                              "Write Range display name is defined many times. Current allowed threshold is 1. Code contains 2.":  "Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names. "
                          },
                          {
                              "Activity Log Message has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                          },
                          {
                              "Activity Write Range has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                          },
                          {
                              "Activity Read Range has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                          },
                          {
                              "Activity Excel Application Scope has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                          },
                          {
                              "Activity Log Message has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                          }
                      ],
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "File Main is empty.":  "Consider removing unused files. "
                      }
                  ]
}

**Comment by krish952-creator** [comment]
@Pravin38 
Task -12
Code verified. Default activity name
image
 
Task -13
Code verified.
Provide Input file on necessary Tasks

**Pull request merged**
