### PR TITLE
TASK3 COMPLETED

### PR DESCRIPTION
**Pull request by PRAVEENRAJA1699**

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/oct2023/Basics/Praveenraja S V/Task_1/project.json
Hello Developer,

As per my understanding, here's a look at the points that need your attention:

* In regards to "NoFile":
   - The project is missing the Automation Hub URL. Kindly add this information through the "Project Settings".
   - Also, there are few packages that you've added as dependencies which are not being used, including UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities. Please clear unused packages as it'll make the process execution faster.

* For "Main.xaml":
   - I noticed that the "Log Message" is not being used. Including them is crucial both during the development phase and after the release. It makes it easy for us to understand the flow of the process, making maintenance easy. Moreover, when an error pops up, it'll help us to quickly identify the root cause. 

Scoring Criteria:

- Code Completion : 2/2 
- Execution: 1.5/2 
- Annotations and Comments: 0.5/1 

If you fix these issues, we can definitely increase the execution and comment scores. 

Happy coding! Let me know if you need more clarifications.

**Comment by vajrang-b** [comment]
SourceCode/2023/oct2023/Basics/Praveenraja S V/Task_2/project.json
# Code Review Score

**Code Completion: 1/2**  
Your code is incomplete due to undefined project Automation Hub URL and dependencies with unused packages. Please set them correctly.

**Execution: 1/2**  
The execution of your code will be affected due to unused packages, Potential improvements can be seen after their removal.

**Annotations and Comments: 0/1**  
The lack of unique and descriptive names for activities reduces the readability of your code. Consider adding more descriptive titles to practices. 

_Total Score: 2/5_

Consider the following changes:

## For No File
1. Add the Automation Hub URL in your Project Settings.
2. Remove the dependency packages UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities as they are not in use. Unused packages can slow down process execution time.

## For Main.xaml
1. Avoid using the same name for different activities. This is observed in Input Dialog and Log Message which are defined 2 and 5 times respectively.
2. Make sure to add a unique and descriptive display name to all your activities. This will increase the readability and maintainability of your code. This is applied mostly to your Log Message and

**Comment by vajrang-b** [comment]
SourceCode/2023/oct2023/Basics/Praveenraja S V/Task_3/project.json
As a code reviewer, here are my findings and steps you can take to improve code:

1. Your project lacks an Automation Hub URL. This is a need within our company. Go to 'Project Settings' and provide the necessary details.

2. There are unused packages in your code such as UiPath.Excel.Activities, UiPath.Mail.Activities, and UiPath.UIAutomation.Activities. Unnecessary packages can slow down the execution time. Please erase them.

Scores:
- Code Completion: 1.5 - Some parts of the code seem to be incomplete due to missing necessary information like Automation Hub URL.
- Execution: 1.5 - It might not be as optimized as possible due to the unused packages, which could lead to longer execution time.
- Annotations and comments: 1 - The current version lacks comments that would make code understanding easier for others.

Please, consider these tips to enhance your code. And once done, submit your modifications via a new pull request on GitHub.

**Comment by vajrang-b** [comment]
SourceCode/2023/oct2023/Basics/Praveenraja S V/Task_4/project.json
### Review for NoFile:

1. Automation Hub URL missing: Update your project settings to add this information. 
2. Unused packages: You've included the UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities packages, but you're not using them. Remove these to streamline your process execution time.

### Review for Main.xaml:

1. Duplicate activity names: You've used "Assign" and "Message Box" multiple times for activity names. Please use unique and descriptive names to make your code more readable. 
2. Variable naming pattern: The variables "Year_Input", "Boolean_Variable" do not follow the acceptable pattern. Please revise according to guidelines. 
3. Default activity names: You've got a few activities including "Log Message", "If", "Assign", "Message Box" which are using the default names. Consider giving these activities more descriptive names to improve readability.

### Scoring:

1. Code completion: 1 (Code is incomplete with missing Automation Hub URL and unnecessary dependencies)
2. Execution: 2 (There are no indications that the code would not execute as expected)
3. Annotations and Comments: 0 (No annotations or comments are present) 

This

**Comment by vajrang-b** [comment]
SourceCode/2023/oct2023/Basics/Praveenraja S V/Task_5/project.json
Comments on Flowchart.xaml:

1. Log Message not used in workflow Flowchart.Xaml: Include oft-used Log Message activities to understand flow path during development and maintenance, and to quickly find errors.

2. Activity Flowchart has a default name: Change the name of the activity to be more descriptive and clear.

Score - Code completion: 2, Execution: 2, Annotations and comments: 0.5

Comments on Main.xaml:

1. Log Message not used in workflow Main.Xaml. Include often used Log Message activities to understand flow path during development and maintenance and to quickly locate errors.

2. WriteLine activity usage at Write Line: Replace Write Line with tracepoints during debug and remove before publishing. If required for debugging, change WriteLine to Log Message.

3. Flowchart Add two different Variable types: For better readability and maintainability, use Flowchart in top layer.

4. Assign display name is defined multiple times. Keep the names of activities unique and clear for better understanding. Default names might be too generic.

5. Several activities have default names. Give descriptive titles to all activities for a clearer understanding of their function.

Score - Code completion: 1.5, Execution: 2, Annotations and comments: 0

Comments on NoFile:

Several

**Comment by krish952-creator** [comment]
@PRAVEENRAJA1699 
Task -1
Code verified.
Task -3
Code verified.
Task -4
Code verified. Default activity names
image
 
Task -5
Code verified. Default activity names
image

**Pull request merged**
