### PR TITLE
Task 24,26

### PR DESCRIPTION
**Pull request by rajendrayarlagaddausa333**

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Rajendra/Task24/project.json
### Main.xaml

* `WriteLine` activity usage at `Write Line`: These activities can be replaced with tracepoints during debug. They should be removed before publishing.
* Consider changing `WriteLine` to `Log Message` if it is really needed for debugging purposes.

### Variables

* `Str_Input` does not respect the set pattern: Make sure all variables follow the naming convention.
* `Str_replace` does not respect the set pattern: Make sure all variables follow the naming convention.

### Names

* Write Line display name is defined many times. Current allowed threshold is 1. Code contains 2: Please avoid duplicate names and make them more descriptive to indicate how they are being used.

Overall Score: 4/5

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Rajendra/Task26/project.json
**Main.xaml**
- Log messages are not used in the workflow Main. This makes it difficult to understand the flow path and identify errors.
- The message box display name is defined multiple times, which should be avoided.

**Variable naming convention**
- The variables `random_` and `Int_Guess` do not follow the set pattern. They should be renamed to adhere to the naming convention.

**Activity naming convention**
- Activity names should be more descriptive and avoid duplicates.
- Activities like Assign, Message Box, Input Dialog, State Machine have default names that could be improved with more descriptive titles.

**Dependency packages**
- The following unused dependency packages are present: UiPath.Excel, UiPath.Mail, UiPath.Testing, and UiPath.UIAutomation. These should be removed to improve process execution time.

**Score: 4/5**

Note: I did not provide code suggestions as requested.

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Rajendra/Task24/project.json
**Main.xaml**
The code uses `WriteLine` activities extensively. Consider replacing them with tracepoints during debug and removing them before publishing. Additionally, consider changing `WriteLine` to `Log Message` if it's necessary for debugging purposes.

**Variable naming conventions**
Variables Str_Input and Str_replace do not follow the set pattern. Make sure all variables adhere to the naming convention.

**Unused dependencies**
The code includes unused packages like UiPath.Excel.Activities, UiPath.Mail.Activities, etc. Remove them to improve process execution time.

**Activity naming conventions**
Some activities have default names. Check if they could be made more descriptive by adding a title. Also, avoid duplicate names for activities and variables.

**Score: 5/5**

Note: I didn't provide code suggestions as per your request.

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Rajendra/Task25/project.json
**Main.xaml**
The Log Message activities are not being used in the workflow. Using these activities is important for understanding the flow path during development and after release. They help with maintenance and identifying the source and cause of errors.

**Variables**
Variable ExtractDataTable does not have a DataTable prefix (should start with "dt_").

**Activity Naming**
The activity Extract Table Data has a default name. Consider adding a more descriptive title to make it easier to understand what the activity does.

**Dependency Packages**
Dependency packages UiPath.Mail.Activities, UiPath.System.Activities, and UiPath.Testing.Activities are not used. Remove unused packages to improve process execution time.

**Score: 5/5**

Note: This review focuses on providing clear and actionable feedback for the developer to improve their code. It does not provide specific code suggestions or alternatives.

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Rajendra/Task26/project.json
**Main.xaml**
Log message not used in workflow Main. It's recommended to use log messages for better understanding of the flow path during development and error handling after release.

**Variable naming convention**
The variables `random_num` and `Int_Guess` do not follow the set pattern. Please ensure all variable names follow the naming convention.

**Message Box display name**
The code contains multiple message box display names, exceeding the allowed threshold of 1. It's recommended to use more descriptive titles for activities to avoid duplicate names.

**Activity default names**
Several activities have default names that could be improved by adding a more descriptive title. This would make it easier to understand what each activity does.
```markdown
Score: 4/5
```
Note: I've grouped the issues based on file name, and addressed them in a simple and concise manner.

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Rajendra/Task24/project.json
Here is my review:

**Main.xaml**
- The `WriteLine` activities are being used for debugging purposes only. They should be removed before publishing.
- Consider replacing them with tracepoints during debug.

**General**
- Unused dependencies:
	+ UiPath.Excel.Activities
	+ UiPath.Mail.Activities
	+ UiPath.System.Activities
	+ UiPath.Testing.Activities
	+ UiPath.UIAutomation.Activities
	Remove unused packages to improve process execution time.
- Variable naming convention is not respected for `Str_Input` and `Str_replace`. Make sure all variables follow the naming convention.

**Variable naming**
- All variable names should follow a consistent pattern. Ensure that all variables are named correctly.

**Activity naming**
- The display name of `WriteLine` activities is defined many times. Please avoid duplicate names.
- Activities with default names, like `Write Line`, could be easier to understand with more descriptive titles.

Score: 5 out of 5

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Rajendra/Task25/project.json
**Main.xaml**
Log Message not used in workflow Main. It's important to use Log Message activities both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause.

**Score: 5/5**

**NoFile**
Your organization requires your project to have an Automation Hub URL defined. Please add the missing information in Project Settings.

**Score: 5/5**

**Main.xaml**
Variable ExtractDataTable doesn't have DataTable prefix. DataTable Variable should start with a dt_ prefix.

**Score: 5/5**

**Main.xaml**
Activity Extract Table Data has a default name. Check if it could be easier to understand what the activity does by adding a more descriptive title.

**Score: 5/5**

**Dependency packages**
Dependency package UiPath.Mail.Activities is not used. Remove unused packages in order to improve process execution time.
Dependency package UiPath.System.Activities is not used. Remove unused packages in order to improve process execution time.
Dependency package UiPath.Testing.Activities is not used. Remove unused packages in order to improve process execution time.

**Score: 5/5**

Total Score: **20/20**

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Rajendra/Task26/project.json
### `Main.xaml`

* Log Message not used in workflow Main: Make sure log messages are added throughout the workflow for better debugging and understanding.

### Naming Convention

* Variable random_num does not respect the set pattern: Update variable naming to follow convention (e.g., dt_RandomNum).
* Variable Int_Guess does not respect the set pattern: Update variable naming to follow convention (e.g., dt_IntGuess).

### Activity Names

* Activity State Machine has a default name: Rename activity with a more descriptive title.
* Activity Assign has a default name: Rename activity with a more descriptive title.
* Activity Message Box has a default name: Rename activity with a more descriptive title.
* Activity Input Dialog has a default name: Rename activity with a more descriptive title.

### Duplicate Names

* Message Box display name is defined many times: Remove duplicate names by using more descriptive titles or combining similar activities.

**Score: 4/5**

Note: The review focuses on suggesting improvements for better code organization, naming convention, and debugging. No specific code suggestions are provided.

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Rajendra/Task27/project.json
**Substraction.xaml**
- The naming convention for `out_` variables is not followed.
- No Log Message activities are used in this workflow.

**NoFile**
- The project requires an Automation Hub URL, which is currently missing. This should be added in Project Settings.

**Main.xaml**
- There are multiple instances of Write Line activity with display names defined, but the same name is used. This exceeds the allowed threshold.
- No Log Message activities are used in this workflow.
- The Write Line activities can be replaced with tracepoints during debug and then removed before publishing.
- Some activities have default names that could be more descriptive.

**Addition.xaml**
- Two arguments (`In_num1` and `out_add_`) do not follow the naming convention for `in_` and `out_` variables.
- No Log Message activities are used in this workflow.
- One activity has a default name that could be more descriptive.

Score: 4/5

Note: The score is based on the completeness of the review. All issues have been identified, but some suggestions for improvement were not provided.

**Comment by krish952-creator** [comment]
@rajendrayarlagaddausa333 
Task – 24
Code verified.
Task – 25
Code verified.
Task – 26
Code verified.
Task – 27
Code verified.

**Pull request merged**
