### PR TITLE
Task 11

### PR DESCRIPTION
**Pull request by Khantil12**
Display Fruit name with Flowchart

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 11/project.json
@dev_team, I've completed the code review for this PR. Below are the pointers for your perusal, please take appropriate actions.

1) File: NoFile
   - Completeness of Project: Please add the missing Automation Hub URL in your Project Settings. Respect the organizational rules, buddy.
   - Execution: Noticed few unused dependency packages. We don't need Excel.Activities, Mail.Activities, Testing.Activities, and UIAutomation.Activities right now. Removing them is a smart step against potential code bloat and sluggish execution. 

2) File: Main.xaml
   - Code Comprehension: Log Messages are the flashlight in our night trek. Let's use them in the 'Main' workflow. They disclose the flow path and root cause whenever an error occurs and eases the maintenance bit too. 
   - Naming Convention: The variable 'Fruit_name' isn’t fitting the set pattern. Let's stick to the established naming structure for smooth team collaboration.

Code completion: 2/2
Execution: 1.5/2 
Annotation and comments: 0.5/1

Take a look and let me know if you have questions. Let’s keep it clean and effective. 

compileComponents

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 11/project.json
### NoFile
**Score**: Code Completion - 1/2, Execution - 1/2, Annotations and Comments - 1/1.

**Comments**:

1. Looks like you forgot to add an Automation Hub URL to your project. Using the "Project Settings" options, add it in so it meets company requirements.
2. You have packages in your project that aren't being used, like UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, and UiPath.UiAutomation.Activities. When you delete these, the project's execution time can be improved. 

### Main.xaml
**Score**: Code Completion - 1/2, Execution - 2/2, Annotations and Comments - 0/1.

**Comments**:

1. There's no Log Message activities found in main workflow (Main). Log Messages are really good for seeing how the project is flowing and spotting any errors. Add these in where necessary.
2. For the 'Fruit_name' variable, try following the naming pattern ^(dt)?([A-Z]|[a-z])+([0-9])*$, it appears it's not fitting into the norm.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 13/project.json
In the **NoFile** section:
This code is missing an Automation Hub URL. Please define it using the 'Project Settings'. The code carries unused packages like UiPath.Mail.Activities, UiPath.MicrosoftOffice365.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities. These need to be removed to make the code lighter and faster.

In the **Main.xaml** section:
There is no use of 'Log Message' which is important to understand the flow path for both development and error-identification. 'Task 13' is a redundant sequence, and it should be removed to unclutter the workflow. Variables 'Output' and 'Read_Excel' don't carry a 'dt_' prefix which is required for DataTable Variables. Check if your 'Comment Out' and 'Read Range' activities could use more descriptive names. Also, the variable 'Read_Excel'doesn't follow the naming convention: ^(dt_)?([A-Z]|[a-z])+([0-9])*$

Scoring:
Code Completion 1.5 (Needs the removal of redundant sequences and proper naming of variables)
Execution 1.5 (Execution could be improved by logging messages)
Annotations and comments 0.5 ('Comment Out' and

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 11/project.json
**NoFile** 
- Add your Automation Hub URL in the "Project Settings" as it's a requirement from your organization. 
- I noticed UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities. packages are all included but not used. Remove them so that the process runs more smoothly. 

**Main.xaml** 
- There's no use of Log Message in the Main workflow. Log Messages are key during and after development to understand the flow path. They help not just in maintaining the project but also in identifying the source and cause of an error if it occurs.
- Variable Fruit_name doesn't follow the correct naming convention. Please revise it.

_Score:_
- Code Completion: 1.5
- Execution: 1.5
- Annotations and Comments: 0.5

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 13/project.json
#### Code Review Comments and Score

#### NoFile

1. You forgot to include the Automation Hub URL. This is required by your organization. To solve this issue, add the URL via "Project Settings". [Code Completion - 0.8]

2. UiPath.Mail.Activities, UiPath.MicrosoftOffice365.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities packages are not being used. They should be removed to make your process run faster. [Execution - 0.8]

#### Main.xaml

1. You're not using any Log Messages in Main workflow. These are important to understand the flow path and identify the source of errors. Start using them. [Annotations and Comments - 0.2]

2. Task 13 sequence is redundant. Avoid using unnecessary sequences as it complicates the workflow. Use the Remove Surrounding Sequence to get rid of them. [Execution - 0.6]

3. Variables "Output" and "Read_Excel" should have a prefix of dt_ since they are DataTables. Start using the convention. [Code Completion - 0.2]

4. Activities Comment Out and Read Range are still using default names. Give them descriptive titles to increase understanding of your activity.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 13/project.json
# NoFile

- This project needs an Automation Hub URL. Go to "Project Settings" to fix this.
- There are several unused packages: UiPath.Mail.Activities, UiPath.MicrosoftOffice365.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities. It's best to remove these. They're just slowing you down.

# Main.xaml

- You're not using any Log Message activities in Main workflow. These help track how your process is running and can help spot errors.
- "Task 13" sequence doesn't need to be there. It just makes the workflow messier. Use "Remove Surrounding Sequence" to get rid of it.
- The variable "Output" and "Read_Excel" needs a "dt_" prefix. We do this with all DataTable variables.
- Your "Comment Out" activity needs a better name. Give them descriptive titles so we know what they do.
- The variable "Read_Excel" isn't following our naming convention. Make sure it does.
- Your "Read Range" activity could use a better name.

# Scores:
- Code Completion: 1.5/2. There are redundant sequences and the project lacks Automation Hub URL.
- Execution: 1.5/

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 11/project.json
**NoFile:**
- Consider adding the Automation Hub URL in the Project Settings, as this might be a requirement within your organization. Finding this is pretty straightforward in the settings.

- There seems to be unused packages here - UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities. You can get rid of them to bring down the process execution time. It's good to keep things tidy. 

**Main.xaml:**
- Make sure you are logging things right in the Main workflow. With appropriate logging, you could troubleshoot errors easily and also understand the workflow's path better. 

- Check on the variable `Fruit_name`. We have set patterns to follow and it seems to be not respecting that. Stick to the rules for smooth sailing.

**Scores:**
1. Code completion: 1.5
2. Execution: 1.5 
3. Annotations and Comments: 0.5

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 13/project.json
## Main.xaml
### Score: 
- Code Completion: 1.5
- Execution: 1.5
- Annotations and Comments: 0.5

### Feedback:
- [_removed_: Cell] Add the Automation Hub URL to the "Project Settings". It is a requirement for our project.
- You have some packages (UiPath.Mail.Activities, UiPath.MicrosoftOffice365.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities) that are not being used in your project. Remove them to speed up the process execution time.

- There are no log messages in your Main workflow. Using Log Message activities will help in debugging both during development and after release. They can also help us quickly locate errors if/when they happen.
- The sequence 'Task 13' in your Main workflow is not needed. Cleaning up such sequences makes your workflow easier to understand and maintain. You can use the "Remove Surrounding Sequence" option in UiPath Studio for this.
- Your variable 'Output' needs to be prefixed with 'dt_' as it is a DataTable.
- The 'Comment Out' activity needs a more descriptive title. This makes your code easier to understand for other people.
- Same as 'Output', your variable '

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 11/project.json
NoFile:

- You have forgotten to add an Automation Hub URL in your "Project Settings". Please add the missing information.
- Your project has several dependency packages (UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities) that are not being utilised. Please remember to remove these unused packages, it helps in improving process execution time. 

Main.xaml:

- There is no "Log Message" used in the Main workflow. Using log messages can be very beneficial during the development phase as well as post-release. These log messages can help you understand the workflow path better and when an error occurs, you can easily pinpoint the source and its cause.
- A variable 'Fruit_name', does not respect the set convention (should match the pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$). Please ensure all your variables follow the correct naming conventions.

Scores:
- Code Completion: 1 (Issue with unused packages)
- Execution: 2 (No issues related to execution were found)
- Annotations & Comments: 0.5 (Logging was missing in the Main.xaml file)

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 13/project.json
**File: NoFile**

1. Automation Hub URL is Important. Please put this using "Project Setting". Your score for code completion: 2
2. If you are not using the UiPath.Mail.Activities package, please remove it. Saves times and keeps it clean. You are scored 2 for execution.
3. Same for UiPath.MicrosoftOffice365.Activities. Not in use means not needed. Your score for execution stays at 2.
4. You seem to have UiPath.Testing.Activities as a surplus. Uninstall this one too. Your score for execution still stands at 2.
5. UiPath.UIAutomation.Activities is not being used as well. Follow the same and remove. Execution score: 2.

---
**File: Main.xaml**

1. Logging is crucial. Use Log Message in Main workflow. Helpful during and post development. Code completion: 1.5
2. Got a sequence Task 13 which seems repeated. Avoid such clutter by removing. Use Remove Surrounding Sequence from Context Menu. Code completion: 1
3. Variables for DataTable should start with `dt_`. Change `Output` to follow this. Code completion: 1
4. Can you make 'Comment Out' activity more

**Comment by krish952-creator** [comment]
@Khantil12 
Task -2
Code verified. 
Task -3
Code verified. 
Task -5
Code verified. 
Task -6
Code verified. Default activity name 
 
image

Task -11
Code verified. 
Task -13
Code verified. Default activity name 
image

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 11/project.json
---
**Code Completed: 1/2**
- UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities were added as a dependency but not used.
- Follow standard naming conventions for your variable (e.g. Fruit_name does not conform to the expected regex pattern).

**Execution: 1/2**
- Unused dependencies are bogging down your software. Remove them to improve performance.

**Annotations and Comments: 0/1**
- You're not using Log Message. You should, it helps understand the flow of the code and debugging errors.

---

**Solutions:**
- Go to "Project Settings" and define the Automation Hub URL.
- Remove UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities from your dependencies if they're not being used.
- Rename your variable 'Fruit_name' to follow the correct pattern. A suggestion could be 'fruitName' or 'fruit_name'.
- Incorporate the use of Log Message in your workflow to help monitor the program's progress and as a debug tool.

By making these adjustments, your code should be more efficient and easier to read and debug. Keep on coding,

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 13/project.json
File: NoNameFile

1. Add the missing Automation Hub URL through your Project Settings.
2. Unused dependency packages such as UiPath.Mail.Activities, UiPath.MicrosoftOffice365.Activities, UiPath.System.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities are found in your project. Remove these to make your process run faster.

File: Main.xaml

1. Log messages are missing in your workflow labeled 'Main'. These are important to help you understand the flow path during development and help in error identification after release.
2. Found variables 'Output' and 'Read_Excel' without DataTable prefix. Name your DataTable variables starting with 'dt_'.
3. The variable 'Read_Excel' does not conform to the stated pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*. Follow this pattern for naming your variables.

Score:
- Code Completion: 1.5/2 (Some naming conventions aren't followed)
- Execution: 2/2 
- Annotations and Comments: 0.5/1 (Logging is missing)
Total Score: 4/5

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 11/project.json
Main.xaml:

1. "Log Message not used in workflow Main" - Use Log Message activities to understand the workflow, both during development and after release. They help you figure out bugs and sources quickly.

2. "Variable Fruit_name does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$" - Make sure every variable follows the naming rules. 

NoFile:

1. "Your organization requires your project to have an Automation Hub URL defined" - Use "Project Settings" to enter required URL info.

2. "Dependency packages UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities not used" - Drop the unused packages to speed up the process running time.

Score: 
1. Code Completion: 2/2
2. Execution: 1.5/2 - project requires Adaptation Hub URL to be defined for execution.
3. Annotations and Comments: 0.5/1 - Log Message should have been used to make code readable for others.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 13/project.json
Code Review for NoFile:

1. Your project lacks the Automation Hub URL. Solve it by going to your "Project Settings" and add the required info.
Score: Code Completion: 1, Execution: 2, Annotations and Comments: 1

2. Seems like you have got a few unused dependency packages here - UiPath.Mail.Activities, UiPath.MicrosoftOffice365.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities. Trim them off. Your process execution will be faster.
Score: Code Completion: 2, Execution: 1, Annotations and Comments: 1

Code review for Main.xaml:

1. Can't see any Log Message in 'Main'. Log Messages can be a great help during development and post-release. They help you understand the flow and make errors easy to fix.
Score: Code Completion: 2, Execution: 1, Annotations and Comments: 1

2. 'Task 13' sequence seems redundant. Clear it off; it'll make your workflow less messy. Use the "Remove Surrounding Sequence" option in UiPath Studio.
Score: Code Completion: 2, Execution: 2, Annotations and Comments: 1

3. The 'Ignored Activities' display

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 11/project.json
#### `NoFile` Code Review:

**Score: NoFile - Completion: 2, Execution: 1, Annotations/Comments: 0**

**1. Missing URL for Automation Hub:**
Include your project's Automation Hub URL. You can do this in the "Project Settings".

**2. Unused Dependencies:**
Your code has several unused packages such as UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities. Delete these to speed up your system.

---

#### `Main.xaml` Code Review:

**Score: Main.xaml - Completion: 2, Execution: 1, Annotations/Comments: 1**

**1. Missing Log Message:**
Logs are important because they help you understand the flow of your code. This makes regular maintenance easier and can help you find the source of errors when they come up. I recommend adding them to your workflow.

**2. Variable Naming Convention:**
Your variable "Fruit_name" doesn't follow the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*. Be consistent and use proper naming conventions to make your code more readable.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 13/project.json
**Score:**
- Code Completion: 1.5/2
- Execution: 1.5/2
- Annotations and Comments: 0.5/1 

**Comments:**

- You've missed adding the Automation Hub URL in your project settings. Go to 'Project Settings' to add this missing information.
- Found several dependency packages that you're not using - 'UiPath.Mail.Activities', 'UiPath.MicrosoftOffice365.Activities', 'UiPath.Testing.Activities', and 'UiPath.UIAutomation.Activities'. Clear them out to speed things up.

**Comments for Main.xaml:**

- Add a log message to your workflow in the 'Main' for debugging and better understanding of your flow.
- You have a sequence 'Task 13' which is not doing anything. It's just clutter, clear it out.
- 'Ignored Activities' and 'Comment Out' display names are repeated. Ditch the generics and give them clear, unique names.
- Your variables 'Output' and 'Read_Excel' don't follow the DataTable naming convention. Prefix them with 'dt_'.
- 'Read_Excel' is not following another set pattern. You gotta fix that too.
- 'Comment Out' activity has a default

**Comment by krish952-creator** [comment]
@Khantil12 
Task - 6
changes verified.
Task -13
changes verified.

**Pull request merged**
