### PR TITLE
Task3to5

### PR DESCRIPTION
**Pull request by Mohdabid161**
Here include three tasks
1.Data&time display & printed text format
2.finding Leap Year by if statement control statement 
3.Adding two different data type by using genericvalue

### CODE REVIEW

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "WriteLine activity usage at Write Line.":  "Write Line activity can be replaced with tracepoints during debug. They should be removed before publishing. Consider also changing WriteLine to Log Message if it is really needed for debugging purposes. "
                      },
                      {
                          "Flowchart Flowchart is used in a secondary layer in Main.":  "Flowchart should only be used in top layer for maintainability and readability reasons. "
                      },
                      {
                          "Activity Flowchart has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Write Line has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "WriteLine activity usage at Write Line.":  "Write Line activity can be replaced with tracepoints during debug. They should be removed before publishing. Consider also changing WriteLine to Log Message if it is really needed for debugging purposes. "
                      },
                      {
                          "Variable da_te does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$|_out_[A-Za-z][A-Za-z0-9_]*$":  "Make sure all the variables follow the naming convention. "
                      },
                      {
                          "Activity Assign has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Write Line has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Write Text File has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "Message Box display name is defined many times. Current allowed threshold is 1. Code contains 2.":  "Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names. "
                      },
                      {
                          "Activity Input Dialog has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by krish952-creator** [comment]
@Mohdabid161 
Task -3
Code verified. Default activity names 
 
image

Task -4
Code verified. Default activity names 
 
image

Task -5
Code verified. Default activity names 
image
 
Before submitting a pull request, please ensure that the code is placed in the correct task folder. Take a moment to double-check and make any necessary adjustments

**Pull request merged**
