### PR TITLE
Completed 10 task

### PR DESCRIPTION
**Pull request by suvedharan**
Completed

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Suvedharan/Task23/project.json
**Code Completion: 1**

Your code doesn't complete all parts of the project.

There are several unused dependency packages (UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities). Getting rid of these will make your program run faster.

You also forgot to include an Automation Hub URL for your project. You can set this up in Project Settings.

**Execution: 1**

Your code doesn't execute as expected, with many places for improvement.

"Log Message" isn't used in your workflow. This helps you trace where the problem is during development and even after release.

Your sequence for concatenating two variables is unnecessary. Removing it makes your workflow cleaner.

**Annotations and Comments: 0**

There are several activities with default or repeated names. It'll be easier to understand the purpose of the activities if you give them descriptive, unique titles.

Your code's structure will improve, and it'll be simpler to collaborate and maintain the code. 

Remember, comrades, clear and poignant communication often makes the difference between standing strong and crumbling in the face of adversity. Keep your code clean, orderly and well-documented.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Suvedharan/Task24/project.json
GitHub Comment for PR:

**File: NoFile**
1. Looks like the project doesn't have an Automation Hub URL defined. You can fix it by going to `Project Settings` and adding the necessary details.

2. There are several dependency packages that are not in use like `UiPath.Excel.Activities`, `UiPath.Mail.Activities`, `UiPath.System.Activities`, `UiPath.Testing.Activities`, `UiPath.UIAutomation.Activities`. It's better to remove them as they'll make the process execution faster.

**File: Main.xaml**
1. No `Log Message` is found in the Main.xaml workflow. They're really important as they help in understanding the path of the flow that's quite useful for both maintenance and pinpointing errors.

2. Noticed usage of `WriteLine activity` at `Displaying the stored value` and `Output of the replaced value`. Ideally, during debugging, they should be swapped with `tracepoints` and removed before publishing. If it's crucial for debugging, you should opt for `Log Message` instead of `WriteLine`.

**Overall Scores:** 
- Code Completion - 1/2 (Need to resolve unused package dependencies)
- Execution - 2/2 
- Annotations and Comments -

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Suvedharan/Task26/project.json
## NoFile

- **Automation Hub URL**: Your project doesn't have a declared Automation Hub URL. Set it in the "Project Settings".
- **Unused Packages**: I see UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities packages are added but not utilized. Remove them to quicken your process execution time.

## Main.xaml

- **Log Message**: Your workflow lacks a Log Message activity. These activities help track the development journey and debug the workflow if needed. Consider using it.
- **Repeated Activity Name**: Message box activity names are repeated 6 times. Activity names should reflect their operation. Avoid repeated and generic names.
- **Default Name for Activities**: Several activities such as Assign, Message Box, Input Dialog still have default names. Changing it to a more descriptive one will improve code readability.

In terms of criteria scoring based on the review:

- **Code completion**: 2 (Done, but areas need improvement)
- **Execution**: 2 (Can't validate execution without running, but no blocking issues seen in the XAML code)
- **Annotations and comments**: 0.6 (Needs much more commenting and renaming of activities)

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Suvedharan/Task_18/project.json
{
    "NoFile": [
        {
            "message":"Your project is missing the required Automation Hub URL. In the Project Settings, add this information."
        },
        {
            "message":"You've included the UiPath.Mail.Activities package, but it's not being used. Remove it to speed up process execution."
        },
        {
            "message":"You've included the UiPath.Testing.Activities package, but it's not being used. Remove it to speed up process execution."
        },
        {
            "message":"You've included the UiPath.UIAutomation.Activities package, but it's not being used. Remove it to speed up process execution."
        }
    ],
    "Main.xaml":[
        {
            "message":"I see no Log Message used in your Main workflow. It's a good practice to use Log Message activities while developing. They help you track the flow and diagnose issues when errors occur."
        },
        {
            "message":"I see a variable, DtOutputtable, without a DataTable prefix. For clarity, prepend it with a dt_ prefix."
        }
    ],

    "Score": {
        "code_completion": 1.5,
        "execution": 1.5,
        "annotations_comments":

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Suvedharan/Task_19/project.json
Score:

- Code Completion: 1/2 - Project lacks an Automation Hub URL.
- Execution: 2/2 - There doesn't seem to be any errors preventing code execution.
- Annotations and comments: 0/1 - Usage of log messages for better understanding of the workflow is missing.

Total: 3/5

Review:

- Main.xaml: Log Message activity should be used in your workflow. This is essential during development and after code deployment. It helps understand the workflow better and trace any errors back to their source.
- NoFile: Your project lacks an Automation Hub URL. You could add this in your "Project Settings". This is necessary as per your organization's requirements.
- NoFile: Several dependencies like UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.System.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities are included but not used. These unnecessary dependencies can slow down your project execution. It's better to remove them.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Suvedharan/Task_20/project.json
## NoFile Review Comments

1. Your organization requires your project to have an Automation Hub URL defined. For fixing it, please go to "Project Settings" and add the missing information.

2. I noticed that the dependency package 'UiPath.Mail.Activities' is not used. To improve the execution time of the process, it would be beneficial to remove unused packages.

3. Similar to above, another unused package 'UiPath.Testing.Activities' is also present. For better performance, please remove this package.

## Main.xaml Review Comments

1. The workflow 'Main' is not using the 'Log Message' activity. Using this activity can be helpful both during the development process and after release. It helps to understand the execution flow and can make it easier to identify the source and cause of errors. Please consider using it.

2. The variable 'ExcelSheet' is not following the standard naming convention for DataTable - 'dt_'. Kindly update the variable name.

3. The naming of 'Cell_ID' variable does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$. Please follow the defined naming conventions for variables.

### Scores
- Code Completion: 2
- Execution: 1.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Suvedharan/Task_21/project.json
NoFile:

1. Project is missing an Automation Hub URL. Fix: Use "Project Settings" to add the missing information.

2. UiPath.Mail.Activities package isn't used. Fix: Remove unused packages to improve process execution time.

3. UiPath.Testing.Activities package isn't used. Fix: Remove unused packages to improve process execution time.

Score: Code Completion: 1, Execution: 1, Comments: 0

Main.xaml:

1. Log Message activity is not used. Fix: Using Log Message activities can be useful during development and post-release for error tracing, consider adding them if appropriate.

2. Variable Dt_Output doesn't have DataTable prefix. Fix: DataTable Variables should start with a dt_ prefix.

3. Variable Dt_Output doesn't follow set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*. Fix: Ensure all variables follow the naming convention, in this case, DataTable variables should start with dt_prefix.

4. Variable Cell_ID doesn't follow set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*. Fix: Ensure all variables follow the naming convention. 

5. Certain activities have a default name. Fix: Assign descriptive titles to activities to easily understand

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Suvedharan/Task_22/project.json
Here's a breakdown of improvements that could be made to your code:

### NoFile
- Automation Hub URL is missing. Go to `Project Settings` to add this information.
- Unused dependency packages `UiPath.Mail.Activities` and `UiPath.Testing.Activities` found. Best to remove them to speed up process execution time. 

### Main.xaml
- You might want to use `Log Message` in your workflow. They are helpful in understanding the flow path during development, and can also make it easier to find the source of errors. 
- The variable names `ExcelSheet` and `ResultDT` should use proper prefix indicating their type, for example, `dt_ExcelSheet` and `dt_ResultDT`. 

### Scores
- Code Completion: 1.5
- Execution: 1.5
- Annotations and Comments: 0.5

Please take these points into consideration and apply necessary changes to improve your code.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Suvedharan/Task_28/project.json
Your PR #xxxxxx review is done, here is what to do:

1. **No File**
- Fill in the Automation Hub URL. Go to "Project Settings" and provide the URL there.
- There are some packages like UiPath.Excel.Activities and UiPath.Mail.Activities not needed for this project. Please remove them to speed up the process.

2. **Main.xaml**
- Please remember to use "Log Message" activities. They help us understand more during the development and troubleshooting phase, easy to find where stuff broke.
- You have a sequence named "Excuting different activities in PDF" presenting more than once, Clean it up, you can use the option called 'Remove Surrounding Sequence' in UiPath Studio, just a right-click away.
- The activity "Tesseract OCR" is named as default, how about giving it a better name that tells us what it does without checking into details.

Make these changes and submit again, looking good otherwise.

Scored your code as below:

Code Completion: 1.5/2 - There are a few missing parts, but they are not a big problem.

Execution: 1.5/2 - The redundant sequences slow down the process.

Annotations and Comments: 0.5/

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Suvedharan/Task_4/project.json
Here's the review:

1. No File:
- It appears your project is missing an Automation Hub URL. Go to "Project Settings" and add it.

- It seems you've included several packages that you aren't using like UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities and UiPath.UIAutomation.Activities. Get rid of these to speed up the process.

2. Main.xaml:

- I see you've not used the Log Message in the Main workflow. These are essential for tracking workflow lifecycle and spotting errors. You should consider adding them where necessary.

- The Assign, Multiple Assign and Message Box activities all have default names. You can replace these with something more understandable, it helps with readability and maintenance.

Score:
Code Completion: 2/2.
Execution: 1.5/2, add log message activities and remove unused packages.
Annotations and Comments: 0.5/1, rename activities to improve the clarity of the code.
Overall: 4/5, Good job, but there's room for improvement.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Suvedharan/Task23/project.json
GitHub comment for PR

File: NoFile
1. Your project is missing an Automation Hub URL which is required by your organization. To fix this, add the missing information in the "Project Settings".
2. There are several dependency packages (UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities) that are not being used. To improve on the process execution time, please remove these unused packages. 

Score: Code completion: 1.5, Execution: 2

File: Main.xaml
1. Your workflow "Main" is lacking Log Message activities which are crucial to understanding the flow path and for maintenance purposes. Please add these where they are needed. 
2. The sequence named "Concating the two variable strings" appears to be redundant. Using redundant sequences can clutter the workflow. It would be best to remove redundant sequences to clean up the workflow.
3. The activity display name "Assign" has been defined multiple times (currently 2). Avoid having duplicate names to provide a clear indication of how they are being used.
4. Several activities "Assign", "Message Box" have default names. By giving these a more descriptive title will help in understanding what the activity does

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Suvedharan/Task24/project.json
"Main.xaml"
- Using of 'Log Message' is recommended both during development and after release. They help in understanding the flow path which is very useful for maintenance and when an error occurs, it helps to identify the problem easier. Use 'Log Message' in your workflow. 
- 'Write Line' activity at 'Displaying the stored value' and 'Output of the replaced value' can be replaced with tracepoints during debugging and should be removed before publishing. If it is crucial for debugging purposes, consider changing 'Write Line' to 'Log Message'.

No Specific File
- Adding an Automation Hub URL defined in 'Project Settings' is needed by your organization. Please add it.
- Clean up your code by removing unused packages like UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.System.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities. This will improve process execution time.

Score
- Code completion: 1.5/2 (All required actions in the code are not completed)
- Execution: 1/2 (Code execution can be improved by removing unused packages)
- Annotations and comments: 0.5/1 (Lack of log messages make it hard to understand the flow of the

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Suvedharan/Task26/project.json
Based on the provided information, here is your score and the review for your code.

**Scores:** 
Code Completion: 1
Execution: 1
Annotations and Comments: 0

---

**NoFile:**

1. Missing Automation Hub URL in project settings. You need to provide URL in Project Settings.
   
**Unused Dependency Packages:**

2. There are several unused dependency packages, including UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities. Removing them could help decrease process execution time.

---

**Main.xaml:**

1. There is no use of Log Message in Main.workflow. Log Messages are significant during development and post-release to understand the flow path and easily identify the source of errors.
   
2. Message Box display name has been used more than allowed threshold. Avoid using same name multiple times. Change it to give a clear understanding of its usage.
   
3. There are several activities with default names (Assign, Message Box and Input Dialog). Giving descriptive names to these activities can provide a better understanding of their purpose and function.

---

For an efficient and optimized performance, it's essential to adhere to best practices of coding. Looking forward to seeing the improvements in the next pull

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Suvedharan/Task_18/project.json
In NoFile:

1. Define your project Automation Hub URL in "Project Settings". This information is missing and required by your organization.

2. Packages `UiPath.Mail.Activities`, `UiPath.Testing.Activities`, and `UiPath.UIAutomation.Activities` are not in use. Toss them out to make your process run smoothly and faster.

Score for Code Completion: 1.5

In Main.xaml:

1. Do use 'Log Message.' This helps you see the path your workflow takes, making fixing errors and maintenance easier.

2. Your DataTable Variable is poorly named. Call it dt_DtOutputtable, not DtOutputtable.

Score for Execution: 1
Score for Annotations and Comments: 0.5

Overall, your work needs a touch-up before it's ready. Get these fixes in place and keep learning. Keep it simple next time and only include what you need!

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Suvedharan/Task_19/project.json
In the "NoFile" and "Main.xaml" sections:

1. You forgot to integrate the Automation Hub URL in your project settings. Make sure to add the missing information.
2. There are several packages that you've included, but aren't using. Unused packages can clutter your process and increase execution time. It would be best to get rid of UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.System.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities.
3. Also, I noticed your "Main" workflow doesn't make use of the Log Message activity. These are especially helpful during development and debugging phases because they help you trace your process execution. Consider adding some where necessary.

Score:
- Code Completion: 1/2 (Code was not fully completed due to multiple unused packages and missing settings)
- Execution: 1/2 (Unused packages and missing logging could lead to inefficient execution)
- Annotations and Comments: 0/1 (Code lacks necessary comments or annotations for understanding and maintaining it).

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Suvedharan/Task_20/project.json
`Score: Code Completion - 1, Execution - 1.5, Annotations and Comments - 0.5`

**File: NoFile**
- Your project lacks a defined Automation Hub URL. Head to "Project Settings", there you can fill in the missing info.
- Better get rid of the packages you're not using like the UiPath.Mail.Activities and UiPath.Testing.Activities. It could help your project run faster.

**File: Main.xaml**
- Noticed you didn't use any Log Message in the Main workflow. They're incredibly handy tools especially when you're debugging or if something blows up, be sure to include them.
- The variable `ExcelSheet` should start with `dt_`, so it should look like this `dt_ExcelSheet`.
- Speaking of variables, make sure they stick to the naming convention. The variable `Cell_ID` doesn't follow that rule.

Keep coding, you're getting there!

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Suvedharan/Task_21/project.json
Since there's no file names in your provided structure to group the output into the Github PR comments, Here's how I would review and deliver suggestions.

**NoFile Review:**
1. **Score: 1.5/2:** Your project doesn't have the required Automation Hub URL. Fix it by adding the URL in the "Project Settings".
2. **Score: 1.5/2:** 'UiPath.Mail.Activities' and 'UiPath.Testing.Activities' packages are not used in your project. Remove unnecessary packages which slow down execution speed.
3. **Score: 0/1:** Missing annotations in the project. Adding them can help enhance understandability.

**Main.xaml Review:**
1. **Score: 1/2:** Lack of Log Messages to trace the execution process, especially during errors. Use more of it.
2. **Score: 1/2:** 'Dt_Output' variable doesn't follow the convention of prefixing DataTable variables with 'dt_'.
3. **Score: 1.5/2:** 'Dt_Output' and 'Cell_ID' variables don't respect the set pattern for naming, please follow the correct naming convention.
4. **Score: 1/2:** 'For Each

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Suvedharan/Task_22/project.json
NoFile:
- Your missing an Automation Hub URL in your project settings. Go into 'Project Settings' and add it.
- You've included UiPath.Mail.Activities in your dependency packages but you're not actually using it. Remove it so your process runs faster.
- You're not using UiPath.Testing.Activities either, remove it from your dependencies.

Main.xaml:
- Not seeing Log Message used in your Main workflow. Log Message is your friend - it helps you understand the flow path during development and lets you easily identify issues when they crop up after release.
- Your variable 'ExcelSheet' doesn't start with 'dt_' - try to keep your DataTable variables consistent to avoid confusion.
- Same issue with your 'ResultDT' variable - it should start with 'dt_'.

Score:
Code completion: 1.5
Execution: 1.5
Annotations and comments: 0.5
Overall: 3.5/5

Keep working, you're getting there!

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Suvedharan/Task_28/project.json
For NoFile: 

1. As previously noted, your organization mandates that your project must include an Automation Hub URL. You can add this required information in the "Project Settings". Score for code completion: 1/2.

2. You've added UiPath.Excel.Activities as a dependency, but it's not needed. I suggest you remove unnecessary packages to expedite the execution time. Score for code execution: 1/2.

3. Likewise, UiPath.Mail.Activities appears to be added but isn't implemented in your code. Remove it to improve execution efficiency. Score for code execution: 1.5/2.

For Main.xaml:

1. You should incorporate Log Message activity in your Main workflow. These are helpful for both development and post-release purposes, offering insights into the flow path and assisting in swift identification of issues' causes and sources. Score for code completion: 1/2.

2. Found a sequence, 'Excuting different activities in PDF' which appears redundant. Such sequences tend to clutter the workflow and should be removed. You can do so by using the 'Remove Surrounding Sequence' option of the Context Menu in UiPath Studio. Score for code execution: 2/2.

3. The 'Tesseract OCR

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Suvedharan/Task_4/project.json
## NoFile
- **Score: Code Completion 2, Execution 2, Annotations and Comments 1**
- Things to improve:
  - Add the Automation Hub URL in the "Project Settings". Your organization requires this.
  - You've got a few packages that are not being used:
    - UiPath.Excel.Activities
    - UiPath.Mail.Activities
    - UiPath.Testing.Activities
    - UiPath.UIAutomation.Activities
    - Getting rid of these will speed up your process.

## Main.xaml
- **Score: Code Completion 2, Execution 1, Annotations and Comments 1**
- Things to improve:
  - Start using Log Message activities. They’re really useful for understanding where the action is happening. Plus, when an error happens, they make it a doddle to work out why.

**Comment by krish952-creator** [comment]
@suvedharan 
Task-3
Code not available in this pr.
Task-18
Code verified.
Task-20
Code verified.
Task-21
Code verified. Need to check Selectors and output .
Task-22
Code verified. Execution error and need to check output.
Task-23
Code verified.
Task-24
Code verified.
Task-25
Code not available in this pr
Task-26
Code verified. Default activity names
image
 
Task-28
Code verified.

**Pull request merged**
