### PR TITLE
Task_18_19_20_21_22_23_24_26_27_Completed

### PR DESCRIPTION
**Pull request by PRAVEENRAJA1699**

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/oct2023/Basics/Praveenraja S V/Task_18/project.json
Comments on File: NoFile

1. Your project is missing an Automation Hub URL. To rectify this, go to "Project Settings" and insert the relevant information.

2. The dependency package UiPath.Testing.Activities is currently included in the project but is not in use. It will be more efficient if you can remove this package to decrease the process execution time.

3. The UiPath.UIAutomation.Activities package is also included but not used. You should remove it to quicken the process execution.

Score: Code completion: 1.5, Execution: 1.5, Annotations and Comments: 0.5 

Comments on File: Main.xaml

1. In your main workflow, there's no usage of Log Message activity. This feature is crucial, especially during development and post-release for easier identification of errors' source and cause. Consider including it.

2. There's a variable called Output without a prefix indicating it's a DataTable. It will be more readable if you prefix DataTable variables with dt_, e.g., dt_Output.

Score: Code completion: 1, Execution: 2, Annotations and Comments: 1

**Comment by vajrang-b** [comment]
SourceCode/2023/oct2023/Basics/Praveenraja S V/Task_19/project.json
### NoFile

- Deficiency: Your project doesn't have an Automation Hub URL defined. 
   Solution: Go to "Project Settings" and add the necessary information.

Score: Code Completion 1 / Execution 1 / Annotations and comments 0. Total Score: 2/5

### Main.xaml

- Deficiency: Log Message isn't used in the Main workflow.
   Solution: Include more Log Message activities, they’ll help you understand the workflow path and identify any errors that may occur which is useful for maintenance.

- Deficiency: Variable 'Extracted_data_from_website' doesn't follow set pattern.
   Solution: Ensure all the variables follow the correct naming convention, this helps making the variables related to their usages and purposes.

Score: Code Completion 1 / Execution 0.5 / Annotations and comments 0.5. Total Score: 2/5

Please make the necessary adjustments and adhere to the suggested solutions.

**Comment by vajrang-b** [comment]
SourceCode/2023/oct2023/Basics/Praveenraja S V/Task_20/project.json
## No File
- This project is missing an Automation Hub URL, please define it in the "Project Settings".
- The UiPath.Testing.Activities package is included but not being used. Please remove unused packages to improve process execution time.

Score: Code completion 1/2, Execution 1/2, Annotations and comments 0.5/1

## Main.xaml
- There is an absence of "Log Message" in your workflow "Main". Remember, logs are useful tools during development and post-release, they provide insights about the flow path which is crucial during maintenance and error identification.
- Your workflow contains an unnecessary "Sequence". Cleaning these up makes your workflow less cluttered and easier to read. Try using the "Remove Surrounding Sequence" option in UiPath Studio.
- Multiple variables do not adhere to the correct naming conventions, these convention rules are in place to improve readability and ease of use see below: 
    - st_Names
    - Cell_ID
    - st_Result
- Your DataTable variable "st_Names" should be prefixed with "dt_". This is another convention aimed to increase clarity in your code.

Score: Code completion 1/2, Execution 1/2, Annotations and comments 0.5

**Comment by vajrang-b** [comment]
SourceCode/2023/oct2023/Basics/Praveenraja S V/Task_21/project.json
Based on the provided files and code review, here is the scoring:

Code Completion: 1 - The code does not seem complete. Several aspects are missing, such as connecting the project to the Automation Hub URL and purging unused dependencies. Also, naming conventions for variables don't seem to have been followed.

Execution: 1 - It is not clear how well the code would execute, given the presence of redundant sequences and unused log messages and packages. Further, the WriteLine activity, which should have been replaced with tracepoints before publishing, is still in the code.

Annotations and Comments: 0 - The code does not contain any comments or annotations. These are essential for others to understand the code.

In plain English, this means the code needs a lot of improvement. It's missing links it should have, and it's got things it doesn't need. It's also not clear what some parts are doing, which could make it run slower or even crash. Also, make sure to use proper names for all parts, to avoid confusion. And remember to remove all test parts before the final version.

Total Score: 2 out of 6.

**Comment by vajrang-b** [comment]
SourceCode/2023/oct2023/Basics/Praveenraja S V/Task_22/project.json
Score:
- Code completion: 1.5
- Execution: 1
- Annotations and comments: 0.5

Comments:
- NoFile: The project is missing an Automation Hub URL, which is important for your organization's settings. Add the missing Automation Hub URL in the "Project Settings".
- NoFile: You have included the UiPath.Testing.Activities package, but it is not being used. Unused packages can cause the process execution time to increase. Remove it for better performance.
- Main.xaml: It seems that you haven't used Log Message activities. These activities are essential not just during the development phase, but also after the project is released for understanding the flow path. Do consider using them.
- Main.xaml: Naming conventions are important for readability and maintainability. Here, your DataTable variables should start with a "dt_" prefix. Ensure to correct this for all DataTables in your workflow.

**Comment by vajrang-b** [comment]
SourceCode/2023/oct2023/Basics/Praveenraja S V/Task_23/project.json
"NoFile": 
- "Your organization requires your project to have an Automation Hub URL defined.":  You need to provide an Automation Hub URL. Find it under "Project Settings".
- "Dependency package UiPath.Testing.Activities is not used.": Clear out the package 'UiPath.Testing.Activities'. Doesn't make sense to keep it if it's not in use.
- "Dependency package UiPath.UIAutomation.Activities is not used.": Same goes for 'UiPath.UIAutomation.Activities'. Remove things you don't need.

"Main.xaml":
- "Log Message not used in workflow Main.": You might want to throw in a 'Log Message' or two. It'll help you proceed when things go sideways. It's good for keeping things in check both while you're working on it and when it's running live.

Scores:
- Code Completion: 2/2
- Execution: 1/2 (You need to put in the URL for the Automation Hub.)
- Annotations/Comments: 0/1 (No log messages to map the workflow.)

**Comment by vajrang-b** [comment]
SourceCode/2023/oct2023/Basics/Praveenraja S V/Task_24/project.json
NoFile comments:

1. Please add the Automation Hub URL to your project settings. You're required to do this by our group rules.

2. Unnecessary dependency packages (UiPath.System.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities) have been noticed. Please remove them to improve process execution time. 

Main.xaml file comments:

1. I couldn't find any 'Log Message' used in the workflow. They are important for both while you're writing the code and after it's released. They help us understand how your code works and when something goes wrong, makes it easier to find what & where it went wrong.

2. I saw you're using 'WriteLine' activity to write the replaced result. But, using 'WriteLine' isn't a great practice. Instead, during the debugging process, tracepoints can be used. If it is still required, consider using 'Log Message'.

Score:
Code Completion: 1.5
Execution: 1.5
Annotations and Comments: 0.5

**Comment by vajrang-b** [comment]
SourceCode/2023/oct2023/Basics/Praveenraja S V/Task_26/project.json
#### For `NoFile`:

- There seems to be no Automation Hub URL defined in your project. Head over to the 'Project Settings' and fill in the required info.
- There are several dependency packages, such as UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities that are not being used. Consider removing these to speed up your process execution.

#### `Main.xaml` review:

- Log Messages are absent in your Main workflow. Their usage aids in both development and post-release, mainly to understand the flow path which is vital for maintenance and error identification.
- The 'Correct number display name' is defined more than once in your code, the allowed threshold is one. It's crucial to have unique activity names, they should clearly indicate their use. Revisit the code and avoid such duplicates. 

**Score:**
- Code Completion: 1.5 (due to the duplicate naming of activities and absence of Log Messages)
- Execution: 2 
- Annotations and Comments: 0.5 (Log Messages considered in scoring)
  
Remember that a well-coded workflow isn't just about getting a task done, it also needs to be manageable and understandable for others who might be working

**Comment by vajrang-b** [comment]
SourceCode/2023/oct2023/Basics/Praveenraja S V/Task_27/project.json
Subtraction.xaml:

1. Log Message is not used: Include log messages throughout your code. This will help in troubleshooting and understanding code flow. Score: 0.5 out of 1
2. Argument In_Num1 and In_Num2 do not respect naming conventions: Amend these to fit the pattern ^in_(dt_)?([A-Z]|[a-z])+([0-9])*$. Score: 1.5 out of 2
3. Argument Out_SubResult does not respect naming conventions: Alter it to fit the pattern ^out_(dt_)?([A-Z]|[a-z])+([0-9])*$ Score: 1.5 out of 2

NoFile:

1. No Automation Hub URL has been defined: Add the URL in Project Settings. Score: 1 out of 2
2. Dependency packages UiPath.Testing.Activities and UiPath.UIAutomation.Activities are not used: Consider removing these to improve execution time. Score: 1 out of 2

Main.xaml:

1. Log Message not used: Use log messages for better maintenance and tracking issues. Score: 0.5 out of 1
2. WriteLine activity used at Display Addition Result and Display Subtraction Result: Replace WriteLine

**Comment by krish952-creator** [comment]
@PRAVEENRAJA1699 
Task -18
Code verified
Task -19
Code verified
Task -20,21,22
Input file not available in folder ,So merge the file
Task -23
Code verified. 
Task -24
Code verified. 
Task -26
Code verified. 
Task -27
Code verified. Default activity name(Input file not available in folder.)

**Pull request merged**
