### PR TITLE
task5,taskk8,task10,taskk12

### PR DESCRIPTION
**Pull request by sharuk-cherukubilli**

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Sharuk/Task10/project.json
**Main.xaml**
The log message activity is not being used in the workflow `Main`. This can make it difficult to understand the flow of the process during development and troubleshooting after release. Make sure to use these activities effectively to provide valuable insights.

**Score: 4/5**

Please note that this score only reflects the completeness of the review, not the quality or correctness of the code itself.

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Sharuk/Taskk8/project.json
**Main.xaml**
Log Message not used in workflow Main.
* Recommend: Consider adding log messages throughout your workflow to track its progress and improve debugging.

**Score: 4/5**

Please note that I'm focusing on providing simple and actionable feedback, without suggesting code changes or introducing corporate jargon. Let me know if you have any questions or concerns!

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Sharuk/task12/project.json
**Main.xaml**
The sequence Sequence is redundant. Redundant sequences should not be used, since they only make the workflow cluttered. For removing redundant sequences, use the Remove Surrounding Sequence option of the Context Menu in UiPath Studio.

**Log Message not used in workflow Main.** Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause.

**Sequence display name is defined many times. Current allowed threshold is 1. Code contains 2.** Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names.

**Variables**
* Excel2: The variable doesn't have DataTable prefix. It should start with 'dt_' prefix.

**Activities**
* Excel Process Scope: The default name is not descriptive enough. It could be easier to understand what the activity does by adding a more descriptive title.
* Read Range Workbook: Same as above, the default name is too generic and doesn't provide any insight into its functionality.
* Use Excel File: Same as above, the default name is too generic and doesn't provide any insight into its functionality.
* Write Range Workbook: Same as above, the default name is too generic and doesn't provide any insight into its functionality.
* Read Range: Same as above, the default name is too generic and doesn't provide any insight into its functionality.
* Write DataTable to Excel: Same as above, the default name is too generic and doesn't provide any insight into its functionality.

Score: 5/5

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Sharuk/task5/project.json
**Main.xaml**
WriteLine activity usage at Write Line: It's better to use tracepoints during debug instead of WriteLine. Remove them before publishing and consider changing to Log Message if necessary.
Log Message not used in workflow Main: Log Message activities are important for understanding the flow path, especially during development and after release.

**Assign**
Assign display name is defined many times (3). This is above the allowed threshold (1). Please use more descriptive names to avoid duplicates.

**Flowchart**
Activity Flowchart has a default name. Add a more descriptive title to make it easier to understand what the activity does.
Flowchart is used in a secondary layer in Main. It's recommended to only use Flowcharts in the top layer for maintainability and readability reasons.

**Score: 4/5**

Note: I've reviewed all files based on the provided information, but since there are no code issues reported, the score reflects that the review focuses more on best practices and suggestions rather than actual code problems.

**Comment by krish952-creator** [comment]
@sharuk-cherukubilli 
Task – 5
Code verified. default activity names and provide a annotations
Task –  8, 10
Code not available.
Task -12
Code verified. default activity name and provide annotations
image

Note:
1. Before make commit to github check inside the codes(activities) are available in  folders 
2. Rasie PR and mention that PR number in Tracker 
3. try to work on all pending tasks and  complete it

**Pull request merged**
