### PR TITLE
Task4

### PR DESCRIPTION
**Pull request by karunakar7668**
Find the Leap year and also display the message along with the boolean conditions (flowchart and sequence)

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/karunakar/Task4/project.json
For "NoFile":

1. Please make sure to have an Automation Hub URL defined in the project settings. This is a requirement from your organization.

2. You have included certain dependency packages which are not used. Remove the unused packages UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities and UiPath.UIAutomation.Activities. This will help improve the process execution time.

For "Main.xaml":

1. There are several activities with default or duplicate names. It's best if the activity names give a clear indication of the action being performed. Please make sure to avoid duplication and use more descriptive names.

2. The variable 'year_input' doesn't follow the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*. Please adhere to the naming conventions.

**Scores:**

1. Code completion: 1.5/2 - Some changes are required to adhere to best practices.
2. Execution: 2/2 - No issues found related to code execution.
3. Annotations and comments: 0.5/1 - No comments found in the code. It's best if the crucial parts of the code are commented clearly for future reference and readability.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/karunakar/task5/project.json
Post 1 for ~Main.xaml:

    "Your code is missing log messages. They help you catch and fix errors more easily by letting you understand the flow of your program. Please add them.
    
    You also used flowchart inside ~Main. Flowchart is better placed on top for easier reading and maintaining, so move it to top layer.
    
    I also noticed your 'Assign' has a default name and has been used more than once. Please provide more specific names. Try to reduce the usage to a minimum for simplicity."

Post 2 for Main.xaml:

    "It seems you missed out on using Log Message in your Main.xaml too. They're pretty handy for identifying issues post-release, try to include them more.

Post 3 for NoFile:

    "Your project is missing the Automation Hub URL. To add it, please go to 'Project Settings'.
    
    Additionally, there are unused dependency packages in your code. To speed up your process time, remove unused packages like:
    
    UiPath.Excel.Activities,
    UiPath.Mail.Activities,
    UiPath.Testing.Activities,
    UiPath.UIAutomation.Activities"

Code Completion: 1.5, Execution: 2, Annotations and Comments: 0.5

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/karunakar/Task4/project.json
## NoFile Code Review

**Score:** Code = 1.5, Execution = 2, Annotations = 1

- Your project doesn't have an Automation Hub URL defined. Navigate to "Project Settings" and add the required info.
- Your code uses packages and dependencies it doesn't need, specifically `UiPath.Excel.Activities`, `UiPath.Mail.Activities`, `UiPath.Testing.Activities`, and `UiPath.UIAutomation.Activities`. Get rid of these unused packages to make your process run faster.
  
## Main.xaml Code Review

**Score:** Code = 1, Execution = 2, Annotations = 0.5

- In your code, the names `Assign display name` and `Message Box display name` are present multiple times. Try to give specific and unique names to your activities, it helps in understanding the flow.
- You need to name your variables properly. Your variable `year_input` doesn't follow the set pattern.
- Activities like `Log Message`, `If`, `Assign`, `Message Box`, and `Input Dialog` have a default names. It's good practice to give them descriptive names so we can understand their role in the process easily.

Remember, clean and well-organized code is much easier

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/karunakar/task5/project.json
Score:
- Code Completion: 1.5/2
- Execution: 1.5/2
- Annotations and Comments: 0.5/1

FeedBack:

NoFile:
- Your project doesn't have an Automation Hub URL set. Go to 'Project Settings' in UiPath Studio and add it.
- There are several packages added to your project (UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities) which you are not using. This could make your robot slow. Remove them if you're not using them.

Main.xaml:
- You're not using 'Log Message' throughout your workflow. This can make troubleshooting tough. Add them to get details about execution steps.
- 'WriteLine' is good for debug, but not for production. Use Tracepoints or Log Message instead and ensure to clean before publishing.
- You're using 'Flowchart' within another Flowchart. This gets messy. Stick to one Flowchart in the top layer so it's easier to read.
- The name 'Assign' is used too much. Try to give unique, descriptive names to your activities related to what they do.
- Several activities have default names. Use descriptive names to

**Comment by krish952-creator** [comment]
@karunakar7668 
Task-4
Code verified. Default activity names
 
image

Task-5
Code verified. Default activity names
 
image

**Pull request merged**
