### PR TITLE
task2

### PR DESCRIPTION
**Pull request by Mohdabid161**
Displaying message using log message

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/Nov2023/Abid/task2/project.json
Score:
- Code Completion: 2/2
- Execution: 1.5/2
- Annotations and Comments: 0.5/1

Code Review:

**NoFile**:
- The project doesn't have an Automation Hub URL defined. Go to the "Project Setting" and add missing information.
- You've included UiPath.Excel.Activities and UiPath.Mail.Activities packages. But they're not used in the project. Unloading unused packages helps to speed up process execution.

**Main.xaml**:
- "Log Message" activity has a default name. Giving a more descriptive name helps to understand what exactly the activity does. 

Remember, clean and well-documented code makes it easier for others (and for you in the future) to understand what going on. Always take the time to clean up and document your code.

**Comment by vajrang-b** [comment]
SourceCode/2023/Nov2023/Abid/task2/project.json
Score Card:
- Code Completion: 1.5/2
- Execution: 2/2
- Annotations & Comments: 0.5/1

### Comments:

1. NoFile: 
- It's essential to provide an Automation Hub URL in Project Settings specifically for your organization's requirements. It's not visible here, so add it in. 
- Noticed you have some unnecessary packages - UiPath.Excel.Activities and UiPath.Mail.Activities. If these aren't in use, scrap them. It'll speed up your process execution. 

2. Main.xaml: 
- Add Log Message activities. They're good trackers during development and post-release. Helps tackle errors faster by identifying the source and cause.
- The Input Dialog activity could use a more descriptive name to provide clarity on its function.
- Similarly, give your MessageBox activity a practical name that suits its purpose.

Remember, clean coding is efficient coding.

**Comment by vajrang-b** [comment]
SourceCode/2023/Nov2023/Abid/task2/project.json
The scores are as follows:

- Code Completion: 1.5/2. You've managed to complete most of the task, but there are some areas to improve.
- Execution: 1/2. There are spaces for streamlining the process towards better execution.
- Annotations and Comments: 0.5/1. You've gone far, but we need more descriptions and comments to provide clarity.

Here are a few comments to make your code better:

- You haven't set up a URL in the Automation Hub part of your project settings. Quick fix: go to "Project Settings" and add the missing details.
- You've packed things you're not even using. Packages "UiPath.Excel.Activities" and "UiPath.Mail.Activities" are sitting there for no reason. Neat trick: remove unused packages to make your process run faster and smoother.
- I've noticed a lack of log messages in your Main.xaml. Keep this in mind: logs are your best friends, especially when error messages start popping out. Stick them logs everywhere!
- Some of your activities are nameless. They're lost and confused, give 'em expressive titles! Your future self will thank you for it.
  
And don't forget, the best code is readable

**Comment by vajrang-b** [comment]
SourceCode/2023/Nov2023/Abid/task3/project.json
Based on the code review, here's the feedback:

For the `NoFile`, your organization requires an Automation Hub URL for your project. Please use the 'Project Settings' to enter the necessary information. 

Additionally, the dependency packages UiPath.Excel.Activities and UiPath.Mail.Activities have been included in the project but it appears they are not used anywhere. Such unused packages increase process execution time and should be removed. 

For the `Main.xaml` file, several optimisations can be made. 

The use of the `Log Message` activity is currently missing in the Main workflow. These log messages are crucial not only during the development phase but also post release. They help in understanding the flow path and are extremely useful in identifying the source and cause of any error during the maintenance phase. 

Both the `Input Dialog` and `Message Box` activities are currently named with their default names. If these activities were named more descriptively, it would make it easier to understand their function in the workflow.

Ratings (Out of 2):
- Code Completion: 1.5 (because there are unused packages and missing Automation Hub URL)
- Execution: 1.5 (because of missing log message activity)
- Annotations & Comments: 0.5

**Comment by krish952-creator** [comment]
@Mohdabid161 
Task -1
Code verified. Default activity names.
 
image

Task -2
Addition of two Numbers (based on input dailogebox and Variables) (Addition, Substraction and multiplications)
Code verified. Default activity names and need to complete all operations
image

**Pull request merged**
