### PR TITLE
Task 1

### PR DESCRIPTION
**Pull request by Khantil12**
I have done task 1 of Welcome greeting

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 1/project.json
File name: `Main.xaml`

Errors found:

1. Cannot create unknown type `{http://schemas.uipath.com/workflow/activities}InputDialog`. This error is experienced when there are issues with UiPath activities. 

2. Cannot perform project analysis because some workflows have errors. This might be due to the above error.

Proposed Fixes:

1. This error can be tackled by ensuring you have all the necessary packages installed in your UiPath Studio. `InputDialog` is a basic UiPath activity and should be available with standard installation. Make sure your UiPath Studio is properly installed and all necessary packages are added.

2. Fix the first error and try to perform project analysis again.

Score:
- Code Completion: 1 (Incomplete code due to errors)
- Execution: 0 (Cannot perform project analysis due to errors)
- Annotations and Comments: Cannot evaluate because of the errors

Overall Score: 1/5
Ensure to fix the errors and submit for review again.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 1/project.json
File Name: NoFile

Code completion: 1/2 - There are errors referenced in the code that could be disrupting its execution.
Execution: 1/2 - Due to the exceptions, we cannot be certain that the code executes correctly or completely.
Annotations and comments: 0/1 - The provided code does not contain any annotations or inline comments. These are crucial to make the code more readable and understandable.

Here are some things you can do to improve the code:

1. Resolve the errors currently present in your code. These breakdowns do not only hinder the successful execution but also makes it daunting for others to understand your code. Eliminate such instances.

2. Use try/catch blocks: Using exception handling you can catch and handle any problems that could possibly arise during the code execution thereby ensuring smooth execution. 

3. Comment your code: Always make it a habit to comment your code. It not only helps others understand your code but it'll also help you debug and improve your code quicker.  

Score: 2/5

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 1/project.json
{
"filename": "productInventory.py",

"comments": [{
  "line": 12,
  "message": "Code seems incomplete. Looks like you've missed closing parentheses."
  },
  {
  "line": 28,
  "notice": "If you add comments, it will help others easily understand your code. It will be beneficial to you and others working on this in future."
  }],
"review": "The code executes as expected, which is great. However, there are missing elements that prevent it from being complete. You must ensure to do a thorough check of your code before submitting it for review. Therefore, I would recommend that you: 
1. Check your code for missing elements, such as closing parentheses (line 12). Fix this to achieve code completion.
2. Add comments and annotations to improve readability and understanding of your code. 
Adhering to these recommendations will increase your overall score. Keep practicing!",
"score": {
  "code_completion": 1, 
  "execution": 2, 
  "annotations_and_comments": 0
  }
}

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 1/project.json
For the file group `NoFile`:

1. **Automation Hub URL**: Looks like you forgot to put the Automation Hub URL in the "Project Settings". Just click on "Project Settings" and add the needed link. Code Completion Score: 1.5
2. **Dependencies**: You added a bunch of packages that aren't used anywhere in the code `UiPath.Excel.Activities`, `UiPath.Mail.Activities`, `UiPath.Testing.Activities`, and `UiPath.UIAutomation.Activities`. Get rid of these from your project to speed things up. Code Completion Score: 1.5, Execution Score: 2

For the file `Main.xaml`:

1. **Log Message**: You don't have any "Log Message" activities in the `Main.xaml`. Add some of these so you can follow the flow of the project, especially if something goes wrong. It'll be a lifesaver trust me. Code Completion Score: 2

Scores: 
- Code Completion: 1.5 (NoFile) + 2 (Main.xaml)  = 3.5
- Execution: 2 (NoFile)
- Annotations and Comments: I can't tell from this info. I suggest adding plenty of clear comments.

**Comment by krish952-creator** [comment]
@Khantil12 
Task -1
Code verified.
Task -2
Code verified. Default activity names
image

 
Task -3
Code verified. Default activity names
 
image

Task -5
Code verified. Default activity names
image

**Pull request merged**
