### PR TITLE
Task 34 Completed

### PR DESCRIPTION
**Pull request by Sachinrawal1109**

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Task34/project.json
Based on the review for the UIPATH code, here are the comments per file:

1. NoFile:
- Add missing Automation Hub URL in the Project Settings.
- Clean up by removing the unused UiPath.Mail.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities packages.

2. Substraction.xaml
- Use log messages for debugging and easy maintenance.
- Argument names don't follow the convention, rename 'In_Num1', 'In_Num2', and 'Out_Subs' as per standard.
- Assign activity has default name, consider giving it a fitting title.

3. Addition.xaml
- Use log messages for debugging and easy maintenance.
- Argument names don't follow the convention, rename 'In_Num1', 'In_Num2', and 'Out_Add' as per standard.

4. Main.xaml
- Use log messages for debugging and easy maintenance.
- Remove redundant Dispatcher sequence for simpler workflow.
- Assign 'Add Queue Item' activity a more descriptive name.

5. Performer.xaml
- The flowchart might be in an infinite loop. Check for termination conditions with 'Get Transaction Item from Orchestrator'.
- Variable names 'Out_ResultSub', and 'Out_Result' don't follow the convention. Fix this.

**Comment by krish952-creator** [comment]
@Sachinrawal1109 
Task 34 not available in this pr reopen it again

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Task34/project.json
Code Review:

"Substraction.xaml":
1. Argument names 'In_Num1', 'In_Num2', 'Out_Subs' don't follow the naming pattern "^in_(dt_)?([A-Z]|[a-z])+([0-9])*$". Update the naming to respect convention.

"NoFile": 
1. I did not find 'Main.xaml' and 'Performer.xaml'.
2. Skipping further reviews because of these missing files.

"Addition.xaml":
1. Argument names 'In_Num1', 'In_Num2', 'Out_Add' don't follow the naming pattern "^in_(dt_)?([A-Z]|[a-z])+([0-9])*$". Update the naming to respect convention.

Task Score: 
Code completion: 1 (Missing files. Arguements not in standard format)
Execution: 0 (Missing files)
Annotations and Comments: 0 (Not available from given details).

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/SachinRawal/Task34/project.json
_Subtraction.xaml_
Keep naming constant. You're inconsistent with In_Num1, In_Num2, and Out_Subs. Follow the pattern `^in_(dt_)?([A-Z]|[a-z])+([0-9])*$.`

_NoFile_
Your system can't load Main.xaml and Performer.xaml. They may have errors, double-check those.

_Addition.xaml_
Just like before, keep argument names constant. Check In_Num1, In_Num2, and Out_Add for the correct pattern `^in_(dt_)?([A-Z]|[a-z])+([0-9])*$.`

_Score Criteria_
Code Completion: 1 (Your code has some issues that need fixing, like naming)
Execution: 1 (Your program has failed to run Main.xaml and Performer.xaml)
Annotations and Comments: 1 (Couldn't find any annotations or comments in your codes)

You have a total score of 3 out of 6. You can do better! Try and address the issues I mentioned for better results.

**Pull request merged**
