### PR TITLE
Task

### PR DESCRIPTION
**Pull request by ShashiRPA**

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Shashi/Task18/project.json
### NoFile
- Your project needs an Automation Hub URL as per the organization's requirement. Use "Project Settings" to plug this in.
- I see that the UiPath.Mail.Activities package is included but not used. Remove unneeded packages to speed up the process.
- The same goes for UiPath.Testing.Activities and UiPath.UIAutomation.Activities. Chop them off if there's no use for them.

### Main.xaml
- "Log Message" is not used in the "Main" workflow. Log Messages are handy for understanding the process, especially when things go south. Try to use them.
- You have a DataTable variable that doesn't have a "dt_" prefix. DataTable variable names should always start with "dt_".
- The "Assign", "Build Data Table", "Multiple Assign", and "Add Data Row" activities all have default names. Assigning them descriptive titles can make your code easier to understand.
  
That's it. A few tweaks here and there, and your code will be more readable and efficient. Keep going!

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Shashi/Task20/project.json
Hey,

Just spotted a few hiccups with the file at `C:\\VSTS_BA1\\_work\\1\\s\\SourceCode\\2023\\Sep2023\\Basics\\Shashi\\Task20\\Main.xaml`. I'm getting an issue here with the `ForEachRow`, it looks like it's an unknown type. 

A couple of possible solutions here:
Firstly, double-check the `{http://schemas.uipath.com/workflow/activities}` imported namespace. Maybe there's a typo there, or it should be slightly different. Secondly, it might be a package issue, so ensure that you have installed all the necessary packages for the `ForEachRow`. Try latest `UiPath.System.Activities` and `UiPath.UiAutomation.Activities` versions.
  
Also, fixing this error is key, the project analysis is failing because of these workflow errors. So we can't proceed until it's sorted.

Let me know how it goes after these changes,

Thanks.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Shashi/Task21/project.json
Hey there, I've been looking over your code and have noticed a couple of issues that you'll want to address:

1. When I attempted to load your 'Main.xaml' file located in the path `C:\\VSTS_BA1\\_work\\1\\s\\SourceCode\\2023\\Sep2023\\Basics\\Shashi\\Task21\\`, I ran into an error. It seems you're trying to create a type that doesn't exist: `{http://schemas.uipath.com/workflow/activities}BuildDataTable`. Check if your UiPath version supports this activity or if the package is correctly installed and up-to-date.

Fixing this will help to load your file without errors. Also, ensure you have all the necessary packages installed in your project.

2. Your project could not be analyzed because some workflows contain errors. After you've addressed the error detailed above, run the project again. If there are other errors, UiPath Studio will give you feedback about what's wrong. Carefully read the error message and rectify the issues.

Remember, well-structured and error-free workflows are key to successful execution. Look at each workflow individually, run checks, spot the errors. Fix them one-by-one and keep testing.

Keep

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Shashi/Task22/project.json
For the "NoFile":

1. You need to add an Automation Hub URL to your project settings. It's a rule in this organization.
 
For the package dependencies:

1. Clean up the dependencies. You've loaded packages UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.System.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities, but you're not using them. Kick them out to speed up your process.

For the "Main.xaml" file:

1. Don't forget to use Log Message in your workflow. It's not fancy but it will help you to understand where you are in the flow. Especially when something goes wrong, you'd know where the problem is coming from.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Shashi/Task23/project.json
To all files:
1. Make sure to add your Automation Hub URL to your project settings.
2. Your code has several unused packages like UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities. Remove them to speed up your process.

For the Main.xaml file:
1. Start using Log Message activities. They'll be really handy for figuring out where errors are or which flow paths aren't working.
2. There are too many Message Boxes with the same name. It's hard to tell 'em apart. Use different names.
3. There's a variable named "string_data" that isn't following your naming convention. Fix its name.
4. Several activities like Assign and Message Box are using their default names. Give 'em a title that points out what they're supposed to do; it makes the code easier to understand.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Shashi/Task24/project.json
NoFile:
1. The project lacks an Automation Hub URL. Go to "Project Settings" and add the necessary information.
2. Several packages are part of the project but unused (UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.System.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities). Clean-up is needed, kick out unnecessary packages to speed up the process run time.

Main.xaml:
1. "Log Message" is missing in your workflow. Keep track of your workflow path during development and post-release with Log Messages.
2. There are a couple of "Write Line" usages. During debugging, use tracepoints instead. Delete them before publishing. If needed for debugging, change WriteLine to Log Message.
3. Non-unique "Assign" and "Write Line" display names are present. Duplicates can be confusing, make each activity name unique and meaningful.
4. The variable "string_value" doesn't match the naming convention. Adjust name as per the standard practice.
5. Some activities like "Assign" and "Write Line" have default names. A more descriptive name would help folks understand its functionality better.

**Comment by krish952-creator** [comment]
@ShashiRPA 
Task -18
Code Verified. Default Activity names
 
image

Task -20
Code Verified. Default Activity names
 
image

Task -21
Find the temperature of few cities and print the results into Excel
(But you did ) task-22 on their(Read the excel (consists of Lower Letters), and type into website (Vajrang.org - Uppercase Task) (by using Add data row add the data into the excel))
Task -22
Code Verified. Default Activity names and errors 
 
image
Task -23
Code Verified. Default Activity names
 
image

Task -24
Code Verified. Default Activity names
image

**Pull request merged**
