### PR TITLE
Task 12 , 14 Completed

### PR DESCRIPTION
**Pull request by Nazeernrb**
Task 12, 14 Completed

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nazeer/Task15/project.json
Your code review score for the criteria: 

1. Code Completion: 2
2. Execution: 1.5
3. Annotations and Comments: 1

Here's how to improve:

NoFile:
- Add the Automation Hub URL to the 'Project Settings'.
- Unused packages: UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.MicrosoftOffice365.Activities, UiPath.System.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities. It's better to remove them, they're slowing down your process.

Main.xaml:
- Missing logs in 'Main' workflow. Logs are key for debugging, maintenance, and error tracking. Don't forget to include them.

Please revise and resubmit your code.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nazeer/Task15/project.json
Score:

Code Completion: 1.5/2 - The code seems largely finished, but there seems to be a missing Automation Hub URL which needs to be included.

Execution: 1.5/2 - There are unused dependencies like UiPath.Testing.Activities and UiPath.UIAutomation.Activities. These need to be deleted for proper and efficient execution. 

Annotations and Comments: 0.5/1 - WriteLine activity that is used at Result Write Line could be replaced with tracepoints or Log Message. This would improve the clarity of the code and aid in debugging.

Please make the appropriate changes based on the feedback provided.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nazeer/Task16/project.json
Code Completion: 1.5
The code seems to be missing some crucial elements like the Automation Hub URL. Additionally, unused dependency packages like UiPath.Testing.Activities and UiPath.UIAutomation.Activities need to be cleaned up.

Execution: 1.5
While there don't seem to be errors that would prevent code execution, the absence of an Automation Hub URL means that the project's integration is not optimal. Removing unused packages also aids in more efficient execution.

Annotations and comments: 0.5
From the provided information, no note on annotations or comments is included. So, it's difficult to assess this criteria accurately.

Recommendations for improvement:

- Under "Project Settings", add the Automation Hub URL to ensure all parts of your project are properly linked.
- Get rid of packages that are not in use. This way, your process will run faster and smoother.
- Make sure to include relevant notes and comments in your code. It helps others understand what your logic behind certain pieces of code.
 
Overall score: 3.5/6

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nazeer/Task17/project.json
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "You've missed out the Automation Hub URL. Go to 'Project Settings' and drop in the required URL. "
                   },
                   {
                       "Dependency package UiPath.UIAutomation.Activities is not used.":  "There's an unused Dependency package, UiPath.UIAutomation.Activities. Uninstall unnecessary packages. This will speed things up a notch."
                   }
               ],

   "Score": "Code Completion: 1.5, Execution: 1.5, Annotations and Comments: 0.5"
}

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nazeer/Task15/project.json
Your score is below.

Code Completion: 1 - You missed the required Automation Hub URL, and it would be better if unused dependencies are not included in your project.

Execution: 2 - There are no issues that affect execution.

Annotations and Comments: 0.5 - The WriteLine activity can be replaced with tracepoints during debug and should be removed before publishing.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nazeer/Task16/project.json
Code Completion: 1/2 - The project is missing crucial information and unused dependency packages are included. To get full point make sure to meet all the requirements.

Execution: 2/2 - There doesn't seem to be any issues with the execution of the code.

Annotations and Comments: 1/1 - The code is self-explanatory, no need for additional comments.

Overall Score: 4/5 - A good effort, but there's a need for some tidying up in terms of project settings and package use. Remember, neat and efficient is the way to go.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nazeer/Task17/project.json
File: NoFile

Review Comment:

1. Your project is required to have an Automation Hub URL defined according to your organization's rules. Go to the "Project Settings" and add this missing information. This would ensure your project complies with organizational rules.

Score: Code Completion 1.5, Execution 2 

2. I noticed that the dependency package UiPath.UIAutomation.Activities is not used in your code. Delete unused packages which can improve your process execution time, this would lead to a cleaner and more efficient code.

Score: Code Completion 2, Execution 2, annotations and comments 0.5 

Please make these changes and commit again.

**Comment by krish952-creator** [comment]
@Nazeernrb 
Task-12
Task not available in this pr. check it
Task-14
Task not available in this pr. check it
Task -15
Code verified.
Task -16
Code verified.
Task -17
Code verified.

**Pull request merged**
