### PR TITLE
Task_10 update and Task_21

### PR DESCRIPTION
**Pull request by peddyshailaja**
added Task 21 and updated existing Task_10

### CODE REVIEW

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   }
               ]
}

**Comment by vajrang-b** [comment]
{
    "Main.xaml":  [
                      {
                          "Variable dtTemp doesn\u0027t have DataTable prefix.":  "DataTable Variable should start with a dt_ prefix. "
                      }
                  ],
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   }
               ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   }
               ]
}

**Comment by vajrang-b** [comment]
{
    "Main.xaml":  [
                      {
                          "Variable dtPerson doesn\u0027t have DataTable prefix.":  "DataTable Variable should start with a dt_ prefix. "
                      }
                  ],
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   }
               ]
}

**Comment by vajrang-b** [comment]
{
    "Main.xaml":  [
                      {
                          "Variable dtTemp doesn\u0027t have DataTable prefix.":  "DataTable Variable should start with a dt_ prefix. "
                      }
                  ],
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   }
               ]
}

**Comment by krish952-creator** [comment]
@peddyshailaja 
Task -10
Code verified.
Task -21
Code verified. 
provide input file with code in necessary tasks.

**Pull request merged**
