### PR TITLE
Completed Task6, Task7, Task8

### PR DESCRIPTION
**Pull request by MadhuKumar45**
Completed Task6, Task7, Task8

### CODE REVIEW

**Comment by krish952-creator** [comment]
@MadhuKumar45 
Task -6
 Code verified.
Task -7
 Code verified.
Task -8
 Code verified.
This pull request has conflicts; please refrain from accessing any other files on GitHub. Consequently, I am unable to merge it at this time.

**Comment by MadhuKumar45** [comment]
Completed Task13, Task14, Task15, Task16, Task17

**Comment by MadhuKumar45** [comment]
Completed Task13, Task14, Task15, Task16, Task17

**Comment by krish952-creator** [comment]
@MadhuKumar45 
This pull request has conflicts; please refrain from accessing any other persons files on GitHub. Consequently, I am unable to merge it at this time.

Task -13
Code verified.
Task -14
Code verified. Execution error check the filter activity 
 
image

Task -15
Code verified.
Task -16
Code verified.
Task -17
Code verified.

**Pull request closed without merging**
