### PR TITLE
Task 4,5,6

### PR DESCRIPTION
**Pull request by Sudheer2331**
Task 04,05,06 completed with all the parameters

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Sudheer Devabattula/Task04/project.json
Group: Main.xaml
- Log Message not used in workflow Main: It's crucial to use Log Message activities for understanding the flow path, especially during maintenance or when an error occurs. Add them in.
- Sequence LeapYear is redundant: There's no need for redundant sequences; they only make the workflow cluttered. Get rid of it. Use the "Remove Surrounding Sequence" option in UiPath Studio.
- Message Box display name is defined many times: Try to avoid duplicate names, mate. It helps in getting a clear understanding of distinct activities. You've used two where the threshold is one.
- Activity Message Box has a default name: Can you add a more descriptive title to these? It'll be way easier to understand what the activity does.

Group: NoFile
- Your organization requires your project to have an Automation Hub URL defined: Can you please add the missing information in the "Project Settings".

Scores:
- Code Completion: 1.5
- Execution: 1.5
- Annotations and Comments: 0.5

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Sudheer Devabattula/Task05/project.json
# Main.xaml
- **Code Completion (1/2)**: There's a redundant sequence titled "Add two different Variables". This can clutter the flow, making it less efficient and harder to read. You can remove redundant sequences via the Remove Surrounding Sequence option in UiPath Studio's context menu. 

# NoFile
- **Code Completion (1/2)**: Your project is currently missing an Automation Hub URL, which is required by your organization. You can add this information through the "Project Settings". 

# Execution & Annotations and comments
As these are not mentioned in your report, I will not be able to provide a score.

So, overall, the project is 50% there. You've made some progress, but there's room for improvement.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Sudheer Devabattula/Task07/project.json
Main.xaml:
- Score: Code completion 1, Execution 2, annotations and comments 0. Total: 3/5.

Comments:
1. Log Message activity is missing in your Main workflow. Use it to track activities during development and maintenance. It will help you in identifying the source of error.
2. There exists a needless sequence "Displayvalues". This makes the workflow cluttered. Remove it using the 'Remove Surrounding Sequence' option from UiPath Studio's context menu.

NoFile:
- Score: Code completion 0, Execution 0, annotations and comments 0. Total: 0/5

Comments:
1. Your project doesn't have an Automation Hub URL, it's a requirement in our organization. Add the URL using the 'Project Settings' option.

**Comment by krish952-creator** [comment]
@Sudheer2331 
Task -4
Code verified. Default activity names 
 
image

Task -5
Code verified.
Task -6
Code verified. Default activity names 
 
image

Task -7
Code verified.
Task -8
Code verified.
Task -9
Code verified.

**Pull request merged**
