### PR TITLE
task3

### PR DESCRIPTION
**Pull request by Pavankumar1411**

### CODE REVIEW

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "MessageBox display name is defined many times. Current allowed threshold is 1. Code contains 7.":  "Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names. "
                      },
                      {
                          "Activity Input Dialog has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Switch has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "MessageBox display name is defined many times. Current allowed threshold is 1. Code contains 7.":  "Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names. "
                      },
                      {
                          "Activity Switch has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Input Dialog has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "Flowchart Task_11 is used in a secondary layer in Main.":  "Flowchart should only be used in top layer for maintainability and readability reasons. "
                      },
                      {
                          "Variable Fruit_name does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$|_out_[A-Za-z][A-Za-z0-9_]*$":  "Make sure all the variables follow the naming convention. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "MessageBox display name is defined many times. Current allowed threshold is 1. Code contains 7.":  "Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names. "
                      },
                      {
                          "Activity Switch has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Input Dialog has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "Flowchart Task_11 is used in a secondary layer in Main.":  "Flowchart should only be used in top layer for maintainability and readability reasons. "
                      },
                      {
                          "Variable Fruit_name does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$|_out_[A-Za-z][A-Za-z0-9_]*$":  "Make sure all the variables follow the naming convention. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "MessageBox display name is defined many times. Current allowed threshold is 1. Code contains 7.":  "Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names. "
                      },
                      {
                          "Activity Switch has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Input Dialog has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "Flowchart Task_11 is used in a secondary layer in Main.":  "Flowchart should only be used in top layer for maintainability and readability reasons. "
                      },
                      {
                          "Variable Fruit_name does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$|_out_[A-Za-z][A-Za-z0-9_]*$":  "Make sure all the variables follow the naming convention. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      }
                  ]
}

**Comment by krish952-creator** [comment]
@Pavankumar1411 
To merge a code on GitHub, please ensure that the changes have been reviewed and approved. Once merged, update the tracker with the pull request (PR) number in the respective tasks in Excel

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "MessageBox display name is defined many times. Current allowed threshold is 1. Code contains 7.":  "Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names. "
                      },
                      {
                          "Activity Input Dialog has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Switch has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "Flowchart Task_11 is used in a secondary layer in Main.":  "Flowchart should only be used in top layer for maintainability and readability reasons. "
                      },
                      {
                          "Variable Fruit_name does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$|_out_[A-Za-z][A-Za-z0-9_]*$":  "Make sure all the variables follow the naming convention. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "MessageBox display name is defined many times. Current allowed threshold is 1. Code contains 7.":  "Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names. "
                      },
                      {
                          "Activity Switch has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Input Dialog has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "Flowchart Task_11 is used in a secondary layer in Main.":  "Flowchart should only be used in top layer for maintainability and readability reasons. "
                      },
                      {
                          "Variable Fruit_name does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$|_out_[A-Za-z][A-Za-z0-9_]*$":  "Make sure all the variables follow the naming convention. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "MessageBox display name is defined many times. Current allowed threshold is 1. Code contains 7.":  "Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names. "
                      },
                      {
                          "Activity Input Dialog has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Switch has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "Flowchart Task_11 is used in a secondary layer in Main.":  "Flowchart should only be used in top layer for maintainability and readability reasons. "
                      },
                      {
                          "Variable Fruit_name does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$|_out_[A-Za-z][A-Za-z0-9_]*$":  "Make sure all the variables follow the naming convention. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "MessageBox display name is defined many times. Current allowed threshold is 1. Code contains 7.":  "Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names. "
                      },
                      {
                          "Activity Input Dialog has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Switch has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "Flowchart Task_11 is used in a secondary layer in Main.":  "Flowchart should only be used in top layer for maintainability and readability reasons. "
                      },
                      {
                          "Variable Fruit_name does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$|_out_[A-Za-z][A-Za-z0-9_]*$":  "Make sure all the variables follow the naming convention. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "MessageBox display name is defined many times. Current allowed threshold is 1. Code contains 7.":  "Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names. "
                      },
                      {
                          "Activity Switch has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Input Dialog has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "Flowchart Task_11 is used in a secondary layer in Main.":  "Flowchart should only be used in top layer for maintainability and readability reasons. "
                      },
                      {
                          "Variable Fruit_name does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$|_out_[A-Za-z][A-Za-z0-9_]*$":  "Make sure all the variables follow the naming convention. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "MessageBox display name is defined many times. Current allowed threshold is 1. Code contains 7.":  "Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names. "
                      },
                      {
                          "Activity Input Dialog has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Switch has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "Flowchart Task_11 is used in a secondary layer in Main.":  "Flowchart should only be used in top layer for maintainability and readability reasons. "
                      },
                      {
                          "Variable Fruit_name does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$|_out_[A-Za-z][A-Za-z0-9_]*$":  "Make sure all the variables follow the naming convention. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "Write Range Workbook display name is defined many times. Current allowed threshold is 1. Code contains 2.":  "Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names. "
                      },
                      {
                          "Variable resulted doesn\u0027t have DataTable prefix.":  "DataTable Variable should start with a dt_ prefix. "
                      }
                  ]
}

**Comment by krish952-creator** [comment]
@Pavankumar1411 
Task -4
Code verified. Default activity names
image
 
Task -5
Code verified. Default activity names
image
 
Task -6
Code verified. Default activity names 
image
Task -10
Code verified. Default activity names
 
image
Task -11
Code verified.

**Pull request merged**
