### PR TITLE
Task22

### PR DESCRIPTION
**Pull request by Supriyar6040**
Extracted the information from vajrang.org and stored into an Excel sheet

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Supriya/Task22/project.json
**Main.xaml**
WriteLine activity usage at Write result.
Write Line activity can be replaced with tracepoints during debug. They should be removed before publishing. Consider also changing WriteLine to Log Message if it is really needed for debugging purposes.

**Dependency package UiPath.Mail.Activities is not used.**
Remove unused packages in order to improve process execution time.

**Dependency package UiPath.Testing.Activities is not used.**
Remove unused packages in order to improve process execution time.

**Score: 4/5**

Please note that the above points are suggestions for improvement and do not include any code changes.

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Supriya/Task22/project.json
**Main.xaml**

* The `WriteLine` activity usage at `Write result` seems unnecessary.
	+ It can be replaced with tracepoints during debug sessions.
	+ This will help in removing unused activities and improving process execution time.
* Consider changing `WriteLine` to `Log Message` if it's really needed for debugging purposes.

**Score: 4/5**

No further issues found.

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Supriya/Task23/project.json
**main.xaml**
Activity Log Message should have a more descriptive title to make it easier to understand what the activity does.

**score: 5/5**

**dependencies.xaml**
- UiPath.Excel.Activities (not used) - Remove unused packages to improve process execution time.
- UiPath.Mail.Activities (not used) - Remove unused packages to improve process execution time.
- UiPath.Testing.Activities (not used) - Remove unused packages to improve process execution time.
- UiPath.UIAutomation.Activities (not used) - Remove unused packages to improve process execution time.

**score: 5/5**

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Supriya/Task22/project.json
**Main.xaml**
- The `WriteLine` activity usage at `Write result` can be replaced with tracepoints during debug. These should be removed before publishing.
- Consider changing `WriteLine` to `Log Message` if it's really needed for debugging purposes.

**Score: 5/5**

Please note that I will only provide review comments in this format.

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Supriya/Task23/project.json
```
**File: NoFile**
NoFile: Your organization requires your project to have an Automation Hub URL defined.
To fix this, please go to Project Settings and add the missing information.

**File: Main.xaml**
Main. xaml: Activity Log Message has a default name.
Consider adding a more descriptive title to make it easier to understand what the activity does.

**Score: 4/5**
```

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Supriya/Task24/project.json
**Main.xaml**

* The `WriteLine` activities are used to display input and output. This can be replaced with tracepoints during debug, which should be removed before publishing.
* Consider changing these `WriteLine` activities to `Log Message` if they're really needed for debugging purposes.

**Score: 4/5**

---

**NoFile**

* The organization requires an Automation Hub URL defined in the project settings. Please add this information to improve process execution time and ensure compliance with organizational requirements.

**Score: 0/5** (not applicable, as there is no file)

---

**Dependency packages (UiPath.Excel.Activities, UiPath.Mail.Activities, etc.)**

* These dependency packages are not used in the code. Remove unused packages to improve process execution time.
* This can also help reduce unnecessary dependencies and make the code more efficient.

**Score: 4/5**

---

**Variable Str_Replace**

* The variable does not respect the set pattern `^(dt_)?(A-Z|a-z)+(0-9)*$|_out_A-Za-zA-Z0-9*$`. Make sure all variables follow this naming convention.
* This helps maintain consistency and makes it easier to read and understand the code.

**Score: 4/5**

---

**Total Score: 12/15**

Please address these issues to improve the code quality, maintainability, and performance.

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Supriya/Task22/project.json
Here are the code reviews grouped by file name:

**Main.xaml**

* The `WriteLine` activity usage at `Write result` could be replaced with tracepoints during debug. They should be removed before publishing.
* Consider changing `WriteLine` to `Log Message` if it's really needed for debugging purposes.

**Score: 4/5**

Let me know if you have any further questions or concerns!

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Supriya/Task23/project.json
**Main.xaml**
Activity Log Message has a default name: Check if it could be easier to understand what the activity does by adding a more descriptive title.

**Score:** 5/5

**General Suggestion:** Use meaningful names for your activities and variables to improve code readability.

**Dependency packages:**
* Dependency package UiPath.Excel.Activities is not used.: Remove unused packages in order to improve process execution time.
* Dependency package UiPath.Mail.Activities is not used.: Remove unused packages in order to improve process execution time.
* Dependency package UiPath.Testing.Activities is not used.: Remove unused packages in order to improve process execution time.
* Dependency package UiPath.UIAutomation.Activities is not used.: Remove unused packages in order to improve process execution time.

**Score:** 5/5

**NoFile:**
Your organization requires your project to have an Automation Hub URL defined.: Use Project Settings to add the missing information.

**Score:** 5/5

**Total Score:** 15/15

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Supriya/Task24/project.json
**Main.xaml**
The `WriteLine` activities are used to display input and output. This is not recommended as it can be replaced with tracepoints during debug. Consider removing them before publishing.

**NoFile**
An Automation Hub URL is missing in the project settings. Please add this information to improve the process execution time.

**Dependencies**

* **UiPath.Excel.Activities**: Unused package. Remove it to improve process execution time.
* **UiPath.Mail.Activities**: Unused package. Remove it to improve process execution time.
* **UiPath.Testing.Activities**: Unused package. Remove it to improve process execution time.
* **UiPath.UIAutomation.Activities**: Unused package. Remove it to improve process execution time.

**Variable**
The `Str_Replace` variable does not respect the set pattern. Make sure all variables follow the naming convention.

Score: 4/5

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Supriya/Task26/project.json
**Main.xaml**
The `Log Message` activity is not used in the workflow `Main`. This makes it difficult to understand the flow path of the process and identify the source and cause of any errors.
Please add log messages throughout the workflow to help with maintenance and debugging.

**Message Box display name**
The code contains 5 duplicate names for message box displays. It's better to have unique names that clearly indicate their purpose. Please rename them to avoid confusion.

**Activity State Machine**
The default name for the `Activity State Machine` is not very descriptive. Please add a more informative title to make it easier to understand what this activity does.

**Activity Assign, Input Dialog, and Message Box**
All of these activities have default names that could be improved. Please consider adding more descriptive titles to make their purposes clearer.

**Score: 4/5**

(Note: I've grouped the comments by file name as per your request, and provided a score at the end. The scores are out of 5 points for complete information.)

**Comment by krish952-creator** [comment]
@Supriyar6040 
Task – 22
Code verified.
Task – 23
Code verified.
Task – 24
Code verified.
Task – 26
Code verified.

**Pull request merged**
