### PR TITLE
Task 10 & Task 11

### PR DESCRIPTION
**Pull request by shakeelabdull**
Compiling Task 10 & Task 11 together along with the updates for task6

### CODE REVIEW

**Comment by vajrang-b** [comment]
{
    "Task 10.xaml":  [
                         {
                             "Variable str_userinput does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$|_out_[A-Za-z][A-Za-z0-9_]*$":  "Make sure all the variables follow the naming convention. "
                         },
                         {
                             "Activity Log Message has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                         }
                     ],
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Process does not define a main entry point.":  "Fix the project.json file to point to the entry/main workflow. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ]
}

**Comment by vajrang-b** [comment]
{
    "Task 10.xaml":  [
                         {
                             "Variable Str_userinput does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$|_out_[A-Za-z][A-Za-z0-9_]*$":  "Make sure all the variables follow the naming convention. "
                         }
                     ],
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Process does not define a main entry point.":  "Fix the project.json file to point to the entry/main workflow. "
                   }
               ]
}

**Comment by vajrang-b** [comment]
{
    "Task 11.xaml":  [
                         {
                             "Flowchart Fruits/Vegetables flowchart is used in a secondary layer in Task 11.":  "Flowchart should only be used in top layer for maintainability and readability reasons. "
                         },
                         {
                             "MessageBox display name is defined many times. Current allowed threshold is 1. Code contains 7.":  "Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names. "
                         },
                         {
                             "Variable Str_userinput does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$|_out_[A-Za-z][A-Za-z0-9_]*$":  "Make sure all the variables follow the naming convention. "
                         }
                     ],
    "NoFile":  [
                   {
                       "Process does not define a main entry point.":  "Fix the project.json file to point to the entry/main workflow. "
                   },
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   }
               ]
}

**Comment by vajrang-b** [comment]
{
    "Task 10.xaml":  [
                         {
                             "Variable Str_userinput does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$|_out_[A-Za-z][A-Za-z0-9_]*$":  "Make sure all the variables follow the naming convention. "
                         }
                     ],
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Process does not define a main entry point.":  "Fix the project.json file to point to the entry/main workflow. "
                   }
               ]
}

**Comment by vajrang-b** [comment]
{
    "Task 11.xaml":  [
                         {
                             "Flowchart Fruits/Vegetables flowchart is used in a secondary layer in Task 11.":  "Flowchart should only be used in top layer for maintainability and readability reasons. "
                         },
                         {
                             "MessageBox display name is defined many times. Current allowed threshold is 1. Code contains 7.":  "Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names. "
                         },
                         {
                             "Variable Str_userinput does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$|_out_[A-Za-z][A-Za-z0-9_]*$":  "Make sure all the variables follow the naming convention. "
                         }
                     ],
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Process does not define a main entry point.":  "Fix the project.json file to point to the entry/main workflow. "
                   }
               ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   }
               ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   }
               ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   }
               ]
}

**Comment by krish952-creator** [comment]
@shakeelabdull 
Task -6
Changes verified.(update the tracker with the pull request (PR) number in the respective tasks in Excel)
Task -10
Code verified.
Task -11
Code verified.

**Pull request merged**
