### PR TITLE
Math Operations

### PR DESCRIPTION
**Pull request by Nihar-11**
Sample Math Operations demo BOT

### CODE REVIEW

**Comment by vajrang-b** [comment]
An expert need to review your code and it will be done before next sunrise :)

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nihar/Task2/project.json
Hey there,

Seems like we have a couple of issues with the workflow you've shared. Here they are:

1. Can't load the file "Main.xaml" in Task2. It's tripping on an unknown type '{http://schemas.uipath.com/workflow/activities}InputDialog'. Please make sure you've all packages installed right or if you're using custom activities, they are correctly imported.

2. Also, the whole project analysis is having a tough time because of errors in some workflows. Clean those up before pushing, so we can get a smooth analysis.

Hope this helps. Keep 'em coming clean! Remember, a minute spent in code review saves ten in debugging!

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nihar/Task_3/project.json
Hi, it seems you're having trouble with `Main.xaml`. The system cannot create an unknown type `{http://schemas.uipath.com/workflow/activities}WriteTextFile`.

Double-check the file's syntax. A missing or incorrect package might also be an issue. Ensure to import or update all the required packages for the `WriteTextFile` activity.

Secondly, your project analysis seems stuck due to these workflow errors. Fix the errors and try running the analyzer again. Hopefully, this should put you back on track. Keep trying!

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nihar/Task2/project.json
Hey there,

There seems to be an issue with the file `Main.xaml` in the directory `C:\\VSTS_BA1\\_work\\1\\s\\SourceCode\\2023\\Oct2023\\Basics\\Nihar\\Task2\\`.

The error message states "Cannot create unknown type '{http://schemas.uipath.com/workflow/activities}InputDialog'. This typically occurs when the UiPath version in use does not support the activity. 

Make sure to check if the UiPath version you're using supports InputDialog activity. If not, you might need to update UiPath or find an alternative activity that accomplishes the same thing. 

The second problem is the project cannot be analyzed because of errors in some workflows. This means that you can't get full insights about the entire project unless errors are fixed. 

Find those workflows, correct the errors and rerun the analysis. This will help in getting a clear picture of the project. 

Hope this helps!

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nihar/Task_3/project.json
Hey there,

I stumbled upon an issue with Main.xaml in the Task_3. It seems like it's attempting to create an unknown type '{http://schemas.uipath.com/workflow/activities}WriteTextFile'. This could be due to a missing or corrupted package where this activity is defined. 

Double check your project dependencies, ensure the proper packages are installed and their version is correct, then try again.

Additionally, there seems to be a problem with project analysis because of some workflow errors. You need to resolve all the workflow errors first before any analysis can be done. 

Hope this helps. Let me know if you require further assistance. 

Keep coding!

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nihar/Task2/project.json
File: Main.xaml

1. Looks like the file is using an unknown type "{http://schemas.uipath.com/workflow/activities}InputDialog". UIPath can't create unknown types. That's why your code failed to load.  

   Suggestion: You need to know what type to use. Make sure you're including the right packages or libraries for your code to use the types you specified.

2. The code in your repository is throwing errors. We cannot analyze your project because of this.

   Suggestion: First, you need to fix those errors before we can get into any deeper level of code review. Use a Robot process to debug and identify the errors.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nihar/Task_3/project.json
Comment on Main.xaml:

There seems to be a loading issue with the 'WriteTextFile' activity here. It's likely because the activity doesn't exist or is incorrectly referenced. 

Try this: Ensure you have the correct namespaces imported and that the activity is installed. If you still face problems, try reinstalling the UiPath.System.Activities package and reference it again. 

Side note: Your UIPath project analysis is failing due to errors in your workflows. Review them one by one and rectify any issues you come across before running the analysis. This will help keep your project bug free. 

Keep coding!

**Comment by krish952-creator** [comment]
@Nihar-11 
Update tracker with PR number in respective tasks
Task -1
Code verified. Default activity names 
 
image

Task -2
Code verified. Default activity names 
 
image

Task -3
Code verified. Default activity names 
 
image

**Pull request merged**
