### PR TITLE
task 3, task 4, task 12, task 27 to task 30

### PR DESCRIPTION
**Pull request by hasini94D**

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2024/Basics-April2024/hasini/task 12/project.json

Hello! As an UiPath code reviewer, I've reviewed your PR and found some areas that need improvement. Here are my findings:

1. NoFile: Your project requires an Automation Hub URL to be defined in Project Settings. Please add the necessary information to complete the setup.
2. Main.xaml: You have a Log Message activity without any usage in your workflow. Using Log Messages is crucial for understanding the workflow's flow path and identifying errors quickly. Please consider adding a Log Message activity wherever it's needed.
3. Multiple instances of the same name in Do display name: The allowed threshold for duplicate names is 1. Renaming activities with similar names can make your code more readable. Please avoid using identical names for different activities.
4. Variable result doesn't have a DataTable prefix: Make sure to start DataTable variables with dt_. This will help identify them easily in the workflow.
5. Activity Comment Out has a default name: Consider adding a more descriptive title to the activity to explain its purpose. This will make your code more readable and easier to maintain.

Based on these findings, I'll give you a total score of 3 out of 5. Please address these issues before the PR can be approved.

**Comment by vajrang-b** [comment]
SourceCode/2024/Basics-April2024/hasini/task 29/project.json
Alright, I'll do my best to review your code as an UiPath Code Reviewer! Here are my notes:

File: NoFile.xaml
Score: 1/5

* Your organization requires your project to have an Automation Hub URL defined. Please add the missing information in Project Settings.

File: Main.xaml
Score: 2/5

* Log Message not used in workflow Main. Using Log Message activities is important both during development and after release, as they help understand the flow path and identify errors easily.
* Current allowed threshold for activity names is 1. Please avoid duplicate names.

File: Read Range Workbook display name is defined many times. Score: 2/5

* Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names.

File: Variable result doesn't have DataTable prefix. Score: 1/5

* DataTable Variable should start with a dt_ prefix.

File: Activity Kill Process has a default name. Score: 2/5

* Check if it could be easier to understand what the activity does by adding a more descriptive title.

File: Activity Try Catch has a default name. Score: 2/5

* Check if it could be easier to understand what the activity does by adding a more descriptive title.

File: Activity Retry Scope has a default name. Score: 2/5

* Check if it could be easier to understand what the activity does by adding a more descriptive title.

Total score: 8/5

**Comment by vajrang-b** [comment]
SourceCode/2024/Basics-April2024/hasini/task 30/project.json
Hi there! As an UIPath code reviewer, I've reviewed your PR and here are my findings:

1. NoFile: You're missing an Automation Hub URL definition in your project settings. Please add it to ensure proper functioning of your project.
2. Main.xaml: You have Log Messages that are not being used in your workflow. It's important to use Log Messages during development and after release to understand the flow path and identify errors quickly. Try to avoid duplicate names for activity names, as they should give a clear indication of how they're being used.
3. Activity For Each Row in Data Table: You have a default name for this activity that could be more descriptive. Can you provide a more detailed title to help understand what the activity does?
4. Activity If: Similar to the previous point, the default name for this activity could be more informative. Please consider adding a more descriptive title to make it easier to understand its purpose.
5. Activity Message Box: You have a default name for this activity that could be more descriptive. Can you provide a more detailed title to help understand what the activity does?
6. Activity Throw: The default name for this activity could also be more informative. Please consider adding a more descriptive title to make it easier to understand its purpose.

Based on these findings, I'll give your PR a score of 3 out of 5. Please address the issues I've mentioned to improve the code quality and earn a higher score in the future.

**Comment by hasini94D** [comment]
Hi vajrang
    Thanks for reviewing and
     I understand every point,& I will do corrections,  but I don't know
about Hub URL.
     Thanks.

**Comment by krish952-creator** [comment]
@hasini94D 
Task -3
Changes  verified.
Task -4
Changes verified.
Task -12
Code verified.
Task -27
Code verified.
Task -28
Code verified.
Task -29
Code verified.
Task -30
Code verified.

**Pull request merged**
