### PR TITLE
Task 28, Task 29, Task 30, Task 31, Task 32, Task 33 and Task 34

### PR DESCRIPTION
**Pull request by Bhimendhar**

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2024/Basics-April2024/Bhimendhar/Task 29/project.json
**Main.xaml**
```
Log Message not used in workflow Main.
Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause.

Sequence Action is empty. Remove empty sequences because they can clutter the workflow.
```

**Read Range Workbook**
```
Read Range Workbook display name is defined many times. Current allowed threshold is 1. Code contains 2 names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names.
```

**Variables**
```
Variable Result doesn't have DataTable prefix. DataTable Variable should start with a dt_ prefix.
```

**Try Catch and Retry Scope**
```
Activity Try Catch has a default name. Check if it could be easier to understand what the activity does by adding a more descriptive title.

Activity Retry Scope has a default name. Check if it could be easier to understand what the activity does by adding a more descriptive title.

Activity Kill Process has a default name. Check if it could be easier to understand what the activity does by adding a more descriptive title.
```

**Score: 5/5**

**Comment by vajrang-b** [comment]
SourceCode/2024/Basics-April2024/Bhimendhar/Task 30/project.json
Here are my code review comments for the PR:

**Main.xaml**
The `Log Message` activities are not used in the workflow, which is unusual. In most cases, these activities help with debugging and understanding the flow of your automation. Make sure to use them during development to get a better understanding of what's happening.

**NoFile: Automation Hub URL**
Add an Automation Hub URL to your project settings. This is required by your organization, so please make sure to do this before merging the PR.

**dtResult Variable**
The variable `Result` should start with `dt_` because it's a data table variable. Rename it to something like `dt_Result`.

**ForEach Row in Data Table**
Rename the activity to something more descriptive, like "Process Each Row in Order Data". This will make it easier for others (and yourself!) to understand what this activity does.

**If-Then Condition**
Rename the activity to something more descriptive, like "Check If Customer Has Paid". This will make it easier for others (and yourself!) to understand what this activity does.

**Message Box**
You have multiple message boxes with default names. Rename them to something more descriptive, like "Show Error Message" or "Display Success Message". This will make it easier for others (and yourself!) to understand what each message box is used for.

**Throw Activity**
Rename the activity to something more descriptive, like "Handle Exception". This will make it easier for others (and yourself!) to understand what this activity does.

Overall Score: 5/5

Please address these comments and I'll be happy to merge the PR.

**Comment by vajrang-b** [comment]
SourceCode/2024/Basics-April2024/Bhimendhar/Task 31/project.json
Here are my comments:

**Main.xaml**
The Log Message activity is not used in this workflow. It's important to use these activities during development and after release to understand the flow path, which makes maintenance easier and helps identify error sources.

**NoFile**
The project requires an Automation Hub URL defined. To fix this, please go to Project Settings and add the missing information.

**Comment by vajrang-b** [comment]
SourceCode/2024/Basics-April2024/Bhimendhar/Task 32/project.json
Here's my review:

**Main.xaml**
> The workflow doesn't have any log messages, which makes it harder to understand during development and after release.
Add some log messages throughout the workflow to make it easier to debug and maintain.

**dt_Build_dt**
> The variable name should start with "dt_" to follow the standard naming convention for DataTable variables.
Rename it to something like `dt_Build_Dates`.

**dt_Build_dt**
> The variable name doesn't follow the set pattern. Make sure all variables have a prefix of "dt_" or "_out" and match the specified pattern.
Rename it again to something that follows the pattern, such as `dt_Build_Date_Stamp`.

**Add Data Row Activity**
> The activity has a default name. Try to make it more descriptive by giving it a title that explains what the activity does.

Score: 4/5

**Comment by vajrang-b** [comment]
SourceCode/2024/Basics-April2024/Bhimendhar/Task 33/project.json
**Main.xaml**
Code Review:
- Log Message not used in workflow
Recommendation: Add meaningful log messages throughout the workflow to help with debugging and understanding the flow path.

**NoFile**
Code Review:
- Your organization requires your project to have an Automation Hub URL defined.
Recommendation: Go to Project Settings, click on "Automation Hub" and add the required URL. This is a requirement for your organization's projects.

**Comment by vajrang-b** [comment]
SourceCode/2024/Basics-April2024/Bhimendhar/Task 34/project.json
**Substraction.xaml**
```markdown
* The log message is not used in the workflow. It's important to include log messages for better understanding of the flow and debugging purposes.
* Argument In_Num1, In_Num2, and Out_SubResult do not follow the naming convention (^in_(dt_)?(A-Z|a-z)+(0-9)*$). Please rename them accordingly.
```

**NoFile**
```markdown
* The project requires an Automation Hub URL defined. Please add it in Project Settings.
```

**Performer.xaml**
```markdown
* Log Message display name is repeated multiple times. It's better to have unique names for each activity.
* Flowchart should be used only at the top layer for maintainability and readability reasons.
* Activity Get Transaction Item has a potential infinite loop. Please add a termination condition or document the code if it's intentional.
* Activities Log Message, Get Transaction Item, Set Transaction Status, and Log Message have default names. Please rename them to something more descriptive.
```

**Dispatcher.xaml**
```markdown
* Log Message activity is not used in the workflow. It's important for understanding the flow path during development and after release.
* Activity For Each Row in Data Table and Add Queue Item have default names. Please rename them to something more descriptive.
```

**Addition.xaml**
```markdown
* The log message is not used in the workflow. It's important for better understanding of the flow and debugging purposes.
* Arguments In_Num1, In_Num2, and Out_AddResult do not follow the naming convention (^in_(dt_)?(A-Z|a-z)+(0-9)*$). Please rename them accordingly.
```

**Score: 4/5**

Please note that I've grouped the issues based on file names as requested.

**Comment by krish952-creator** [comment]
@Bhimendhar 
Task -28
Code verified.
Task -29
Code verified.
Task -30
Code verified.
Task -31
Code verified.
Task -32
Code verified.
Task -33
Code verified.
Task -34
Code verified.

**Pull request merged**
