### PR TITLE
Task 6

### PR DESCRIPTION
**Pull request by Khantil12**
Writing Fruits name in Txt wile by using Append Line

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 6/project.json
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Go to 'Project Settings' to add the URL that's needed."
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Get rid of packages that aren't used. It can speed things up."
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Get rid of packages that aren't used. It can speed things up."
                   },
                   {
                       "Dependency package UiPath.UIAutomation.Activities is not used.":  "Get rid of packages that aren't used. It can speed things up."
                   }
               ],

    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Remember to use log messages. They're helpful for figuring out errors and for keeping track of the flow."
                      },
                      {
                          "Message Box display name is defined many times. Current allowed threshold is 1. Code contains 2.":  "Change the name of your activities to something unique. Using the same name many times can get confusing."
                      },
                      {
                          "Activity Message Box has a

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 6/project.json
github comments:

File: NoFile
- Remember to link your project to our Automation Hub URL. Head over to 'Project Settings' to add the missing details.
- I noticed you have included the UiPath.Excel.Activities, UiPath.Mail.Activities, and UiPath.UIAutomation.Activities packages. But I don't see you using them in your workflow. To speed up our process, it would be best to eliminate any additional baggage. Please remove any unused packages.

File: Main.xaml
- As a best practice, always use 'Log Message' activities. They help us to understand what's happening during development and troubleshooting. Please start using them.
- Each 'Message Box' must have a unique name. It helps us to know what the message box is for. Let's correct that.
- Please give a more descriptive name to these activities - 'Message Box', 'For Each' and 'Append Line'. It is a little hard for the rest of us to understand what these are doing currently.

Score:
- Code Completion: 1/2. There are unused packages and missing project information.
- Execution: 1/2. Not using log messages can lead to challenges in debugging.
- Annotations and Comments: 0/1. Missing unique and descriptive

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 7/project.json
Hey there,

I'd like to share some feedback on your code.

Firstly, it's notable that your project is missing an Automation Hub URL, which is a requirement for organization. So please add that through your "Project Settings". 

Now, on to your dependencies: I see UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities are included in your package, but they aren't being used in your code. Getting rid of these will help your process run a bit quicker.

In your Main.xaml, the variable 'num_array' is not following the set naming convention, which could make your code a bit challenging to follow. Please ensure all your variables follow the naming rules.

And that's it! Remember, keeping your code clean and efficient is always beneficial.

Scores:
- Code Completion: 1.5/2 (Unutilized dependencies and missing Automation Hub URL)
- Execution: 2/2 (No execution errors noted)
- Annotations and Comments: 0.5/1 (Improper variable naming)

Keep up the good work!

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 6/project.json
## File: NoFile

1. It seems your project is currently missing an Automation Hub URL. This is required by your organization. You can resolve this by simply adding the URL under "Project Settings".

2. I can see some dependency packages in the project like UiPath.Excel.Activities, UiPath.Mail.Activities, and UiPath.UIAutomation.Activities that seem to be not used. It's good practice to remove unused packages as they affect process execution time. A leaner project leads to faster processing time!

## File: Main.xaml

1. Logs are missing in the Main workflow. Having logs are crucial not only during development but also after release. They help in understanding the flow path and are very useful for maintenance and identification of error sources and causes. Please include them.

2. There seems to be multiple instances of 'Message Box' with same display name more than the allowed threshold. Avoiding duplicate names makes the flow easier to understand and helps in easier maintenance. 

3. Activities such as 'Message Box', 'For Each', and 'Append Line' are named default names. Naming activities that clearly indicate their purpose can greatly enhance understanding and readability of the code even for others in your team. Make sure you change these default names to something more descriptive.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 7/project.json
Score:

- Code completion: 2/2
- Execution: 2/2
- Annotations and comments: 0/1

Review:

NoFile:
- You haven't set the Automation Hub URL in the project settings. Please do this by going to the "Project Settings".
- There are packages in your dependencies that are not being used (`UiPath.Excel.Activities`, `UiPath.Mail.Activities`, `UiPath.Testing.Activities`, and `UiPath.UIAutomation.Activities`). Remove these unused packages to speed up your process.

Main.xaml:
- `num_array` variable doesn't follow the naming convention. It should be in the format `^(dt_)?([A-Z]|[a-z])+([0-9])*$`. Fix this to ensure consistency.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 8/project.json
"NoFile"
1) You need to put your Automation Hub URL in the "Project Settings". It's part of the rules here. 
Code Completion: 1
Execution: 1
Annotations: 0.5

2,3,4,5) There are some packages (UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities) you don't use. Remove them. It'll make things run faster.
Code Completion: 2
Execution: 2
Annotations: 1

"Main.xaml"
1) The variable Name_array doesn't follow the normal rules for naming. Make sure it does.
Code Completion: 1
Execution: 1
Annotations: 0.5

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 6/project.json
Score:
Code Completion: 2/2 (The code is complete.)
Execution: 1/2 (Improve your activity names & remove unused dependencies to increase execution score.)
Annotations and comments: 0/1 (Not seeing any usage of Log Messages for understanding the flow, also no Comments found. You must include these for better understanding of your code.)

Corrections:
1) NoFile: Add your Automation Hub URL in the Project Settings. It is a requirement from your organization. Also, there are some unused dependency packages - UiPath.Excel.Activities, UiPath.Mail.Activities, and UiPath.UIAutomation.Activities. Consider removing these to speed up the process execution time.

2) Main.xaml: 
- Make use of Log Message activities. These help in understanding the flow and tracing errors. 
- Activity names need improvement. They should be unique and descriptive. Currently, 'Message Box' display name is defined twice that is not a good practice.
- Also, multiple activities - 'Message Box', 'For Each' and 'Append Line' have default names. Give them meaningful names to make it clear what they do. Making these changes will make your code more understandable for everyone. 

Note: Regularly reviewing and improving your code is a good software

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 8/project.json
"NoFile",
1. Set the Automation Hub URL in project settings as it's asked by the organization.
2. Remove the unused dependency packages (UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities) for a faster program.

"Main.xaml",
1. Please follow the variable naming rules for "Name_array". Best practice it should be like this "^(dt_)?([A-Z]|[a-z])+([0-9])*$".

Scores:
Code Completion: 1.5
Execution: 1
Annotations and comments: 0.5

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 9/project.json
PR for NoFile:
1. Code Completion Score: 2/2 
    Good job, your code is completed.
2. Execution Score: 1.5/2 
    Your project missing Automation Hub URL, it seems you forgot to mention it on project setting.
3. Annotation and Comments Score: 1/1 
    Really appreciate your effort to make code readable, it's quite clean and acceptable.
   
Recommendations: 
1. Project Settings: Please define your Automation Hub URL. Remember, this is not an optional part.
2. Dependency Optimization: The packages "UiPath.Excel.Activities", "UiPath.Mail.Activities", "UiPath.UIAutomation.Activities" are not used but included in your project. Always remember, tidy up your code, remove the not used one. Keeping your code clean and efficient is a good practice.

Your total score is: 4.5/5. You are doing good, just remember the points I mentioned above. Keep coding.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 6/project.json
Here are my comments on the pull request:

NoFile:
- Add the missing Automation Hub URL in the 'Project Settings'.
- You have several unused packages including UiPath.Excel.Activities, UiPath.Mail.Activities, and UiPath.UIAutomation.Activities. Remove these to improve execution time.

Main.xaml:
- The workflow 'Main' doesn't use log messages. They're important to understand the process flow during development and maintenance. Please incorporate them.
- You've defined the 'Message Box' display name twice. Try to avoid this. Unique activity names makes the code clearer.
- Several activities including 'Message Box', 'For Each', and 'Append Line' all have default names. Adding descriptive titles to these can clarify their purpose in the process.

Scores:
Code completion: 2
Execution: 1.5
Annotation and comments: 0.5

This score indicates that there's a need to pay attention to naming conventions and redundant packages in your project for optimization. Also, make use of comments and logging for better understanding and maintainability.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 7/project.json
GitHub PR comment for file: "NoFile"

[CR Score: Code Completion: 1/2, Execution: 1/2, Comments and Annotations: 1/1]

- I noticed your project doesn't have an Automation Hub URL specified, you need to add one under "Project Settings".
- Your project has several dependency packages that you haven't used: UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities. Uninstall the unused ones to make your process run faster.


GitHub PR comment for file: "Main.xaml"

[CR Score: Code Completion: 1/2, Execution: 1/2, Comments and Annotations: 0/1]

- There's one variable called "num_array" that is not following the standard naming pattern. Please fix it.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 8/project.json
File: NoFile
---
* Your project doesn't have an Automation Hub URL. Go to "Project Settings" and add it.
* I noticed several unused packages. Deleting them can speed up your process. Here are the packages you should remove:
  - UiPath.Excel.Activities
  - UiPath.Mail.Activities
  - UiPath.Testing.Activities
  - UiPath.UIAutomation.Activities

File: Main.xaml
---
* The variable Name_array doesn't match the naming convention. Check and edit your variable names. 

Score:
---
Code Completion: 1.5/2 (Fix the variable naming violations)
Execution: 2/2
Annotation and Comments: 0.5/1 (Comment your code to make it more clear)

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 9/project.json
Your scores are as follows:
- Code Completion: 2/2. You've submitted all necessary files.
- Execution: 1/2. The project is missing the requirement for an Automation Hub URL.
- Annotations and Comments: 0/1. The code lacks sufficient comments explaining what the sections of code do.

You must address several issues:

1. The project requires an Automation Hub URL, which is currently not defined. Add the necessary information through "Project Settings". 

2. There are unused dependency packages in your project, Specifically, UiPath.Excel.Activities, UiPath.Mail.Activities, and UiPath.UIAutomation.Activities. These can slow down the process execution time. Remove them if they're not in use.

Remember to keep your project tight and lean; any unnecessary elements can lead to slowdowns and confusion. Make sure to also explain your code through comments and annotations. This allows others (and yourself in the future) to understand what your code does, making it easier to maintain and troubleshoot.

**Comment by krish952-creator** [comment]
@Khantil12 
Task-6
Code verified. Default activity names
image
 
Task -7
Code verified.
Task -8
Code verified.
Task -9
Code verified.

**Pull request merged**
