### PR TITLE
Task 1,6,7,8,9,10,13

### PR DESCRIPTION
**Pull request by Padmavathykarra**

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Padmavathykarra/Task10/project.json
**NoFile:** 
1. **Score: Code-1, Execution-1.5, Annotations-0.5**
- Update your Automation Hub URL under Project Settings.
- Unused dependencies like UiPath.Testing.Activities and UiPath.UIAutomation.Activities detected. Remove them for optimal execution time.

**Main.xaml:**
1. **Score: Code-1.5, Execution-1, Annotations-0.5**
- Use 'Log Message' in your workflow. Helps in debugging and maintaining your work.
- 'MessageBox' used too often, 7 times against threshold of 1. Avoid repetitions.
- Default names used for 'Message Box' activity. Add a descriptive name for better understanding.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Padmavathykarra/Task4/project.json
Score Criteria:
- Code Completion: 1.5
- Execution: 2
- Annotations and Comments: 0.5

Comments:

1. **NoFile**: There are some issues with your packages. You have unused packages - UiPath.Testing.Activities and UiPath.UIAutomation.Activities. It's best to remove these to improve the speed of the process. Also, don't forget to add the Automation Hub URL to your project settings.

2. **Main.xaml**: There are some issues with the naming of activities and variables.
   - Ensure your activity names are unique for ease of understanding. You have used the default 'Assign' and 'Message Box' names multiple times.
   - Make sure your variables 'Year_Input' and 'Boolean_Variable' respect the naming pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$.
   
For each of the points, you can apply the provided solutions to improve your code.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Padmavathykarra/Task6/project.json
{
    "NoFile": [
        {
            "Good job, but you forgot to define an Automation Hub URL.": "Go to 'Project Settings' and paste appropriate URL so we can update project status."
        },
        {
            "I see you have UiPath.UIAutomation.Activities package installed but not used.": "Let's keep it cleaned up, remove packages that are not needed, it makes process run faster."
        }
    ],
    "Main.xaml": [
        {
            "You didn't use Log Message in your Main workflow.": "Try including it, as it is very helpful in understanding flow path and troubleshooting when things go wrong."
        }
    ]
}

Score:
- Code completion: 2 
- Execution: 2 
- Annotations and comments: 0.5 

Suggestions: Include more comments and annotations, and don't forget to set the Automation Hub URL in the project settings. Plus, keep your environment tidy by removing unutilized packages.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Padmavathykarra/Task7/project.json
File: NoFile

1. "Your organization requires your project to have an Automation Hub URL defined." I suggest you head over to "Project Settings" and add the required information. Score: Code Completion, 1.

2. "Dependency package UiPath.Testing.Activities is not being used." It's best to clear out unused packages. They can slow down process execution. Score: Execution, 1.

3. "Dependency package UiPath.UIAutomation.Activities is also not being used." Again, clean it up. Helps speed up the workflow. Score: Execution, 2.

File: Main.xaml

1. "Log Message is not being used in workflow Main." Logging activities are pretty handy, mate. Helps during development and after release. Makes it easier to pinpoint any issues. Score: Annotations and Comments, 1.

Based on the input, here is your score:
- Code Completion:You score 1 out of 2.
- Execution:You score 2 out of 2.
- Annotations and Comments: You score 1 out of 1.

Overall Score: 4 out of 5. Good but aim for higher.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Padmavathykarra/Task8/project.json
For the file group "NoFile":
- Your project is missing Automation Hub URL. Ensure to add it in the "Project Settings" as it is required by your organization.
- You have included the 'UiPath.Testing.Activities' and 'UiPath.UIAutomation.Activities' package, but they are not used in the process. It is better to remove them as unused packages could slow down the process execution time.

For the "Main.xaml":
- I've noticed you haven't used any 'Log Message' in your workflow. They are crucial for effective troubleshooting, especially if something goes wrong, as they assist us in easily identifying the source and cause of an error.

And here are the scores:

- Code Completion: 1.5/2 (Code is there but some improvements can be made)
- Execution: 1/2 (Unused packages can affect it)
- Annotations and Comments: 0/1 (No log messages to help understand the workflow)

Remember, your code is your craft. Keep working to improve it!

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Padmavathykarra/Task9/project.json
Based on my review, here's your score and some feedback:

Code Completion: 1/2 
- A key detail missing from your project is the Automation Hub URL. Use the "Project Settings" to add this information.
- For the dependency package 'UiPath.UIAutomation.Activities', it looks like you're not actually using it in your project. To speed up process execution time, it's a good idea to remove any unused packages. 

Execution: 2/2 
- Your execution seems good, no issues detected.

Annotations and Comments: 0/1 
- Missing Log Message activity in your 'Main' workflow is a concern. Logs are useful during development but also after deployment by providing crucial information about the flow path. They ease the process of maintenance and debugging, aiding in understanding and identifying the root cause of any errors.
- There's an 'Input Dialog' activity in your Main workflow with a default name. Using a more descriptive name can significantly improve your code readability and understanding of its function.

Total Score: 3/5 

I hope you find this feedback useful and it helps you improve your projects in time to come. Let's strive for clean, efficient and well-annotated code. Happy coding!

**Comment by krish952-creator** [comment]
@Padmavathykarra 
Task -1
Code verified. 
Task -6
Code verified. 
Task -7
Code verified. 
Task -8
Code verified. 
Task -9
Code verified. Default activity name 
image
 
Task -10
Code verified. Default activity name 
 
image

Task -13
Code verified.

**Pull request merged**
