### PR TITLE
Task 28

### PR DESCRIPTION
**Pull request by Radha93M**

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2024/Basics-April2024/Radha/Task 28/project.json
Okay, I'll do my best to act as an UiPath code reviewer and provide feedback on the given file. Here are my findings:

* The organization requires a URL for Automation Hub in Project Settings, so please add this information. (Ignored)
* The Log Message activity in Main.xaml is not used in the workflow. It's important to use Log Messages during development and after release to understand the workflow path and identify errors easily. Please remove the unnecessary Log Message activity. (Executions: 0, Annotations & Comments: 1, Total Score: 1)
* The sequence "Sequence" is redundant and should be removed since it only clutters the workflow. Use the Remove Surrounding Sequence option in UiPath Studio to remove it. (Executions: 0, Annotations & Comments: 1, Total Score: 1)
* Some activity names are too generic and could be improved for better understanding of their usage. Please avoid duplicate names and provide more descriptive titles where possible. (Executions: 0, Annotations & Comments: 2, Total Score: 2)
* The Read PDF Text activity has a default name that doesn't explain its purpose well. Please add a more descriptive title to the activity to clarify what it does. (Executions: 0, Annotations & Comments: 1, Total Score: 1)
* Similarly, some of the other activities have default names that are not very informative. Please consider adding more descriptive titles where possible. (Executions: 0, Annotations & Comments: 2, Total Score: 2)
* Some activities have redundant or unnecessary options, such as "Export PDF Page As Image" and "Join PDF Files". Please review these activities and remove any unnecessary options. (Executions: 0, Annotations & Comments: 1, Total Score: 1)
* The Get PDF Page Count activity has a default name that doesn't explain its purpose well. Please add a more descriptive title to the activity to clarify what it does. (Executions: 0, Annotations & Comments: 1, Total Score: 1)
* Some activities have message boxes with generic titles like "Message Box". Please consider adding more descriptive titles to these activities to explain their purpose better. (Executions: 0, Annotations & Comments: 1, Total Score: 1)
* The Manage PDF Password activity has a default name that doesn't explain its purpose well. Please add a more descriptive title to the activity to clarify what it does. (Executions: 0, Annotations & Comments: 1, Total Score: 1)

Based on these findings, I would give this project a score of 3 out of 5. Some improvements have been made, but there are still some areas where the activity names could be more descriptive and some unnecessary options could be removed.

**Comment by vajrang-b** [comment]
SourceCode/2024/Basics-April2024/Radha/Task 29/project.json
Hello! As an UiPath code reviewer, I've reviewed your PR file and found some areas that need improvement. Here are my findings:

1. Automation Hub URL missing: In Project Settings, please define the Automation Hub URL. This is a requirement for your organization.
2. Unused Log Message in Main workflow: It's important to use Log Messages during development and after release to understand the workflow's flow path and identify errors easily. Please remove the unused Log Message activity in Main.xaml.
3. Duplicate activity names: In Sequence, there are multiple instances of the same activity name. To avoid confusion, please give each activity a unique name that indicates its purpose. The default names are too generic, so please avoid using them.
4. Unclear activity names: In Read Range Workbook, the activity name is ambiguous. Please give the activity a more descriptive title to help understand its purpose.
5. Missing DataTable prefix: In Variable Result, the variable doesn't have the required DataTable prefix. Please start the variable name with dt_.
6. Unhelpful activity names: In Activity Try Catch and Activity Kill Process, the default activity names are too generic. Please give each activity a more descriptive title to help understand its purpose.

Based on these findings, I will give your PR a score of 2 out of 5. Please address these issues before submitting the PR for review.

**Comment by vajrang-b** [comment]
SourceCode/2024/Basics-April2024/Radha/Task 30/project.json
Hello! As an UIPath code reviewer, I have reviewed your project and identified some areas that could be improved. Here is my feedback:

1. NoFile: Your organization requires your project to have an Automation Hub URL defined. Please add the missing information in Project Settings.
2. Main.xaml: You have a Log Message activity without using it in the workflow. It's important to use Log Messages during development and after release to understand the flow path and identify errors easily. Please use the Log Message activities appropriately.
3. Multiple occurrences of "Display Name" are defined for Message Box activities. The allowed threshold is 1. Please avoid duplicate names and give clear indications of how each activity is used.
4. Variable "Result" doesn't have a DataTable prefix. Please start the variable name with "dt_".
5. Activity "For Each Row in Data Table" has a default name that could be more descriptive. Can you add a more detailed title to understand what the activity does?
6. Activity "Message Box" has a default name that could be more descriptive. Please add a more detailed title to understand what the activity does.
7. Activity "If" has a default name that could be more descriptive. Please add a more detailed title to understand what the activity does.
8. Activity "Throw" has a default name that could be more descriptive. Please add a more descriptive title to understand what the activity does.

Overall, your project scores 3 out of 5 for code completion, execution, annotations and comments, and overall readability. Please address these issues in your project to improve its quality and maintainability.

**Comment by krish952-creator** [comment]
@Radha93M 
Task -28
Code verified.
Task -29
Code verified.
Task -30
Code verified.

**Pull request merged**
