### PR TITLE
Task 14

### PR DESCRIPTION
**Pull request by Navneeth1996**

### CODE REVIEW

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "Variable ExtractDataTable doesn\u0027t have DataTable prefix.":  "DataTable Variable should start with a dt_ prefix. "
                      },
                      {
                          "Variable Result doesn\u0027t have DataTable prefix.":  "DataTable Variable should start with a dt_ prefix. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "Variable ExtractDataTable doesn\u0027t have DataTable prefix.":  "DataTable Variable should start with a dt_ prefix. "
                      },
                      {
                          "Variable Result doesn\u0027t have DataTable prefix.":  "DataTable Variable should start with a dt_ prefix. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "WriteLine activity usage at Write Line - Using this to write each line into fullname column.":  "Write Line activity can be replaced with tracepoints during debug. They should be removed before publishing. Consider also changing WriteLine to Log Message if it is really needed for debugging purposes. "
                      }
                  ]
}

**Comment by krish952-creator** [comment]
@Navneeth1996 
Task -14
Code verified.
Task -15
Code verified.
Provide input file in necessary tasks.

**Pull request merged**
