### PR TITLE
Completed Tasks

### PR DESCRIPTION
**Pull request by ChandupriyaY**
Task 12, 13, 14, 15, 16

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_12/project.json
File: Main.xaml

Hello Developer,

It seems like there is an issue when trying to load this file. The system is not able to recognize a ForEach of Integer type function. This could be due to missing or incompatible packages. Here are steps to cross verify and fix it:

1. Confirm if all the needed packages are installed and updated. Mainly check for the UiPath.System.Activities package.
2. Make sure the ForEach activity is correctly set up. In the TypeArgument property, you should set it as Int32.
3. Finally, check your entire xaml file for any syntax errors or missing dependencies.

After above, there's another error for your attention. The project cannot be analyzed due to workflow errors. You should:

1. Check all the workflows used in the project.
2. Each running error should be repaired before trying to analyze the project.
3. Make sure error free in workflows will make project analysis possible.

I hope these suggestions will lead you to the resolution.

Best of luck!

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_13/project.json
"NoFile" Comments:

1. It seems you've forgotten to define an Automation Hub URL for your project in settings. It's easy to fix, just go to "Project Settings" and add it.

2. I noticed that you have some packages (UiPath.System.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities) listed as dependencies, but they aren't being used in the code. You can speed up the execution process by removing these unnecessary packages.

Main.xaml Comments:

1. It looks like Log Message Activities is not being used in your Main workflow. Remember, these are important. They make it a lot easier to understand the flow and to identify problems when errors occur. So, it would be a good idea to add these.

2. I noticed that "Executes set of child activities" is used frequently (2 times), but our threshold is only once. Try to use unique names for activities. They should clearly indicate their purpose. This will make the code easier to read and maintain.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_14/project.json
Hey there,

Looks like there's a problem loading the "Main.xaml" file, it's trying to create an unknown type `{http://schemas.uipath.com/workflow/activities}FilterDataTable`. You may have an issue with the Filter Data Table activity in your workflow, like it does not exist or has been incorrectly referenced.

If you have not already added the Filter Data Table activity in your project, go and add it, and make sure it is the right version. Otherwise, consider refreshing your package dependencies in UiPath Studio and then check if your target .NET framework version is compatible with the UiPath's FilterDataTable activity.

The other error indicates a problem in the workflows within the project. The project analysis cannot be completed because of these workflow errors. Ensure that all individual workflows are working correctly and there are no errors or unresolved activities.

Once you've checked and corrected these issues, give it another try. 

Remember, each part of your project, just like each part of a car engine, needs to be working correctly for the whole thing to run smoothly.

Let me know how it goes.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_15/project.json
This comment pertains to the file `Main.xaml`:

1. **Issue:** The UiPath workflow is unable to load because of an unknown type `{http://schemas.uipath.com/workflow/activities}ForEachRow`. Make sure this type is declared and defined properly in your code.

    **Solution:** Confirm the library packages are correctly installed and up to date. If this doesn't solve it, replace the `ForEachRow` activity with the `For Each` activity and specify the type argument as `DataRow`.

2. **Issue:** The project analysis can't proceed because of errors in some workflows.

    **Solution:** Before you can perform a project analysis, all errors in the workflows need to be resolved. Identify these errors, debug the code and validate the workflow for any runtime exceptions or errors. Keep your code clean, understandable, and optimized.

Please thoroughly check your entire project again before committing. A clean, bug-free code makes it easier for others to review and understand.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_16/project.json
**NoFile**

- _Missing Automation Hub URL_: Your project is missing an Automation Hub URL. You can add it in 'Project Settings'. With it, you can connect easily with the tools that your organization uses.

- _Unused Dependency Packages_: Seems like 'UiPath.Testing.Activities' and 'UiPath.UIAutomation.Activities' are not being used in your project. Remove them. This way, your process will run faster.

**Main.xaml**
- _Log Message Not Used in Workflow_: It's good to sprinkle some 'Log Message' activities here and there. It will be easier to understand and debug. When the going gets tough, these logs can help you get to the root of the problem quicker.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_18/project.json
NoFile:
1. Your project is missing an Automation Hub URL. You can fix this issue by navigating to "Project Settings" and adding the requisite information.

2. The UiPath.Excel.Activities package is not being utilized in your project. For optimization, it's best to remove unused packages. This can help to improve your process's run time.

3. The UiPath.Testing.Activities package is not being used. Much like the above case, it is a good idea to remove unused packages to enhance efficiency.

Main.xaml

1. It appears you haven't used the Log Message activity in your main workflow. Remember, these logs are crucial. They help track the flow and make it easier to identify issues, both during development and after your project's release.

2. The Build Data Table activity currently maintains its default name. To make your workflow more comprehensible, consider renaming this to something more descriptive.

3. Similarly, your Assign activity also holds its default name. Adding a more descriptive name will make your workflow easier to read and understand.

Try to rectify these issues for a more efficient and effective project. Remember, the devil is in the details.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_24/project.json
Error: Undefined Message Box in Main.xaml.

Solution:

The Main.xaml file seems to have an error. The MessageBox class is not being recognized. 

This usually happens if you are using the MessageBox class that doesn't exist in your current namespace. 

Try adding the correct Namespace for using MessageBox into your xaml file. If your current workflow activities don't include MessageBox, you might need to import it. Go to "Import" panel in UiPath and ensure system.windows is added there. 

Please correct this, commit, and push again.

---

Error: Project analysis failure due to workflow errors.

Solution:

Your project failed to analyze due to some errors in your workflow. 

Ensure your workflows are free of errors before attempting to run the project. 

Check your project dependencies and make sure they are up-to-date. Also, verify that all required activities referenced in your workflow are properly installed and imported. 

Resolve all workflow errors and re-attempt project analysis. Commit and push again once errors are cleared.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_12/project.json
Review:

1) File Load Issue: There's an error on Main.xaml in Task_12, it seems you're trying to use a ForEach with an integer, which isn't valid in UiPath. Check your ForEach activity for any casting or type errors.

2) Project Analysis: Ensure all workflows are error-free for the project to run properly. as it stands, your project cannot be analyzed. Double-check your changes and fix any errors you spot.

Always remember to test your code frequently to catch errors early and minimize their impact on the entirety of the project.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_13/project.json
For the file with no specific name:

1. Add the Automation Hub URL to your project. Go to "Project Settings" to put in the missing info.
2. Got a few packages here that aren't being used - UiPath.System.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities. Kick these out to make your process run faster.

For Main.xaml:

1. You're not using Log Message in your workflow. These can help keep track of what's happening, which is great for maintenance and finding errors. Pop one in.
2. You've got "Executes set of child activities" showing up twice. Try to keep names unique so we know what each one does. Cut the copycat out.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_14/project.json
Comment:
```
Hey, 

Looks like there's an issue with your 'Main.xaml' file which is preventing project analysis. The error seems to be related to the 'FilterDataTable' activity. 

You might want to check the following:
1. Verify that the 'FilterDataTable' activity is properly integrated in your workflow.
2. If you're using a package containing the 'FilterDataTable' activity, ensure it's correctly installed and the version is compatible with your UiPath Studio's version. 
3. Check your XAML file for any syntax errors or "unknown types". 

Fix these and submit your PR again. Let's get this up and running!
```

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_15/project.json
Hey there,

There’s a couple of issues with loading the `Main.xaml` file, it seems UiPath can't recognize the `ForEachRow` type. This can be caused by a missing or improperly imported package, or it may be an error in the code itself. Please check if your dependencies are correctly managed. 

Also, the project analysis can't be performed due to these errors. You need to fix them first. We can't proceed further till these are sorted out. 

Fix these, and we should be good to go. If you're stuck, don't hesitate to ask.

Also, to prevent such an issue in future, ensure the missing dependencies are added in `project.json` file and activities that require packages are correctly added.

Cheers!

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_16/project.json
# NoFile
- **Issue:** You're missing an Automation Hub URL defined in your project.  
  **Fix:** Hit up the "Project Settings" and add the details.
  
- **Issue:** You're not using the UiPath.Testing.Activities package.      
  **Fix:** Unused packages can bog down the process execution time - consider removing it.

- **Issue:** The UiPath.UIAutomation.Activities package isn't used in your project. 
  **Fix:** It's a good idea to get rid of any unused packages to speed up execution time.

# Main.xaml
- **Issue:** You're not using the 'Log Message' activity in the Main workflow.
  **Fix:** These logs come in handy during development and after release too. It helps to understand the flow path and if there's an error, it's easier to spot the problem. Add some where needed.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_17/project.json
Error 1:

The file Main.xaml cannot be loaded! It seems that it's using unknown type `ReadTextFile`.

This is a common error when using UiPath activities that are not supported in your version. Please first make sure you have installed the correct packages/dependencies or check your UiPath Studio version.

A possible fix is to update the file with a valid type or activity. You can use the `Read Text File` activity that is properly supported and maintained by UiPath.

Error 2:

There are errors in some workflows, which are causing your project analysis to fail.

Please check your workflows. Algorithm and logic-based errors cannot be fixed with package updates or software updates. These mistakes are often due to inattention or misunderstanding of how the UiPath activities work.

Most times the debugging tool is your best friend. Patch these errors before reattempting the project analysis.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_18/project.json
**NoFile:**
- You forgot to provide the Automation Hub URL. Go to 'Project Settings' and add this.
- There are a couple of packages (UiPath.Excel.Activities & UiPath.Testing.Activities) you're not using, rip them out.

**Main.xaml:**
- No logs, really? Add 'Log Message' activities, they help you figure out what's happening when things go south.
- 'Assign' activity has a default name? Renaming it might help people understand its actual role.
- Another default-named activity spotted, 'Build Data Table'. A better name would add clarity.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_24/project.json
### Main.xaml

1. **Cannot create unknown type MessageBox:** This error usually happens when there are missing dependencies. UIPath can't recognize the type 'MessageBox'. Make sure all the necessary packages are installed and updated. Also, verify that the correct namespaces for 'MessageBox' have been imported.

2. **Project analysis error due to workflow errors:** This error signifies that there are errors within your project and it is causing issues during project analysis. You'll need to debug the project worklfows, fix any discovered issues before you can perform a proper project analysis.

**Comment by krish952-creator** [comment]
@ChandupriyaY 
Task -12
Code Verified. Default Activity names
 
image

Task -13
Code Verified.
Task -14
Code Verified.
Task -15
Code Verified. Default Activity names
 
image

Task -16
Code Verified.
Task -17
Code Verified. Default Activity names
 
image

**Pull request merged**
