### PR TITLE
Task 1

### PR DESCRIPTION
**Pull request by Vineeth039**
Task 1

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/Nov2023/Basics/Vineeth/Task1/project.json
Hey there,

Checked into your code and here are some simple points you need to work on. 

**For your whole project:**

1. It seems you forgot to link your Automation Hub URL in your project settings. You might want to make sure you add those details.

2. I also noticed you have some unused packages lying around. The Excel and Mail activities packages aren't actually being used. Get rid of these to improve how fast your process runs.

**For your Main.xaml file:**

1. Found an activity log message name that's just the default. Make it easier on yourself (and anyone else jumping in) by adding a more descriptive title.

**Scores:**

- Code Completion: 2/2
- Execution: 1/2 (The bot won't run without the Automation Hub URL)
- Annotations and Comments: 1/1

Hope this is helpful, keep coding!

**Comment by vajrang-b** [comment]
SourceCode/2023/Nov2023/Basics/Vineeth/Task 1/project.json
Under "Main.xaml",
1. Your variable "Str_Welmsg" seems to not follow the established naming convention, "^ (dt_)? ( [A-Z] | [a-z] ) + ( [0-9] ) *$ | _out_ [A-Za-z] [A-Za-z0-9_] *$ ". Go through it again and correct it. Execution: 1; Code completion: 1; Annotations and Comments: 0.5

Under "NoFile",
1. The Automation Hub URL is required for your project. You can add this in your "Project Settings". Check it out. Execution: 1; Code completion: 1; Annotations and Comments: 0.5

Keep it up, and we will walk through this code together!

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Vineeth/Task 1/project.json
**Files**: Facebook Login.xaml

**Score**: Code Completion 1, Execution 1, Annotations and comments 1

**Review Suggestions**

1. File Load Error: Looks like there's an unknown type `Face_book_login` in namespace `Facebook_Login`. Ensure that either an appropriate .dll is included in the project, or modify the .xmal file to remove or correct this unknown type.

2. Argument Naming: You're not following the recommended pattern for argument naming (`^in_(dt_)?([A-Z]|[a-z])+([0-9])*$`). It’ll be easy for other developers to identify the type and purpose of an argument if you follow a pattern, so please correct it.

3. Password Argument Usage: You're using a SecureString as an argument. As a best practice, these should be stored in a secure place (like an orchestrator asset) and read when needed. Passing them between workflows is discouraged.

4. Plaintext Passwords: You're using a Type Into activity to input a password as plain text. It's not secure. Use Type Secure Text activity or Send Keys Secure activity for inputting passwords.

Focus on these issues to improve the quality of your code.

**Comment by vajrang-b** [comment]
SourceCode/2023/Nov2023/Basics/Vineeth/Task 1/project.json
Comments on "Main.xaml":

The variable 'Str_Welmsg' isn't following the stated naming conventions. It must stick to the pattern '^(dt_)?([A-Z]|[a-z])+([0-9])*$|_out_[A-Za-z][A-Za-z0-9_]*$'. So, please rename the variable according to this pattern. To do this, go into the variables panel, select the 'Str_Welmsg' variable, and edit the name.

Score: Code Completion: 1, Execution: 2, annotations and comments: 1

Comments on "NoFile":

It seems your project is missing an Automation Hub URL. This is required for your organization. You can set this by going into 'Project Settings' and adding the Automation Hub URL in the appropriate field.

Score: Code Completion: 1, Execution: 1, annotations and comments: 1.

**Comment by vajrang-b** [comment]
SourceCode/2023/Nov2023/Basics/Vineeth/Task 2/project.json
The code review has been done, below is the feedback:

**Main.xaml:**

1) The 'Log Message' function isn’t being put to use in the workflow Main. It’s worth using this function as it can allow you to make sense of the flow path and pick out any problems, both when you're making the code as well as after it's live.

2) The variables 'Int_Num1', 'Int_Num2', 'Int_Addition', 'Int_Subtraction', and 'Int_Multiplication' aren't following the naming patterns set. Remember to make sure all the variables follow the naming convention.

**NoFile:**

1) I see that the project doesn't have an Automation Hub URL defined, your organization needs this. In "Project Settings", add this information.

**Scores:**

Code completion: 1/2 (The variables aren't correctly named)
Execution: 1/2 (You're missing the Automation Hub URL)
Annotations and comments: 0/1 (You're not utilizing the 'Log Message' function)

The improvements aren't tough to handle, but they're important to the functioning of your code. Fix them and you'll be in a better spot.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Vineeth/Task 1/project.json
## Facebook Login.xaml
1. **Secure String Password argument found. SecureString arguments are not recommended.**
    - *Rating: 2/2*
    - Reply: Avoid using SecureString as arguments. After retrieval, SecureStrings should be used directly with the Type Secure Text activity or the Send Keys Secure activity. To securely pass credentials between workflows, don't use arguments. Instead, store the credentials externally and retrieve them as needed.
    - Resolution: Replace SecureString arguments with an external secure method for credential storage and retrieval.

2. **Argument Password does not respect the set pattern ^in_(dt_)?([A-Z]|[a-z])+([0-9])*$**
    - *Rating: 2/2*
    - Reply: Arguments should follow the specified pattern for naming conventions. This helps keep the code clean and easy to understand.
    - Resolution: Rename 'Password' argument to follow the naming pattern.

3. **UI Automation activity FB Type Into 'INPUT pass' used for typing plain text passwords.**
    - *Rating: 1/2*
    - Reply: Clear text passwords should not be used in your project for security reasons. It's advised to keep passwords securely stored and retrieved when necessary.
    - Resolution: Rev

**Comment by krish952-creator** [comment]
@Vineeth039 
Task -1
Code verified.

Task -2
Code verified.

**Pull request merged**
