### PR TITLE
Task20,21,22,23,24

### PR DESCRIPTION
**Pull request by Mohdabid161**
20.Read the excel (consists of Lower Letters), and type into website (Vajrang.org - Uppercase Task) and get the result and write into one excel 
21.Find the temperature of few cities and print the results into Excel 
22.Read the excel (consists of Lower Letters), and type into website (Vajrang.org - Uppercase Task) (by using Add data row add the data into the excel) 
23.Data Manipulation: Assign set of string (eg: abcdefg), and check the (length, substring, index, Last letters and Remove) 24.Assign input value (eg: UiPath Studio) , and replace the word with any other word by using Replace function

### CODE REVIEW

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "WriteLine activity usage at Write Line.":  "Write Line activity can be replaced with tracepoints during debug. They should be removed before publishing. Consider also changing WriteLine to Log Message if it is really needed for debugging purposes. "
                      },
                      {
                          "Variable input doesn\u0027t have DataTable prefix.":  "DataTable Variable should start with a dt_ prefix. "
                      },
                      {
                          "Activity Write Line has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Assign has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "WriteLine activity usage at Write results in uipath.":  "Write Line activity can be replaced with tracepoints during debug. They should be removed before publishing. Consider also changing WriteLine to Log Message if it is really needed for debugging purposes. "
                      },
                      {
                          "Variable temp doesn\u0027t have DataTable prefix.":  "DataTable Variable should start with a dt_ prefix. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "Variable index doesn\u0027t have DataTable prefix.":  "DataTable Variable should start with a dt_ prefix. "
                      },
                      {
                          "Variable build doesn\u0027t have DataTable prefix.":  "DataTable Variable should start with a dt_ prefix. "
                      },
                      {
                          "Activity Assign has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "Variable firstval is not used.":  "Remove variables that are not used. "
                      },
                      {
                          "Variable value is not used.":  "Remove variables that are not used. "
                      },
                      {
                          "Variable replacevalue is not used.":  "Remove variables that are not used. "
                      },
                      {
                          "WriteLine activity usage at Displaying Output data in output panel.":  "Write Line activity can be replaced with tracepoints during debug. They should be removed before publishing. Consider also changing WriteLine to Log Message if it is really needed for debugging purposes. "
                      },
                      {
                          "WriteLine activity usage at Displaying string length.":  "Write Line activity can be replaced with tracepoints during debug. They should be removed before publishing. Consider also changing WriteLine to Log Message if it is really needed for debugging purposes. "
                      },
                      {
                          "WriteLine activity usage at Displaying index of string.":  "Write Line activity can be replaced with tracepoints during debug. They should be removed before publishing. Consider also changing WriteLine to Log Message if it is really needed for debugging purposes. "
                      },
                      {
                          "WriteLine activity usage at Remove value Output.":  "Write Line activity can be replaced with tracepoints during debug. They should be removed before publishing. Consider also changing WriteLine to Log Message if it is really needed for debugging purposes. "
                      },
                      {
                          "Sequence display name is defined many times. Current allowed threshold is 1. Code contains 2.":  "Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names. "
                      },
                      {
                          "Activity Comment Out has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by krish952-creator** [comment]
@Mohdabid161 
Task -20
Code verified. 
Task -21
Code verified.
Task -22
Code verified. Default activity name
image
 
Task -23
Code verified.
Task -24
Code verified.

**Pull request merged**
