### PR TITLE
Task06 Completed

### PR DESCRIPTION
**Pull request by Nazeernrb**
Task06 Completed

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nazeer/Task06/project.json
**Score:**

- Code Completion: 1.5
- Execution: 1.5
- Annotations and Comments: 0.5

**Code Review:**

1. **For All Files:**

   - It appears you don't have an Automation Hub URL defined. To add the missing information, open Project Settings.
   
   - There are unused dependency packages in your project: `UiPath.Excel.Activities`, `UiPath.Mail.Activities`, `UiPath.UIAutomation.Activities`. Unused packages can slow down your process, remove them.

2. **For Main.xaml:**

   - You have not used any Log Message activities. They are essential during development and post-release to understand the flow path and to identify the sources and causes of errors. Add some.
   
   - Activity names 'Loop For Each Value', 'Body' and 'Append Line' are duplicated. It's better to give activities clear and unique names. It helps understand how they are being used.
   
   - Variables 'Colour_Names' and 'Fruits_Name' do not follow the naming pattern. Stick to the prescribed naming convention for clarity.
   
   - There are activities with default names, like 'Append Line'. Giving them a more descriptive name can make it easier

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nazeer/Task07/project.json
#### File: NoFile
- For every project, it's a necessary thing to have an Automation Hub URL defined. Just go to the 'Project Settings' to put this information in.  

- Your project has a bunch of loaded packages which it doesn't even use. Remember, some of these unused packages in your codes like `UiPath.Excel.Activities`, `UiPath.Mail.Activities`, `UiPath.Testing.Activities`, and `UiPath.UIAutomation.Activities` makes your process execution time longer. Do your code a favour, clean it up. 

#### File: Main.xaml
- I see no Log Message in your workflow `Main`. Why not give it a little attention? It's usually helpful during development and even after release. It comes handy to understand the flow path which makes maintenance easier. Trust me, when an error pops up, you'd wish you had included it to identify the problem source and cause easily. 

- There's an activity called `Message Box` having a default name sitting in your workflow. How about you make it more descriptive? It'll help you to understand better what the activity does. 

**Scores**:  Code Completion = 1, Execution = 2, Annotations and Comments = 1

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nazeer/Task08/project.json
### Review for file: NoFile

**Code Completion Score: 1/2**

You forgot to add the Automation Hub URL in the project settings.

**Execution Score: 1/2**

You have several unused packages like - UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities. Remove these to speed up the process.

**Annotations and Comments Score: 1/1**

-------

### Review for file: Main.xaml

**Code Completion Score: 1/2**

You're missing log messages in your workflow. These can help you understand what's going on while coding, and help others understand when they're trying to fix problems.

**Execution Score: 2/2**

**Annotations and Comments Score: 0/1**

Your message box activity has a default name. Changing it to something more descriptive makes your code easier to understand and maintain. 

-----------

Note: It's good to be neat and clean with your code, it makes it faster and easier to understand. Always remember to remove what's not needed, and make things clear for others who might look at your code. Keep coding!

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nazeer/Task09/project.json
#### NoFile
1. Your project is missing the required Automation Hub URL. To fix this, go to "Project Settings" and add the missing information. 

2. You've added some packages (UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.UIAutomation.Activities) that you're not actually using. This can slow down your process, so it's better to remove them. 

#### Main.xaml
1. You're not using Log Message in your Main workflow. These logs can help to understand the flow of your application and track down errors, so consider adding some. 

2. The Read Dialog Box is named the same thing in two different locations. It helps to give unique, descriptive names to your activities. 

3. Some of your activities (Message Box and Write Text File) have the default names. It might be easier to understand what they're doing with more descriptive names. 

### Score
Based on my review, I'd give the following scores:

- Code Completion: 1.5/2
- Execution: 2/2
- Annotations and comments: 0.5/1

Total score: 4/5

**Comment by krish952-creator** [comment]
@Nazeernrb 
Task-6
Code verified. Default activity names
image
Task-7
Code verified. Default activity names
 
image

Task-8
Code verified. Default activity names
 
image

Task-9
Code verified. Default activity names
 
image

**Pull request merged**
