### PR TITLE
Task 28

### PR DESCRIPTION
**Pull request by Khantil12**
Pdf activities

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 28/project.json
_**Review for NoFile**_:

Your project is missing an Automation Hub URL. Go to "Project Settings" to add the necessary info. Score: 1.5/2

You've included several dependency packages that aren't being used, namely UiPath.Excel.Activities, UiPath.Mail.Activities, and UiPath.Testing.Activities. Get rid of the stuff you don't need - it’ll help your process run quicker. Score: 1/2


_**Review for Main.xaml:**_

Log messages haven't been used in the Main workflow. These are real helpful both while building the project and even after it’s finished. They help track the flow and if things go sideways, they can help spot where and why it happened. So, go ahead and use them. Score: 1.5/2

Two of your variables, R_pdf and new_pdf, aren't following the naming conventions. Keep consistency with the names. Score: 1.5/2

Your Tesseract OCR activity is sticking with the default name. It'd be easier to get what's going on if it had a descriptive name. So, consider renaming it. Score: 1.5/2

For annotations and comments, you haven’t included

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 28/project.json
For NoFile:

1. The project is missing an Automation Hub URL defined. Define URL in "Project Settings".
2. 'UiPath.Excel.Activities' package is not being used. Remove it to better process execution time.
3. 'UiPath.Mail.Activities' package is not being used. Remove it to better process execution time.
4. 'UiPath.Testing.Activities' package is not being used. Remove it to better process execution time.

For Main.xaml:

1. 'Log Message' is not used in workflow 'Main'. Use 'Log Message' activities to track flow path which helps during development and error identification.
2. Variable 'R_pdf' does not follow the naming convention. Update to follow the pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$.
3. Variable 'new_pdf' does not follow the naming convention. Update to follow the pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$.
4. 'Tesseract OCR' activity has a default name. Update it to a more descriptive title to understand its functionality better.

Scores: 
For Code Completion: 1.5 (The Automation Hub URL isn't defined and some variable names do not comply with

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Khantil Desai/Task 29/project.json
Score: 
- Code Completion: 1/2
- Execution:2/2
- Annotations and Comments: 0/1

Comments:

NoFile:
- Make sure you have defined an Automation Hub URL for your project. You can do this in 'Project Settings.' This is a requirement from your organization, not doing so may cause issues. 
- There are several packages in your project that aren't being used: UiPath.Mail.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities . Unused packages can slow down process execution, always a good idea to keep your project lean.

Main.xaml:
- I noticed you're not using the Log Message function in your main workflow. This is something you should consider. Log messages can help you trace and debug an application. They are important not just during development but also for maintenance after release.
- One of your variables, 'excel_dt,' is not following the naming convention for DataTable. It should start with 'dt_' to clearly indicate its type.
- The variable 'excel_dt' is not respecting the set pattern for variable names. Naming convention is important for readability and maintainability, ensure it follows the established pattern. 

These are easy fixes that can greatly improve your code. Let

**Comment by krish952-creator** [comment]
@Khantil12 
Task -28
Code verified.
Task -29
Code verified.

**Pull request merged**
