### PR TITLE
Task-3,3c,4,5 completed

### PR DESCRIPTION
**Pull request by Nihar-11**

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nihar/Task_1/project.json
01. PR No: 432 -> File Name: Main.xaml
Review Comments: 

- There is a redundant sequence. Remove the unused ones, it helps to declutter the process. Also, UiPath Studio has a "Remove Surrounding Sequence" option, give it a spin.

- There is a variable named 'str_Name', it doesn't follow the prescribed naming pattern. Consider sticking to the naming convention for better code readability and maintainability.

- We have an 'Input Dialog' activity and a 'Log Message' activity with default names. These default names aren't as descriptive as they could be, consider renaming them.  

Scores: 
Code Completion: 2 
Execution: 2 
Annotations and Comments: 0.5

02. PR No: 432 -> File Name: N/A (Project Level)

Review Comments: 
- The project doesn't have an Automation Hub URL defined. It's mandatory for your organization. Use "Project Settings" to add this URL.

- There are dependency packages 'UiPath.Testing.Activities' and 'UiPath.UIAutomation.Activities' that are not in use. Removing these unused packages can increase execution speed.

Scores: 
Code Completion: 2 
Execution: 2 
Annotations and Comments:

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nihar/Task_2/project.json
The scores are as follows:

- Code Completion: 2/2 - All tasks are done properly.
- Execution: 1.5/2 - There are many redundant and default-named activities. Some variables also don't follow naming conventions.
- Annotations and Comments: 0.5/1 - Your code lacks comments and appropriate naming.

For improvements:

On NoFile:
1. You need to define your Automation Hub URL in "Project Settings."
2. You have UiPath.Testing.Activities and UiPath.UIAutomation.Activities packages which are not used. Decrease process execution time by removing them.

On Main.xaml:
1. The sequence you named as "Sequence" is redundant. For cleaner workflow, remove it through the "Remove Surrounding Sequence" option in UiPath Studio.
2. "Input Dialog" is used more times than necessary. It's not unique. Make sure to give clear names to your activities to avoid confusion.
3. Variables named "int_firstNumber" and "int_secondNumber" don't adhere to the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$ for variable naming. Stick to the pattern.
4. Some activities have default names. For better clarity, give each activity a

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nihar/Task_3-class/project.json
**Main.xaml** 

1. `Log Message not used in workflow Main.` 

Take care of logs, they're like your footprints for others to track you back. They'll help you understand the flow and when hit by an error, to easily locate the source. Use them even after release. 

Score: 2/2 for completion, 1.5/2 for execution, 0.5/1 for comments.

2. `The sequence Sequence is redundant.` 

Cut the fat, mate. Redundant is a beautiful word, but not when it comes to sequences. They only muck up the workflow. Clean them up by clicking on Remove Surrounding Sequence in the Context Menu in UiPath Studio.

Score: 1.5/2 for completion, 1/2 for execution, 0.5/1 for comments.

3. `Activity Assign has a default name.` 

Imagine your name is Default. Yep, doesn't sound fun, right? Same with activities, give them a proper name. could make understanding easier.

Score: 1.5/2 for completion, 2/2 for execution, 0/1 for comments.

4. `Activity Write Text File has a default name.` 

Again,

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nihar/Task_3/project.json
As uipath code reviewer, Here are some points to be noted:

Code Completion Score: 1.9/2
There are redundant sequences in your project, work to de-clutter your code by removing these as suggested in the comments. 

Execution Score: 1.9/2
Your project runs without errors, but we can optimize them by removing unused packages. 

Annotations & Comments Score: 0.6/1
Many activities have default names, it can be difficult for others to understand your code. Work on giving more descriptive names to your activities and variables. 

In summary:
NoFile:
1. Add your missing Automation Hub URL in "Project Settings"
2. If you're not using UiPath.UIAutomation.Activities, get rid of it. This can speed up the run time of program.

Main.xaml:
1. Watch out for unnecessary sequences. They just clutter the workflow. Use the Remove Surrounding Sequence function in Context Menu of UiPath Studio.
2. Pay attention to your activity names. For example "Assign" and "Append Line" show up more than once which is confusing. Unique names help others understand what's happening.
3. Keep your variables to the naming convention. Str_completeday, str_day, and str

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nihar/Task_4_LeapYear/project.json
Score criteria:

1. Code Completion: 1 
   - Multiple errors have been identified that need to be resolved before the code can be deemed complete. Variables are defined more than once, there are items not following the naming convention, and redundant sequences are present.

2. Execution: 1 
   - Unutilized dependency packages will slow the process execution, and variables have been defined more than once.

3. Annotations and Comments: 0  
   - Default names are being used for numerous activities, these should be renamed to help understand their purpose. Additionally, the naming convention for variables is not being followed consistently. 

Amiable advice:

- Uninstall unused packages. This will trim down your project size and potentially speed up the automation.
- Avoid clutter in your workflows. Simplify wherever possible. Remove redundant sequences – they only make the process messy. 
- Don't repeat variable names. It's not a good idea. Name everything uniquely.
- Follow the conventions. They're there for a reason. It makes it easier for everyone to understand what's going on in your code. So, please make sure all variables follow the naming conventions.
- Descriptive names are your best friend. Don't rely on default names, they are usually too generic and don't

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nihar/Task_5/project.json
Score: 

Code Completion: 1/2 
Reason: Issues with naming conventions and repetitive use of certain activities affecting the simplicity and flow of your code.

Execution: 2/2 
Reason: No specific issues related to the execution found.

Annotations and Comments: 0/1 
Reason: Log Message was missing in the flows, which are crucial for understanding and tracking the code path.

Solutions:

1. Flowchart.xaml: 

   - Start using Log Message activities. It helps in identifying the source and the cause of the errors quickly.
   
   - Try avoiding duplicate names. They should provide a clear indication of how they’re being used.
   
   - Remember to change the default names of the activities to more descriptive titles, it will make it easier to understand their functions.
   
   - Follow the naming conventions for all variables. 

2. Main.xaml:

   - Start using Log Message activities. It helps in identifying the source and the cause of the errors quickly.


3. NoFile:

   - Add the Automation Hub URL in the "Project Settings".
   
   - Try to remove the unused packages, it can improve the process execution time.

**Comment by krish952-creator** [comment]
@Nihar-11 
Task -1
Code verified. Default activity names
 
image

Task -2
Code verified. Default activity names
 
image

Task -3
Code verified. Default activity names
 
image

Task -4
Code verified. Default activity names
 
image

Task -5
Code verified. Default activity names
 
image

**Pull request merged**
