### PR TITLE
Uploading Assignment Tasks

### PR DESCRIPTION
**Pull request by Sandhyathota1**
Uploading tasks: 12,13,14,15,16,17,18,20,22,23,24

Also re did the tasks 1,2,4 for my practice.

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Sandhya/Task12/Task12/project.json
## NoFile

- **Issue:** Your project is missing an Automation Hub URL. 
- **Solution:** Go to "Project Settings" and add the missing URL.

- **Issue:** Unused dependency packages detected. One or more of UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities isn't needed.
- **Solution:** Remove these unused packages. It'll make your process run faster.

## Main.xaml

- **Issue:** Log Message not being used in Main workflow. 
- **Solution:** You should use Log Message activities. They help in understanding the flow and identifying the source of errors. Add where needed.

- **Issue:** Duplicate Activity display names (Body, Else If, Assign). 
- **Solution:** Please rename these activities. Each should have a unique name that indicates its purpose.

- **Issue:** Some Activities (For Each, Else If, Assign) have default names. 
- **Solution:** Rename these activities with more descriptive titles. It makes understanding their functions easier.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Sandhya/Task13/Task13/project.json
# NoFile

1. Your project doesn't have a defined Automation Hub URL. To fix this, add the missing information in the "Project Settings".

2. Seems like you've included packages that you're not using. It's best to remove these to improve processing time. These are: UiPath.Mail.Activities, UiPath.System.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities. 

# Main.xaml 

1. You don't have any "Log Message" activities in your workflow - these are really useful for understanding the flow during development and after release, particularly when identifying errors. 

2. There's a variable, Dt_Data1, that you're not using. Best to remove it. 

3. This same variable, Dt_Data1, is defined multiple times - you'll need to give variables unique names, even if they're within different scopes.

4. The variable, Dt_Data, should start with a dt_ prefix. Same with the Dt_Data1 variable. They don't comply with the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$ and don't respect the naming convention. 

These changes should make your project a lot more efficient and easier to debug - please

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Sandhya/Task14/Task14/project.json
**Files**: NoFile

* - Your project is missing its Automation Hub URL. Kindly add it via the "Project Settings" tab.

* - Detected unused UiPath.Mail.Activities package. Suggesting to remove it to lower process execution time.

* - Detected unused UiPath.Testing.Activities package. Suggesting to remove it to lower process execution time.

**Files**: Main.xaml

* - No Log Message used in Main workflow. Remember, log messages are your friends in both development and debugging phases.

* - Variable "ExtractDataTable" does not have a "dt_" prefix. DataTable variables should begin with "dt_".

* - Variable "Dt_Dataresult" does not have a "dt_" prefix. DataTable variables should begin with "dt_".

* - Variable "Dt_Dataresult" seems to not follow the required pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$, please adjust to comply with naming conventions.

* - Activity "Extract Table Data" also has a default name. More descriptive titles are always better for readability and maintenance purposes. Go ahead and adjust it if possible.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Sandhya/Task15/Task15/project.json
For **NoFile**:
- "Put your work's URL from Automation Hub into 'Project Settings'. Your work needs it."
- "You don't appear to be using the UiPath.Mail.Activities, UiPath.Testing.Activities, or the UiPath.UIAutomation.Activities. Get rid of these packages to make your bot run faster."

For **Main.xaml**:
- "I don't see any 'Log Message' activities in 'Main'. These come in handy for both making and maintaining your bot. When something goes wrong, they also point you right to the problem."
- "You've used the 'Write Line' activity in 'Write Line'. This works for debugging but has to go before you publish your work. Use 'Log Message' instead if you really need it for debugging."
- "The name 'Assign' is being used more than once. The current limit is one but your code has two. Names have to relate to what these activities do. Default names won't do."
- "You've used default names for 'For Each Row in Data Table', 'Write Line' and 'Assign' activities. Make these more descriptive. They should tell anyone about what these activities do."

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Sandhya/Task16/Task16/project.json
**NoFile**

- **Issue 1:** Your project needs an Automation Hub URL. Go to 'Project Settings' and fill it in.

- **Issue 2, 3, 4:** You have packages that aren't being used: UiPath.Mail.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities. Remove these to make your process run faster.

**Main.xaml**

- **Issue 1:** No 'Log Message' used in your workflow 'Main'. Logs help understand the flow path, are useful for maintenance, and help identify where and why errors are happening.

- **Issue 2, 3, 4:** Your activities 'Build Data Table', 'Output Data Table', and 'Message Box' are using default names. Rename them to something that tells us what they do.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Sandhya/Task17/Task17/project.json
NoFile: 

1. Warning: The Automation Hub URL is not defined. Easy fix: Go to "Project Settings" and drop in the link there. 

2. Heads up: It seems like we have UiPath.Mail.Activities package included, but it ain't used. Let's save some time by removing it.
 
3. Same situation with the UiPath.UIAutomation.Activities package. Let's clear the unused baggage.

Main.xaml:

1. Noticed, 'Log Message' is non-existent in the 'Main'. Remember, logs are our eyes during and after deployment. They help us track the flow and identify any hiccups. Worth adding a few.

2. There's a variable 'outputtext' that's missing the DataTable prefix. Mirroring conventions, DataTable Variables should start exactly like this: 'dt_outputtext'. Correct it, mate.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Sandhya/Task18/Task18/project.json
Post for "NoFile":
```
Hey there, 

Come across a couple of things that need your attention:

1. We need to have an Automation Hub URL defined in your project. You can simply add this info through "Project Settings". 

2. Noticed some unused packages like `UiPath.Mail.Activities`, `UiPath.Testing.Activities` and `UiPath.UIAutomation.Activities`. Honestly cleaning those up improves process execution time. So, just get rid of those. 

If you got any questions, feel free to ask.
```

Post for "Main.xaml":
```
Hey, 

Just had a look over your workflow in 'Main.xaml'. Here's what stood out:

1. Missed out using `Log Message`. It's like breadcrumbs in the woods mate, helps you backtrack during development and post release. No worries, add it to easily trail errors.

2. Variables for DataTable should start with a dt_ prefix. Found one - `Datatable` which doesn't follow the naming style. Tweaking ought to do it. 

3. Spotted activities with default names: `Build Data Table`, `Multiple Assign`, `Assign`, `Add Data Row`. Seriously, more descriptive names make understanding easier. Switch it up to better ones

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Sandhya/Task20/Task20/project.json
## For Main.xaml

1. Start using "Log Message" activities in your workflow. This helps both during development and also after release. If there's an issue, these logs can help us find the source and cause more easily. 

2. Try to replace "WriteLine" activity with tracepoints during the debug stage. Ideally, get rid of it before publishing. If really needed for debugging, perhaps change WriteLine to Log Message. 

3. Prefix your DataTable Variable with "dt_". So, change "readrange" to "dt_readrange".

4. Please name your activities more descriptively. For example, "For Each Row in Data Table" and "Write Line" are too generic and it's hard for others to understand their purpose without context. 

## For NoFile

1. Your project needs an Automation Hub URL defined. Go to "Project Settings" and add it.

2. The dependency package "UiPath.Mail.Activities" is currently not in use. Let's get rid of it to improve process execution time.

3. The same goes for "UiPath.Testing.Activities". If it's not in use, remove it to speed up process execution time.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Sandhya/Task22/Task22/project.json
`Main.xaml`
1. The file seems to have a problem, it cannot create an unknown type `{http://schemas.uipath.com/workflow/activities}BuildDataTable`. Looks like there is an unrecognized activity in the workflow. Make sure to use supported activities or import the necessary packages.

2. Your project analysis is suffering because of some errors in your workflows. Clean up the errors first before running the project analysis.

Remember to thoroughly check your workflow for any unrecognized or forbidden activities. Keep your UiPath packages updated to avoid this kind of errors.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Sandhya/Task23/Task23/project.json
File: Main.xaml

Hey there,

1. It seems your Main.xaml file is trying to create a type (`{http://schemas.uipath.com/workflow/activities}MessageBox`) that the software doesn't understand. Be sure to use only supported types. Maybe you're trying to show a MessageBox? Use `MessageBox.Show("Your message here")`.

2. In addition, because of the errors in this file, the project analysis can't be completed. Fix the problem above and we should be able to analyze the project again.

Let's get this sorted and move forward. Review and update the file accordingly. 

Cheers.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Sandhya/Task24/Task24/project.json
Hey there,

I've looked over your changes and found some stuff we need to sort out:

1. "An exception was thrown while activating ?: UiPath.Studio.Platform.Contracts.IPlatformWrapper."
 - Seems there's an issue with the PlatformWrapper activation. You might want to check how this was implemented. Make sure all prerequisites for the activation are satisfied.

2. "Cannot perform project analysis because some workflows have errors."
 - Seems like there are errors in some of your workflows, which is blocking project analysis. This is likely caused by faulty or incomplete workflows. Try going over them again and debug any issues. Let me know if you need extra eyes on them.

Cheers, mate and keep up the good work!

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Sandhya/Task2_R1/Task2_R2/project.json
**File: Main.xaml**

Hey there,

Just a heads up, there seems to be a problem loading your `Main.xaml` file. This could possibly be due to an issue with the `InputDialog` activity in your UiPath project. 

It might be because UiPath can't recognize this activity. It could happen if you're using an outdated package version or the specific activity isn't installed in your project. 

To fix this, please check if you've installed all necessary dependencies and their versions are up-to-date.

Additionally, I noticed that the project analysis isn't complete due to some workflow errors. Once you address the above issue, this should be resolved. Remember, it's important for all workflows to be free of errors before we can perform a thorough project analysis.

Let me know if you need help figuring this out. Cheers!

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Sandhya/Task3_R1/Task3_R1/project.json
File: NoFile

Comments:

1. An exception was thrown: It seems like something is preventing your code from activating the IPlatformWrapper interface. Ensure that all dependencies are correctly installed and functioning as they should. If the issue persists, try debugging your code to find the conception point of the exception.

2. Cannot perform project analysis: There are errors in your workflows that are hindering project analysis. Go through your workflows step by step; identify and fix the errors to allow for accurate project analysis. Problem could be as simple as a syntax mistake, logic error or a missing/incorrect variable. Look for red underlines or exclamation marks that would indicate an error.

**Comment by krish952-creator** [comment]
@Sandhyathota1 
Task -2
Code verified.
Task -3
Code verified.
Task -12
Code Verified. Default activity Names
 
image

Task -13
Code verified.
Task -14
Code Verified. Default activity Names
 
image

Task -15
Code Verified. Default activity Names
 
image

Task -16
Code Verified. Default activity Names
 
image

Task -17
Code Verified.
Task -18
Code Verified. Default activity Names
image

 
Task -20
Code Verified. Default activity Names
image

 
Task -22
Code Verified. Default activity Names
 
image

Task -23
Code Verified. Default activity Names
 
image

Task -24
Code Verified. Default activity Names
image

**Pull request merged**
