### PR TITLE
Task10,Task11,Task12,Task13,Task14

### PR DESCRIPTION
**Pull request by ChiragJindal1231998**

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Chirag/Task11/project.json
Looks like you forgot to add the Automation Hub URL. You can add this through "Project Settings". 

Also, I noticed a few unnecessary packages in your project: UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities. These aren't being used and removing them could speed up your process execution time. 

In terms of scoring:
- Code Completion: 1.5/2 - Project incomplete due to missing Automation Hub URL. 
- Execution: 2/2 - No issues here, just potential for optimization.
- Annotations/Comments: 1/1 - No specific issues found regarding this. 

Keep up the good work, and make sure to clean up and refine where necessary for the best results!

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Chirag/Task12/project.json
## Score
- Code Completion: 2
- Execution: 1
- Annotations and Comments: 1

## Review
- You seem to have no issues with code completion. Great job! 
- There is a big issue with the execution side of things. 5 unnecessary dependency packages detected. That will slow down your execution time. Make sure you just include packages in your project that you actually use. You can do this by going to ```Manage Packages``` and removing the unused ones.
- Good job with the annotations and comments. Kept it simple and understandable.

## Solution
- ```Project settings``` > Add required Automation Hub URL.
- ```Manage Packages``` > Remove unused packages (UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities).
Remember, removing extra packages will speed up your process. With these taken care of, your process should run smoothly. Keep it up!

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Chirag/Task13/project.json
Scores:

Code completion: 2, Execution: 1.5, Annotations and comments: 1

Review remarks:
1. No Automation Hub URL in project settings: Head over to "Project Settings" and add the required URL.
2. Unused packages: Cleaning up can help make things run smoother. Consider removing unused packages like UiPath.Mail.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities.

Keep up the work and remember, coding is all about continuous refining.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Chirag/Task14/project.json
{
    "Automation.csproj": {
        "Comment": "There are few issues to address. First, your organization mandates defining an Automation Hub URL. Head over to 'Project Settings' to fix this. Second, there're two dependency packages 'UiPath.Mail.Activities' and 'UiPath.Testing.Activities' not being utilized. Get rid of these unused packages to make the process execute faster.",
        "Score": {
            "Code Completion": 1.5,
            "Execution": 2,
            "Annotations and Comments": 0.5
        }
    }
}

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Chirag/task10/project.json
### Code Completion: 2/2
The code seems to be finished at the time of the review. No places were found where the code execution seems incomplete.

### Execution: 1/2
The code is not used efficiently. There are several packages imported into the project that you aren't using. Please get rid of these as they are slowing your program down.

### Annotations and Comments: 1/1
Even though the code has no comments or annotations, given its current structure and readability, it doesn't seem to require any.

Overall Score: 4/5

Suggested Improvements:
- The project is missing Automation Hub URL. You need to add it in the "Project Settings".
- Clean up your code by removing unused packages. In your project, you are not using these packages: UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities. By removing these unused dependencies, you can improve the execution time of your project.

**Comment by krish952-creator** [comment]
@ChiragJindal1231998 
Task -10
Code verified. 
Task -11
Code verified. 
Task -12
Code verified. 
Task -13
Code verified. 
Task -14
Code verified.

**Pull request merged**
