### PR TITLE
Task 10,11,22,23,24

### PR DESCRIPTION
**Pull request by ChandupriyaY**
Task 10,11,22,23,24 are done

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_10/project.json
This comment is related to the 'Main.xaml' file:

Looks like there's an issue with the 'InputDialog' activity that's preventing your project from being analyzed. It seems UiPath can't identify this activity, likely due to a lack of its corresponding package in your project. To fix it:

1. Open your project in UiPath Studio.
2. In the Activities panel, search for 'InputDialog'. 
3. Check its package details. Make sure it's correctly installed via the Package Manager.
4. If not, install/upgrade it and try again.

Remember to make sure all your activities are correctly installed and maintained to avoid this kind of issue in the future.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_11/project.json
> Hey mate, there are a few things going off here.
> 
> 1. This workflow seems to have a few errors. Tip: double-check your flow, so the project can be accurately analysed. Don’t wanna miss anything, right?
> 
> 2. Looks like there's an issue with loading a file (C:\\VSTS_BA1\\_work\\1\\s\\SourceCode\\2023\\Sep2023\\Basics\\Chandupriya\\Task_11\\Main.xaml). It's having trouble with 'InputDialog'. This could mean the software does not recognise that component. Ensure everything’s in place and in the right version, and retry. Remember, if you ever have issues, always ensure components are correctly installed and updated.
> 
> Let's get these sorted and move onwards, warrior. Don't forget to follow the code- check, correct, commit, and then we conquer!

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_22/project.json
Hey there,

Hold up, seems like there's an issue with the `Main.xaml` file in your PR. Here's what could be going wrong:

1. You're trying to use the `BuildDataTable` activity, but UiPath doesn't seem to recognize it. Make sure you've installed all the necessary packages. Going to `Manage Packages` and installing `UiPath.System.Activities` should solve this.

2. There might be some errors in your workflows preventing the project from being analysed. You might want to go through each .xaml file, check the error list and fix them.

Keep it tight, eliminate the bugs, and let's roll over this issue.

Remember, preparation is key.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Chandupriya/Task_23/project.json
The "Main.xaml" file seems to have an issue. `{http://schemas.uipath.com/workflow/activities}MessageBox` is not recognized. You might have a deprecated or invalid usage of `MessageBox`. Kindly check your usage and replace or fix it accordingly.

Also, the project cannot be analyzed because this file has errors. Please make sure error is fixed for analysis to proceed. Fixing the `MessageBox` call should resolve this.

**Comment by krish952-creator** [comment]
@ChandupriyaY 
Task-10
Code verified.
Task-11
Code verified.
Task-22
Code verified.
Task-23
Code verified.
Task-24
Code verified.

**Pull request merged**
