### PR TITLE
Tasks 13,16,17,18,19,20 by Sarath Chandra

### PR DESCRIPTION
**Pull request by the-sarathchandra**

### CODE REVIEW

**Comment by vajrang-b** [comment]
Name             Value                                                                                              
----             -----                                                                                              
FilePath                                                                                                            
Description      Dependency package UiPath.UIAutomation.Activities is not used.                                     
ErrorSeverity    Warning                                                                                            
Recommendation   Remove unused packages in order to improve process execution time. [Learn more.](https://docs.ui...
ErrorCode        ST-USG-010                                                                                         
Item             774ded3e-49fc-45ee-82e3-5af7cd68a703                                                               
---------------- --------------------------------------------                                                       
FilePath         D:\Uipath\GitSpace\RPA-Developer-in-30-Days\SourceCode\2023\August2023\Sarath Chandra\Vajrang Ba...
Description      Variable DT_Tasks doesn't have DataTable prefix.                                                   
ErrorSeverity    Warning                                                                                            
Recommendation   DataTable Variable should start with a dt_ prefix. [Learn more.](https://docs.uipath.com/studio/...
ErrorCode        ST-NMG-009                                                                                         
Item             b64ba79a-afb4-492b-8d3c-15ff5be608d2                                                               
---------------- --------------------------------------------                                                       
FilePath                                                                                                            
Description      Dependency package UiPath.Mail.Activities is not used.                                             
ErrorSeverity    Warning                                                                                            
Recommendation   Remove unused packages in order to improve process execution time. [Learn more.](https://docs.ui...
ErrorCode        ST-USG-010                                                                                         
Item             b61986ed-f579-41fa-be58-42a01ac00e15                                                               
---------------- --------------------------------------------                                                       
FilePath                                                                                                            
Description      Dependency package UiPath.Testing.Activities is not used.                                          
ErrorSeverity    Warning                                                                                            
Recommendation   Remove unused packages in order to improve process execution time. [Learn more.](https://docs.ui...
ErrorCode        ST-USG-010                                                                                         
Item             ceab4d70-9cdc-496c-8ab2-39fd3858ae2b                                                               
---------------- --------------------------------------------                                                       
FilePath         D:\Uipath\GitSpace\RPA-Developer-in-30-Days\SourceCode\2023\August2023\Sarath Chandra\Vajrang Ba...
Description      Variable DT_Tasks does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$                  
ErrorSeverity    Warning                                                                                            
Recommendation   Make sure all the variables follow the naming convention. [Learn more.](https://docs.uipath.com/...
ErrorCode        ST-NMG-001                                                                                         
Item             e44073e5-05b7-4906-9a79-f06cc214a733                                                               
---------------- --------------------------------------------                                                       
FilePath         D:\Uipath\GitSpace\RPA-Developer-in-30-Days\SourceCode\2023\August2023\Sarath Chandra\Vajrang Ba...
Description      Variable Str_Ouput_Tasks does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$           
ErrorSeverity    Warning                                                                                            
Recommendation   Make sure all the variables follow the naming convention. [Learn more.](https://docs.uipath.com/...
ErrorCode        ST-NMG-001                                                                                         
Item             94e666f2-0781-4255-8d79-968f74bb598f                                                               
---------------- --------------------------------------------                                                       
FilePath                                                                                                            
Description      Your organization requires your project to have an Automation Hub URL defined.                     
ErrorSeverity    Warning                                                                                            
Recommendation   Use "Project Settings" to add the missing information. [Learn more.](https://docs.uipath.com/stu...
ErrorCode        ST-USG-034                                                                                         
Item             b29b5344-2b8c-4a8d-a545-e447f292854b                                                               
---------------- --------------------------------------------

**Comment by vajrang-b** [comment]
Name             Value                                                                                              
----             -----                                                                                              
FilePath                                                                                                            
Description      Dependency package UiPath.Mail.Activities is not used.                                             
ErrorSeverity    Warning                                                                                            
Recommendation   Remove unused packages in order to improve process execution time. [Learn more.](https://docs.ui...
ErrorCode        ST-USG-010                                                                                         
Item             53bc0baf-b738-4376-9c22-5445b8979e83                                                               
---------------- --------------------------------------------                                                       
FilePath                                                                                                            
Description      Your organization requires your project to have an Automation Hub URL defined.                     
ErrorSeverity    Warning                                                                                            
Recommendation   Use "Project Settings" to add the missing information. [Learn more.](https://docs.uipath.com/stu...
ErrorCode        ST-USG-034                                                                                         
Item             b6b523df-6e86-4d5b-842b-fccf84b2b94e                                                               
---------------- --------------------------------------------                                                       
FilePath                                                                                                            
Description      Dependency package UiPath.UIAutomation.Activities is not used.                                     
ErrorSeverity    Warning                                                                                            
Recommendation   Remove unused packages in order to improve process execution time. [Learn more.](https://docs.ui...
ErrorCode        ST-USG-010                                                                                         
Item             38e6508a-dc96-4d66-a475-9682d50f04b3                                                               
---------------- --------------------------------------------                                                       
FilePath         D:\Uipath\GitSpace\RPA-Developer-in-30-Days\SourceCode\2023\August2023\Sarath Chandra\Vajrang Ba...
Description      Variable Str_TxtFile does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$               
ErrorSeverity    Warning                                                                                            
Recommendation   Make sure all the variables follow the naming convention. [Learn more.](https://docs.uipath.com/...
ErrorCode        ST-NMG-001                                                                                         
Item             b3243bad-b090-4ba6-a957-8f1b80291130                                                               
---------------- --------------------------------------------                                                       
FilePath         D:\Uipath\GitSpace\RPA-Developer-in-30-Days\SourceCode\2023\August2023\Sarath Chandra\Vajrang Ba...
Description      Variable DT_Ranks does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$                  
ErrorSeverity    Warning                                                                                            
Recommendation   Make sure all the variables follow the naming convention. [Learn more.](https://docs.uipath.com/...
ErrorCode        ST-NMG-001                                                                                         
Item             e463bb42-fe19-45a9-ad06-644c99d5ab6a                                                               
---------------- --------------------------------------------                                                       
FilePath         D:\Uipath\GitSpace\RPA-Developer-in-30-Days\SourceCode\2023\August2023\Sarath Chandra\Vajrang Ba...
Description      Variable DT_Ranks doesn't have DataTable prefix.                                                   
ErrorSeverity    Warning                                                                                            
Recommendation   DataTable Variable should start with a dt_ prefix. [Learn more.](https://docs.uipath.com/studio/...
ErrorCode        ST-NMG-009                                                                                         
Item             063e2a37-b0da-4364-b35b-78ff35fe9f01                                                               
---------------- --------------------------------------------

**Comment by vajrang-b** [comment]
Name             Value                                                                                              
----             -----                                                                                              
FilePath         D:\Uipath\GitSpace\RPA-Developer-in-30-Days\SourceCode\2023\August2023\Sarath Chandra\Vajrang Ba...
Description      Log Message not used in workflow Main.                                                             
ErrorSeverity    Warning                                                                                            
Recommendation   Using Log Message activities is important both during development and after release. They help u...
ErrorCode        ST-USG-020                                                                                         
Item             f08a135f-1ed1-4d67-964c-931f25e525cc                                                               
---------------- --------------------------------------------                                                       
FilePath         D:\Uipath\GitSpace\RPA-Developer-in-30-Days\SourceCode\2023\August2023\Sarath Chandra\Vajrang Ba...
Description      Activity Comment Out has a default name.                                                           
ErrorSeverity    Warning                                                                                            
Recommendation   Check if it could be easier to understand what the activity does by adding a more descriptive ti...
ErrorCode        ST-MRD-002                                                                                         
Item             ff4c69bb-f7ee-4f72-ad9f-f0d5bfcb4982                                                               
---------------- --------------------------------------------                                                       
FilePath         D:\Uipath\GitSpace\RPA-Developer-in-30-Days\SourceCode\2023\August2023\Sarath Chandra\Vajrang Ba...
Description      Variable DT_Headers does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$                
ErrorSeverity    Warning                                                                                            
Recommendation   Make sure all the variables follow the naming convention. [Learn more.](https://docs.uipath.com/...
ErrorCode        ST-NMG-001                                                                                         
Item             12b9fb4d-fd88-40b2-8ae9-ab65ed0c7563                                                               
---------------- --------------------------------------------                                                       
FilePath         D:\Uipath\GitSpace\RPA-Developer-in-30-Days\SourceCode\2023\August2023\Sarath Chandra\Vajrang Ba...
Description      Variable DT_Output does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$                 
ErrorSeverity    Warning                                                                                            
Recommendation   Make sure all the variables follow the naming convention. [Learn more.](https://docs.uipath.com/...
ErrorCode        ST-NMG-001                                                                                         
Item             1fd31756-8f0a-42d1-ac0e-7723cf989f3e                                                               
---------------- --------------------------------------------                                                       
FilePath                                                                                                            
Description      Dependency package UiPath.UIAutomation.Activities is not used.                                     
ErrorSeverity    Warning                                                                                            
Recommendation   Remove unused packages in order to improve process execution time. [Learn more.](https://docs.ui...
ErrorCode        ST-USG-010                                                                                         
Item             9b59cd31-cd96-4691-be28-2c6a95c675a8                                                               
---------------- --------------------------------------------                                                       
FilePath         D:\Uipath\GitSpace\RPA-Developer-in-30-Days\SourceCode\2023\August2023\Sarath Chandra\Vajrang Ba...
Description      Variable DR_Details does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$                
ErrorSeverity    Warning                                                                                            
Recommendation   Make sure all the variables follow the naming convention. [Learn more.](https://docs.uipath.com/...
ErrorCode        ST-NMG-001                                                                                         
Item             f13bc5b4-81cd-48d2-969d-e27825b8cbf1                                                               
---------------- --------------------------------------------                                                       
FilePath                                                                                                            
Description      Dependency package UiPath.Testing.Activities is not used.                                          
ErrorSeverity    Warning                                                                                            
Recommendation   Remove unused packages in order to improve process execution time. [Learn more.](https://docs.ui...
ErrorCode        ST-USG-010                                                                                         
Item             88db1386-31a7-4741-9b1c-2790a4f70a15                                                               
---------------- --------------------------------------------                                                       
FilePath         D:\Uipath\GitSpace\RPA-Developer-in-30-Days\SourceCode\2023\August2023\Sarath Chandra\Vajrang Ba...
Description      Variable DT_Headers doesn't have DataTable prefix.                                                 
ErrorSeverity    Warning                                                                                            
Recommendation   DataTable Variable should start with a dt_ prefix. [Learn more.](https://docs.uipath.com/studio/...
ErrorCode        ST-NMG-009                                                                                         
Item             1616334d-9f26-42fa-814d-5281b8291c63                                                               
---------------- --------------------------------------------                                                       
FilePath         D:\Uipath\GitSpace\RPA-Developer-in-30-Days\SourceCode\2023\August2023\Sarath Chandra\Vajrang Ba...
Description      Activity Multiple Assign has a default name.                                                       
ErrorSeverity    Warning                                                                                            
Recommendation   Check if it could be easier to understand what the activity does by adding a more descriptive ti...
ErrorCode        ST-MRD-002                                                                                         
Item             3a3bdc29-7ff2-4555-960a-02c7c9fb24ed                                                               
---------------- --------------------------------------------                                                       
FilePath         D:\Uipath\GitSpace\RPA-Developer-in-30-Days\SourceCode\2023\August2023\Sarath Chandra\Vajrang Ba...
Description      Comment Out display name is defined many times. Current allowed threshold is 1. Code contains 2.   
ErrorSeverity    Warning                                                                                            
Recommendation   Names of activities should give a clear indication of how they are being used. Default names are...
ErrorCode        ST-NMG-004                                                                                         
Item             a11f24b3-9374-4ed1-a176-f9d72746f68d                                                               
---------------- --------------------------------------------                                                       
FilePath         D:\Uipath\GitSpace\RPA-Developer-in-30-Days\SourceCode\2023\August2023\Sarath Chandra\Vajrang Ba...
Description      Activity Comment Out has a default name.                                                           
ErrorSeverity    Warning                                                                                            
Recommendation   Check if it could be easier to understand what the activity does by adding a more descriptive ti...
ErrorCode        ST-MRD-002                                                                                         
Item             9f176c23-5a92-440e-9f86-5bf14041baa8                                                               
---------------- --------------------------------------------                                                       
FilePath                                                                                                            
Description      Dependency package UiPath.Mail.Activities is not used.                                             
ErrorSeverity    Warning                                                                                            
Recommendation   Remove unused packages in order to improve process execution time. [Learn more.](https://docs.ui...
ErrorCode        ST-USG-010                                                                                         
Item             867268f2-5875-44b1-a6fe-e6d44d6b6b48                                                               
---------------- --------------------------------------------                                                       
FilePath                                                                                                            
Description      Your organization requires your project to have an Automation Hub URL defined.                     
ErrorSeverity    Warning                                                                                            
Recommendation   Use "Project Settings" to add the missing information. [Learn more.](https://docs.uipath.com/stu...
ErrorCode        ST-USG-034                                                                                         
Item             d70947de-b476-4272-918f-3cd1770a6895                                                               
---------------- --------------------------------------------                                                       
FilePath         D:\Uipath\GitSpace\RPA-Developer-in-30-Days\SourceCode\2023\August2023\Sarath Chandra\Vajrang Ba...
Description      Variable DT_Output is not used.                                                                    
ErrorSeverity    Warning                                                                                            
Recommendation   Remove variables that are not used. [Learn more.](https://docs.uipath.com/studio/lang-en_US/v202...
ErrorCode        ST-USG-009                                                                                         
Item             9bb4e1ee-2cab-4e7b-a712-3c58e74716e6                                                               
---------------- --------------------------------------------                                                       
FilePath         D:\Uipath\GitSpace\RPA-Developer-in-30-Days\SourceCode\2023\August2023\Sarath Chandra\Vajrang Ba...
Description      Ignored Activities display name is defined many times. Current allowed threshold is 1. Code cont...
ErrorSeverity    Warning                                                                                            
Recommendation   Names of activities should give a clear indication of how they are being used. Default names are...
ErrorCode        ST-NMG-004                                                                                         
Item             d739922d-2982-4dfc-ae9f-7413c8bc685f                                                               
---------------- --------------------------------------------

**Comment by vajrang-b** [comment]
Name             Value                                                                                              
----             -----                                                                                              
FilePath                                                                                                            
Description      Dependency package UiPath.Excel.Activities is not used.                                            
ErrorSeverity    Warning                                                                                            
Recommendation   Remove unused packages in order to improve process execution time. [Learn more.](https://docs.ui...
ErrorCode        ST-USG-010                                                                                         
Item             45f2d414-36f9-454b-8394-45fc103f33b5                                                               
---------------- --------------------------------------------                                                       
FilePath                                                                                                            
Description      Your organization requires your project to have an Automation Hub URL defined.                     
ErrorSeverity    Warning                                                                                            
Recommendation   Use "Project Settings" to add the missing information. [Learn more.](https://docs.uipath.com/stu...
ErrorCode        ST-USG-034                                                                                         
Item             327ad6dd-0977-4588-88d6-57b1374a5f50                                                               
---------------- --------------------------------------------                                                       
FilePath         D:\Uipath\GitSpace\RPA-Developer-in-30-Days\SourceCode\2023\August2023\Sarath Chandra\Vajrang Ba...
Description      Variable Str_RPA does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$                   
ErrorSeverity    Warning                                                                                            
Recommendation   Make sure all the variables follow the naming convention. [Learn more.](https://docs.uipath.com/...
ErrorCode        ST-NMG-001                                                                                         
Item             d5d9dd20-378f-4bde-b566-d6520c5c21db                                                               
---------------- --------------------------------------------                                                       
FilePath                                                                                                            
Description      Dependency package UiPath.Mail.Activities is not used.                                             
ErrorSeverity    Warning                                                                                            
Recommendation   Remove unused packages in order to improve process execution time. [Learn more.](https://docs.ui...
ErrorCode        ST-USG-010                                                                                         
Item             699c2057-b4a3-4447-bae5-a52c5dcc1da3                                                               
---------------- --------------------------------------------

**Comment by swathinelakurthi** [comment]
@the-sarathchandra 
Task13: Changes Verified.
Task16: Changes Verified.
Task17: Changes Verified.
Task18: Changes Verified.
Task19: Code not executed.
image
The automation encountered difficulty in locating the required user-interface (UI) element for the intended action. 
Consider these steps: Ensure application is open and UI element visible, validate Target with Debug, re-indicate if properties changed, use 'Check state' activity, or adjust 'Delay before' for rendering time
Task20: Changes Verified.

**Pull request merged**
