### PR TITLE
Task3 Task4

### PR DESCRIPTION
**Pull request by rajendrayarlagaddausa333**

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Rajendra/Task2/project.json
**main.xaml**
- Input Dialog display name is duplicated, consider renaming or combining similar activities.
- Activity names are too generic and don't give a clear indication of what they do; rename them for better understanding.

**Score: 4/5**

Please note that the main issues with this file are:

* Duplicate activity names
* Inadequate naming conventions

These issues can be addressed by renaming activities to provide clearer indications of their purpose.

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Rajendra/Task2/project.json
**Main.xaml**
- The `Input Dialog` display name is repeated multiple times, which exceeds the allowed threshold of 1. Please consider renaming these to something more specific.
- Default names for activities like `Assign`, `Log Message`, and `Input Dialog` are too generic. It's better to add a more descriptive title to make it clear what each activity does.

**Score: 4/5**

Please update the display names and rename activities with more descriptive titles. Also, check if an Automation Hub URL is defined in your project settings.

**Comment by krish952-creator** [comment]
@rajendrayarlagaddausa333 
Task -3
Code verified.
Task -4
Code verified.

**Comment by krish952-creator** [comment]
@rajendrayarlagaddausa333 
Task -2
Code verified.
Task -5
Code verified.
Task -6
Code verified.

**Pull request merged**
