### PR TITLE
Task6,7,8,9

### PR DESCRIPTION
**Pull request by Mohdabid161**
Here task 6,7,8,9  are included
6.Assign the values Fruits and write in Text file
7.Assign Multiple values Numbers and display in the message box through index
8. Assign Multiple values Names and display in the message box through index
9. Read the values from the input dialog box and store the values in Array and write into text file through the index values

### CODE REVIEW

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.GSuite.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "Message Box display name is defined many times. Current allowed threshold is 1. Code contains 5.":  "Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names. "
                      },
                      {
                          "Variable Array_integerNmb does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$|_out_[A-Za-z][A-Za-z0-9_]*$":  "Make sure all the variables follow the naming convention. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Assign has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "Message Box display name is defined many times. Current allowed threshold is 1. Code contains 5.":  "Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names. "
                      },
                      {
                          "Variable Array_listofnames does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$|_out_[A-Za-z][A-Za-z0-9_]*$":  "Make sure all the variables follow the naming convention. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Assign has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "Input Dialog display name is defined many times. Current allowed threshold is 1. Code contains 2.":  "Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names. "
                      },
                      {
                          "Assign display name is defined many times. Current allowed threshold is 1. Code contains 2.":  "Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names. "
                      },
                      {
                          "Activity Input Dialog has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Input Dialog has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Assign has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Assign has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Write Text File has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "MessageBox display name is defined many times. Current allowed threshold is 1. Code contains 5.":  "Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names. "
                      },
                      {
                          "Activity Switch has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Input Dialog has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.GSuite.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "Message Box display name is defined many times. Current allowed threshold is 1. Code contains 5.":  "Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names. "
                      },
                      {
                          "Variable Array_integerNmb does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$|_out_[A-Za-z][A-Za-z0-9_]*$":  "Make sure all the variables follow the naming convention. "
                      },
                      {
                          "Activity Assign has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "Message Box display name is defined many times. Current allowed threshold is 1. Code contains 5.":  "Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names. "
                      },
                      {
                          "Variable Array_listofnames does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$|_out_[A-Za-z][A-Za-z0-9_]*$":  "Make sure all the variables follow the naming convention. "
                      },
                      {
                          "Activity Assign has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Log Message not used in workflow Main.":  "Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause. "
                      },
                      {
                          "Input Dialog display name is defined many times. Current allowed threshold is 1. Code contains 2.":  "Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names. "
                      },
                      {
                          "Assign display name is defined many times. Current allowed threshold is 1. Code contains 2.":  "Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names. "
                      },
                      {
                          "Activity Input Dialog has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Input Dialog has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Assign has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Assign has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Message Box has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      },
                      {
                          "Activity Write Text File has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by krish952-creator** [comment]
@Mohdabid161 
Task -6
Code is not available in the folder. reopen it again
Task -7
Code verified. Default activity name
image
 
Task -8
Code verified. Default activity name
 
image

Task -9
Code verified. Default activity name
 
image



Task -10
Code verified. Default activity name
image
 
After complete the code analyze the project once in studio and make a changes in activity names.
Merge a code in Githup means after that Update tracker with PR number in respective tasks.

**Pull request merged**
