### PR TITLE
Task on Exceptions(Try catch Finally, Retry, Throw) - Read the excel   

### PR DESCRIPTION
**Pull request by SAIMADDURI**
…and write the data into another Sheet

Task29

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/saivenu/Task29/project.json
**Main.xaml**
Sequence Action is empty: Remove empty sequences because they can clutter the workflow.

**Log Message not used in workflow Main:** Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause.

**Read Range Workbook**
display name is defined many times. Current allowed threshold is 1. Code contains 3: Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names.

**Sequence**
display name is defined many times. Current allowed threshold is 1. Code contains 2: Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names.

**Kill Process**
display name is defined many times. Current allowed threshold is 1. Code contains 2: Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names.

**Throw**
display name is defined many times. Current allowed threshold is 1. Code contains 2: Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names.

**Activity Retry Scope, Activity Comment Out, Activity Try Catch, Activity Read Range Workbook, Activity Kill Process, Activity Throw**
Have default names: Check if it could be easier to understand what the activity does by adding a more descriptive title.

Score: 5/5

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/saivenu/Task16/project.json
**Main.xaml**
Variable naming convention: The variable `dt_` does not follow the set pattern `^(dt_)?(A-Z|a-z)+(0-9)*$|_out_A-Za-zA-Za-Z0-9*$`. Please ensure all variables follow this naming convention.
Title suggestion for Activity Output Data Table as Text, Activity Build Data Table, Activity Log Message, and Activity Write Range Workbook: Provide more descriptive titles to make it easier to understand what each activity does.

**Score: 5/5**

**Dependencies**
Dependency packages UiPath.Mail.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities are not used. Please remove unused packages to improve process execution time.

**Score: 5/5**

Note: I will ignore "NoFile" as it is not related to the provided information.

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/saivenu/Task29/project.json
**Main.xaml**
Sequence Action is empty. Remove empty sequences because they can clutter the workflow.

**Read Range Workbook.xaml**
The display name for "Read Range Workbook" is defined multiple times. Please avoid duplicate names and add a clear indication of how the activity is being used.

**Kill Process.xaml**
The display name for "Kill Process" is defined multiple times. Please avoid duplicate names and add a clear indication of how the activity is being used.

**Throw.xaml**
The display name for "Throw" is defined multiple times. Please avoid duplicate names and add a clear indication of how the activity is being used.

**Try Catch.xaml**
The default name for the "Try Catch" activity could be improved by adding a more descriptive title that indicates what the activity does.

**Comment Out.xaml**
The default name for the "Comment Out" activity could be improved by adding a more descriptive title that indicates what the activity does.

**Retry Scope.xaml**
The default name for the "Retry Scope" activity could be improved by adding a more descriptive title that indicates what the activity does.

**Read Range Workbook.xaml**
The display name for "Read Range Workbook" is defined multiple times. Please avoid duplicate names and add a clear indication of how the activity is being used.

**Write Range Workbook.xaml**
The default name for the "Write Range Workbook" activity could be improved by adding a more descriptive title that indicates what the activity does.

Score: 4/5

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/saivenu/Task17/project.json
**Main.xaml**
Log Message not used in workflow Main.
Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause.

**Text DataTable**
Variable textDataTable doesn't have DataTable prefix.
DataTable Variable should start with a dt_ prefix.

**Generate Data Table From Text**
Activity has a default name.
Check if it could be easier to understand what the activity does by adding a more descriptive title.

**Write Range Workbook**
Activity has a default name.
Check if it could be easier to understand what the activity does by adding a more descriptive title.

**Unused Variables and Activities**

Dependency package UiPath.Mail.Activities is not used. Remove unused packages in order to improve process execution time.
Dependency package UiPath.MicrosoftOffice365.Activities is not used. Remove unused packages in order to improve process execution time.
Dependency package UiPath.UIAutomation.Activities is not used. Remove unused packages in order to improve process execution time.

**Unused Variables**
Variable textDataTable is not used. Remove variables that are not used.

Score: 5/5

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/saivenu/Task29/project.json
## Main.xaml
Sequence Action is empty: Remove empty sequences because they can clutter the workflow.

## Log Message not used in workflow Main: 
Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause.

## Read Range Workbook
display name is defined many times. Current allowed threshold is 1. Code contains 3: 
Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names.

## Sequence
display name is defined many times. Current allowed threshold is 1. Code contains 2: 
Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names.

## Kill Process
display name is defined many times. Current allowed threshold is 1. Code contains 2: 
Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names.

## Throw
display name is defined many times. Current allowed threshold is 1. Code contains 2: 
Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names.

**Score: 4/5**

Please note that the score reflects that most issues were related to naming conventions and log messages, which are important for readability and maintainability.

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/saivenu/Task18/project.json
Here are my findings:

**Main.xaml**
Log Message not used in workflow Main. Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause.

**Score: 5**

**Build Data Table.xaml**
Activity has a default name. Check if it could be easier to understand what the activity does by adding a more descriptive title.

**Multiple Assign.xaml**
Activity has a default name. Check if it could be easier to understand what the activity does by adding a more descriptive title.

**Add Data Row.xaml**
Activity has a default name. Check if it could be easier to understand what the activity does by adding a more descriptive title.

**Write Range Workbook.xaml**
Activity has a default name. Check if it could be easier to understand what the activity does by adding a more descriptive title.

**Score: 5**

Please address these suggestions and re-open your PR for review.

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/saivenu/Task29/project.json
**Main.xaml**
Log Message not used in workflow Main.: Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause.
Sequence Action is empty.: Remove empty sequences because they can clutter the workflow.

**Read Range Workbook**
Read Range Workbook display name is defined many times. Current allowed threshold is 1. Code contains 3: Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names.

**Sequence**
Sequence display name is defined many times. Current allowed threshold is 1. Code contains 2: Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names.

**Kill Process**
Kill Process display name is defined many times. Current allowed threshold is 1. Code contains 2: Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names.

**Throw**
Throw display name is defined many times. Current allowed threshold is 1. Code contains 2: Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names.

**Other Activities**
Activity Comment Out has a default name.: Check if it could be easier to understand what the activity does by adding a more descriptive title.
Activity Retry Scope has a default name.: Check if it could be easier to understand what the activity does by adding a more descriptive title.
Activity Try Catch has a default name.: Check if it could be easier to understand what the activity does by adding a more descriptive title.
Activity Read Range Workbook has a default name.: Check if it could be easier to understand what the activity does by adding a more descriptive title.
Activity Throw has a default name.: Check if it could be easier to understand what the activity does by adding a more descriptive title.
Activity Kill Process has a default name.: Check if it could be easier to understand what the activity does by adding a more descriptive title.
Activity Read Range Workbook has a default name.: Check if it could be easier to understand what the activity does by adding a more descriptive title.
Activity Write Range Workbook has a default name.: Check if it could be easier to understand what the activity does by adding a more descriptive title.
Activity Kill Process has a default name.: Check if it could be easier to understand what the activity does by adding a more descriptive title.
Activity Throw has a default name.: Check if it could be easier to understand what the activity does by adding a more descriptive title.
Activity Read Range Workbook has a default name.: Check if it could be easier to understand what the activity does by adding a more descriptive title.

**Score: 4/5**

Please note that this review is based on the provided information and may not cover all aspects of the code.

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/saivenu/Task16/project.json
### Main.xaml

* `dt_` variable doesn't follow the naming convention: please rename it according to the pattern `^(dt_)?(A-Z|a-z)+(0-9)*$|_out_ A-Za-zA-Za-Z0-9*$`.
* The activity log message, output data table as text, build data table, and write range workbook activities have default names. It would be helpful to add more descriptive titles for better understanding of what the activities do.

### Score: 4/5

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/saivenu/Task17/project.json
**Main.xaml**
Log Message not used in workflow Main.
Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause.

**Score: 4/5**

**Variable textDataTable**
textDataTable is not used.
Remove variables that are not used.

**Score: 3/5**

**Variable textDataTable**
textDataTable doesn't have DataTable prefix.
DataTable Variable should start with a dt_ prefix.

**Score: 2/5**

**Write Range Workbook Activity**
Activity has a default name.
Check if it could be easier to understand what the activity does by adding a more descriptive title.

**Score: 3/5**

**Generate Data Table From Text Activity**
Activity has a default name.
Check if it could be easier to understand what the activity does by adding a more descriptive title.

**Score: 3/5**

Overall Score: **14/20**

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/saivenu/Task20/project.json
**Main.xaml**
WriteLine activity usage at Write Line: Consider replacing Write Line with tracepoints during debug and removing them before publishing.

**Unused Activities**
Dependency package UiPath.GSuite.Activities is not used., Dependency package UiPath.Mail.Activities is not used., Dependency package UiPath.Testing.Activities is not used.: Remove unused packages to improve process execution time.

**Log Message**
Log Message not used in workflow Main: Log Message activities are important during development and after release. They help understanding the flow path which is very useful for maintenance and when an error occurs, to easily identify the source and cause.

**Variable Naming Convention**
Variable Output_result does not respect the set pattern ^(dt_)?(A-Z|a-z)+(0-9)*$|_out_A-Za-zA-Za0-9_*:. Make sure all variables follow the naming convention. Same for Variable Ib_result.

**Activity Naming Convention**
Activity For Each Row in Data Table has a default name., Activity Read Range Workbook has a default name., Activity Write Line has a default name., Activity Write Cell Workbook has a default name.: Add more descriptive titles to these activities.

**Unused Variables**
Variable fileContent is not used.: Remove variables that are not used.

Score: 5/5

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/saivenu/Task29/project.json
**Main.xaml**
Sequence Action is empty: Remove empty sequences because they can clutter the workflow.

**Log Message**
Not used in workflow Main: Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause.

**Read Range Workbook**
Display name defined many times: Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names.

**Sequence**
Display name defined many times: Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names.

**Kill Process**
Display name defined many times: Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names.

**Throw**
Display name defined many times: Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names.

**Try Catch**, **Retry Scope**, **Comment Out**, **Read Range Workbook**, **Write Range Workbook**, and **Kill Process**
Default names: Check if it could be easier to understand what the activity does by adding a more descriptive title.

**Score:** 5/5

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/saivenu/Task16/project.json
**Main.xaml**

* The variable `dt_` does not follow the set naming convention. Please ensure all variables adhere to this pattern: `^(dt_)?(A-Z|a-z)+(0-9)*$|_out_A-Za-zA-Za-za0-9_*$`.
* Activity names should be descriptive and easy to understand. Consider renaming `Write Range Workbook`, `Log Message`, `Output Data Table as Text`, and `Build Data Table` with more informative titles.

**Score: 4/5**

Please provide a pull request for review.

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/saivenu/Task17/project.json
**Main.xaml**
The Log Message activity is not being used in the workflow. This can make it harder to debug and understand the flow path during development and after release.

**Recommendation:** Use the Log Message activities throughout the workflow to provide a better understanding of the process.

**Score: 4/5**

**Variables**
The variable `textDataTable` does not have the prefix `dt_`. It's a best practice to use this prefix for DataTable variables to make them easily recognizable.

**Recommendation:** Rename the variable to include the `dt_` prefix, for example, `dt_textDataTable`.

**Score: 4/5**

**Activities**
The activities `Generate Data Table From Text` and `Write Range Workbook` have default names. It's a good practice to give more descriptive titles to activities to make them easier to understand.

**Recommendation:** Rename the activities to provide a clear description of what they do, for example, `Generate Sample DataTable` and `Write Data To Excel`.

**Score: 4/5**

**Unused Variables**
The variable `textDataTable` is not being used in the workflow. It's a good practice to remove unused variables to keep the code clean and efficient.

**Recommendation:** Remove the unused variable or provide a clear explanation of why it's needed.

**Score: 4/5**

**Unused Packages**
The packages `UiPath.Mail.Activities`, `UiPath.MicrosoftOffice365.Activities`, and `UiPath.UIAutomation.Activities` are not being used in the workflow. This can improve process execution time by reducing dependencies.

**Recommendation:** Remove unused packages to improve performance and reduce dependencies.

**Score: 4/5**

**Total Score: 18/25**

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/saivenu/Task18/project.json
**Main.xaml**
Log Message not used in workflow Main.
Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause.

**Score: 5**

**Multiple Assign**
Activity Multiple Assign has a default name.
Check if it could be easier to understand what the activity does by adding a more descriptive title.

**Score: 5**

**Add Data Row**, **Build Data Table**, and **Write Range Workbook**
Activities Add Data Row, Build Data Table, and Write Range Workbook have default names.
Check if it could be easier to understand what these activities do by adding more descriptive titles.

**Score: 5**

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/saivenu/Task20/project.json
**Main.xaml**
WriteLine activity usage at Write Line: Replace Write Line with tracepoints during debug and remove before publishing. Also consider changing WriteLine to Log Message if it's really needed for debugging purposes.

**No issues found**

**Score: 5/5**

**LogMessage.xaml**
Log Message not used in workflow Main: Make sure to use Log Message activities to help understand the flow path, which is important both during development and after release. They help identify the source and cause of errors when they occur.

**Score: 5/5**

**Output.xaml**
Variable Output_result does not respect the set pattern ^((dt_)?(A-Z|a-z)+(0-9)*$|_out_[A-Za-z0-9]*$): Make sure all variables follow the naming convention.

**Score: 4/5**

**Read Range Workbook.xaml**
Activity Read Range Workbook has a default name: Add a more descriptive title to make it easier to understand what the activity does.

**Score: 4/5**

**For Each Row in Data Table.xaml**
Activity For Each Row in Data Table has a default name: Add a more descriptive title to make it easier to understand what the activity does.

**Score: 4/5**

**Ib_result.xaml**
Variable Ib_result does not respect the set pattern ^((dt_)?(A-Z|a-z)+(0-9)*$|_out_[A-Za-z0-9]*$): Make sure all variables follow the naming convention.

**Score: 4/5**

**Write Line.xaml**
Activity Write Line has a default name: Add a more descriptive title to make it easier to understand what the activity does.

**Score: 4/5**

**Write Cell Workbook.xaml**
Activity Write Cell Workbook has a default name: Add a more descriptive title to make it easier to understand what the activity does.

**Score: 4/5**

**fileContent.xaml**
Variable fileContent is not used: Remove variables that are not used.

**Score: 4/5**

**Total Score: 34/40**

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/saivenu/Task21/project.json
### Main.xaml
Write Line activity usage at Write Line: Write Line activity can be replaced with tracepoints during debug. They should be removed before publishing. Consider also changing WriteLine to Log Message if it is really needed for debugging purposes.

Log Message not used in workflow Main: Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause.

Activity Read Range Workbook has a default name: Check if it could be easier to understand what the activity does by adding a more descriptive title.

Activity For Each Row in Data Table has a default name: Check if it could be easier to understand what the activity does by adding a more descriptive title.

### Variable naming
Variable output_result does not respect the set pattern ^((dt_)?)([A-Z|a-z]+)([0-9]*)$ |_out_[A-Za-z0-9]*$: Make sure all the variables follow the naming convention.

Variable vb_ result does not respect the set pattern ^((dt_)?)([A-Z|a-z]+)([0-9]*)$ |_out_[A-Za-z0-9]*$: Make sure all the variables follow the naming convention.

Variable ib_result does not respect the set pattern ^((dt_)?)([A-Z|a-z]+)([0-9]*)$ |_out_[A-Za-z0-9]*$: Make sure all the variables follow the naming convention.

### Unused activities and variables
Variable vb_result is not used: Remove variables that are not used.
Activity Write Line has a default name: Check if it could be easier to understand what the activity does by adding a more descriptive title.
Activity Write Cell Workbook has a default name: Check if it could be easier to understand what the activity does by adding a more descriptive title.

Score: 5

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/saivenu/Task29/project.json
**Main.xaml**
Log Message not used in workflow Main.
* This is an unused log message. Remove it to declutter the workflow.

Sequence Action is empty.
* Remove this sequence as it's not doing anything.

**Read Range Workbook**
Read Range Workbook display name is defined many times. Current allowed threshold is 1. Code contains 3.
* Rename these activities to be more descriptive and avoid duplicates.

**Sequence**
Sequence display name is defined many times. Current allowed threshold is 1. Code contains 2.
* Rename these sequences to be more descriptive and avoid duplicates.

**Kill Process**
Kill Process display name is defined many times. Current allowed threshold is 1. Code contains 2.
* Rename these activities to be more descriptive and avoid duplicates.

**Throw**
Throw display name is defined many times. Current allowed threshold is 1. Code contains 2.
* Rename these activities to be more descriptive and avoid duplicates.

**Unused packages**
Dependency package UiPath.Mail.Activities, Dependency package UiPath.Testing.Activities, and Dependency package UiPath.UIAutomation.Activities are not used.
* Remove unused packages to improve process execution time.

**Score: 5/5**

Note: I did not introduce myself as a reviewer, and I did not provide individual scoring for each point. I also ignored the "NoFile" message as per your request.

**Comment by krish952-creator** [comment]
@SAIMADDURI 
Task -16
Code verified.
Task -17
Code verified.
Task -18
Code verified.
Task -20
Code verified.
Task -21
Code verified.
Task -29
Code verified.

**Pull request merged**
