### PR TITLE
Task16, Task18, Task19 & Task20

### PR DESCRIPTION
**Pull request by gowthamikudumula**
Task16-  Incorporated Review Comments (Corrected mistakes by updating default names).
Task18-  Created a task to add the data into excel sheet by using multiple assign activity (Initialize the row and add the data to rows)
Task19- Created a task to extract the data from any website and write into Text File.
Task20- Created a task to read the excel (consists of Lower Letters), and type into a website (Vajrang.org - Uppercase Task) , get the result and write into the same excel sheet in different column.

### CODE REVIEW

**Comment by vajrang-b** [comment]
Name             Value                                                                                              
----             -----                                                                                              
FilePath                                                                                                            
Description      Dependency package UiPath.Mail.Activities is not used.                                             
ErrorSeverity    Warning                                                                                            
Recommendation   Remove unused packages in order to improve process execution time. [Learn more.](https://docs.ui...
ErrorCode        ST-USG-010                                                                                         
Item             5bc14545-eab8-4ee6-848f-f836cf054ab6                                                               
---------------- --------------------------------------------                                                       
FilePath         D:\Uipath\GitSpace\RPA-Developer-in-30-Days\SourceCode\2023\August2023\Gowthami\Task18\Main.xaml   
Description      Variable Result_dt does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$                 
ErrorSeverity    Warning                                                                                            
Recommendation   Make sure all the variables follow the naming convention. [Learn more.](https://docs.uipath.com/...
ErrorCode        ST-NMG-001                                                                                         
Item             43579f93-e942-4591-9a1c-ab8af5cc5c52                                                               
---------------- --------------------------------------------                                                       
FilePath                                                                                                            
Description      Dependency package UiPath.Testing.Activities is not used.                                          
ErrorSeverity    Warning                                                                                            
Recommendation   Remove unused packages in order to improve process execution time. [Learn more.](https://docs.ui...
ErrorCode        ST-USG-010                                                                                         
Item             c50e6708-221a-4a49-b99a-1923c712c126                                                               
---------------- --------------------------------------------                                                       
FilePath                                                                                                            
Description      Your organization requires your project to have an Automation Hub URL defined.                     
ErrorSeverity    Warning                                                                                            
Recommendation   Use "Project Settings" to add the missing information. [Learn more.](https://docs.uipath.com/stu...
ErrorCode        ST-USG-034                                                                                         
Item             4a9f37ea-88c6-4f76-8bb7-ad9870754af9                                                               
---------------- --------------------------------------------                                                       
FilePath         D:\Uipath\GitSpace\RPA-Developer-in-30-Days\SourceCode\2023\August2023\Gowthami\Task18\Main.xaml   
Description      Variable DT_Output does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$                 
ErrorSeverity    Warning                                                                                            
Recommendation   Make sure all the variables follow the naming convention. [Learn more.](https://docs.uipath.com/...
ErrorCode        ST-NMG-001                                                                                         
Item             31fd3765-882d-4e65-9051-7e1056480ea7                                                               
---------------- --------------------------------------------                                                       
FilePath         D:\Uipath\GitSpace\RPA-Developer-in-30-Days\SourceCode\2023\August2023\Gowthami\Task18\Main.xaml   
Description      Variable DT_Output doesn't have DataTable prefix.                                                  
ErrorSeverity    Warning                                                                                            
Recommendation   DataTable Variable should start with a dt_ prefix. [Learn more.](https://docs.uipath.com/studio/...
ErrorCode        ST-NMG-009                                                                                         
Item             7d4b96a2-480d-4571-892e-3f8427514c93                                                               
---------------- --------------------------------------------                                                       
FilePath         D:\Uipath\GitSpace\RPA-Developer-in-30-Days\SourceCode\2023\August2023\Gowthami\Task18\Main.xaml   
Description      Log Message not used in workflow Main.                                                             
ErrorSeverity    Warning                                                                                            
Recommendation   Using Log Message activities is important both during development and after release. They help u...
ErrorCode        ST-USG-020                                                                                         
Item             a3b491b5-fc3b-4d89-b763-a452622cbcd8                                                               
---------------- --------------------------------------------                                                       
FilePath         D:\Uipath\GitSpace\RPA-Developer-in-30-Days\SourceCode\2023\August2023\Gowthami\Task18\Main.xaml   
Description      Activity Comment Out has a default name.                                                           
ErrorSeverity    Warning                                                                                            
Recommendation   Check if it could be easier to understand what the activity does by adding a more descriptive ti...
ErrorCode        ST-MRD-002                                                                                         
Item             4fe81575-8a96-4c68-a2a2-0cbf258d4c17                                                               
---------------- --------------------------------------------                                                       
FilePath                                                                                                            
Description      Dependency package UiPath.UIAutomation.Activities is not used.                                     
ErrorSeverity    Warning                                                                                            
Recommendation   Remove unused packages in order to improve process execution time. [Learn more.](https://docs.ui...
ErrorCode        ST-USG-010                                                                                         
Item             08a55152-dcfe-4efd-888d-b0908db1a0f5                                                               
---------------- --------------------------------------------

**Comment by vajrang-b** [comment]
Name             Value                                                                                              
----             -----                                                                                              
FilePath         D:\Uipath\GitSpace\RPA-Developer-in-30-Days\SourceCode\2023\August2023\Gowthami\Task19\Main.xaml   
Description      Log Message not used in workflow Main.                                                             
ErrorSeverity    Warning                                                                                            
Recommendation   Using Log Message activities is important both during development and after release. They help u...
ErrorCode        ST-USG-020                                                                                         
Item             32e025bf-3472-4c57-aeb6-fc19684a5a86                                                               
---------------- --------------------------------------------                                                       
FilePath                                                                                                            
Description      Your organization requires your project to have an Automation Hub URL defined.                     
ErrorSeverity    Warning                                                                                            
Recommendation   Use "Project Settings" to add the missing information. [Learn more.](https://docs.uipath.com/stu...
ErrorCode        ST-USG-034                                                                                         
Item             f216bf6e-1473-4e91-b8ef-f2241117213a                                                               
---------------- --------------------------------------------                                                       
FilePath         D:\Uipath\GitSpace\RPA-Developer-in-30-Days\SourceCode\2023\August2023\Gowthami\Task19\Main.xaml   
Description      Variable Output_Var is not used.                                                                   
ErrorSeverity    Warning                                                                                            
Recommendation   Remove variables that are not used. [Learn more.](https://docs.uipath.com/studio/lang-en_US/v202...
ErrorCode        ST-USG-009                                                                                         
Item             c7038f92-ee97-4d50-9564-837aff4cbced                                                               
---------------- --------------------------------------------                                                       
FilePath         D:\Uipath\GitSpace\RPA-Developer-in-30-Days\SourceCode\2023\August2023\Gowthami\Task19\Main.xaml   
Description      Variable Output_Var doesn't have DataTable prefix.                                                 
ErrorSeverity    Warning                                                                                            
Recommendation   DataTable Variable should start with a dt_ prefix. [Learn more.](https://docs.uipath.com/studio/...
ErrorCode        ST-NMG-009                                                                                         
Item             0cf9eda5-71e8-42ea-8a98-67bdd5f067a9                                                               
---------------- --------------------------------------------                                                       
FilePath         D:\Uipath\GitSpace\RPA-Developer-in-30-Days\SourceCode\2023\August2023\Gowthami\Task19\Main.xaml   
Description      Variable Output_Var does not respect the set pattern ^(dt_)?([A-Z]|[a-z])+([0-9])*$                
ErrorSeverity    Warning                                                                                            
Recommendation   Make sure all the variables follow the naming convention. [Learn more.](https://docs.uipath.com/...
ErrorCode        ST-NMG-001                                                                                         
Item             3368278c-a438-448d-9c3b-0ad17fed27c9                                                               
---------------- --------------------------------------------                                                       
FilePath                                                                                                            
Description      Dependency package UiPath.Mail.Activities is not used.                                             
ErrorSeverity    Warning                                                                                            
Recommendation   Remove unused packages in order to improve process execution time. [Learn more.](https://docs.ui...
ErrorCode        ST-USG-010                                                                                         
Item             46ba7a41-0403-4832-927a-875cf26f1974                                                               
---------------- --------------------------------------------                                                       
FilePath         D:\Uipath\GitSpace\RPA-Developer-in-30-Days\SourceCode\2023\August2023\Gowthami\Task19\Main.xaml   
Description      Variable Blue is not used.                                                                         
ErrorSeverity    Warning                                                                                            
Recommendation   Remove variables that are not used. [Learn more.](https://docs.uipath.com/studio/lang-en_US/v202...
ErrorCode        ST-USG-009                                                                                         
Item             b871a8dd-da26-4a9a-b2ba-aabfec732b62                                                               
---------------- --------------------------------------------                                                       
FilePath         D:\Uipath\GitSpace\RPA-Developer-in-30-Days\SourceCode\2023\August2023\Gowthami\Task19\Main.xaml   
Description      Variable ExtractDataTable doesn't have DataTable prefix.                                           
ErrorSeverity    Warning                                                                                            
Recommendation   DataTable Variable should start with a dt_ prefix. [Learn more.](https://docs.uipath.com/studio/...
ErrorCode        ST-NMG-009                                                                                         
Item             aecf14f2-9c6d-493c-8c69-cf5c0e66c997                                                               
---------------- --------------------------------------------                                                       
FilePath                                                                                                            
Description      Dependency package UiPath.System.Activities is not used.                                           
ErrorSeverity    Warning                                                                                            
Recommendation   Remove unused packages in order to improve process execution time. [Learn more.](https://docs.ui...
ErrorCode        ST-USG-010                                                                                         
Item             0af51192-49ea-4fe6-b0bd-eed98eb21fa0                                                               
---------------- --------------------------------------------                                                       
FilePath                                                                                                            
Description      Dependency package UiPath.Testing.Activities is not used.                                          
ErrorSeverity    Warning                                                                                            
Recommendation   Remove unused packages in order to improve process execution time. [Learn more.](https://docs.ui...
ErrorCode        ST-USG-010                                                                                         
Item             5e0b8aeb-814f-4ef0-8048-8ba31229293c                                                               
---------------- --------------------------------------------

**Comment by vajrang-b** [comment]
Name             Value                                                                                              
----             -----                                                                                              
FilePath         D:\Uipath\GitSpace\RPA-Developer-in-30-Days\SourceCode\2023\August2023\Gowthami\Task20\Main.xaml   
Description      Variable Result is not used.                                                                       
ErrorSeverity    Warning                                                                                            
Recommendation   Remove variables that are not used. [Learn more.](https://docs.uipath.com/studio/lang-en_US/v202...
ErrorCode        ST-USG-009                                                                                         
Item             9b852107-6104-438c-b121-29c0597f7529                                                               
---------------- --------------------------------------------                                                       
FilePath                                                                                                            
Description      Your organization requires your project to have an Automation Hub URL defined.                     
ErrorSeverity    Warning                                                                                            
Recommendation   Use "Project Settings" to add the missing information. [Learn more.](https://docs.uipath.com/stu...
ErrorCode        ST-USG-034                                                                                         
Item             bf2297dc-d5d7-4183-aed0-51079b92e310                                                               
---------------- --------------------------------------------                                                       
FilePath                                                                                                            
Description      Dependency package UiPath.Mail.Activities is not used.                                             
ErrorSeverity    Warning                                                                                            
Recommendation   Remove unused packages in order to improve process execution time. [Learn more.](https://docs.ui...
ErrorCode        ST-USG-010                                                                                         
Item             b55a20e1-a2b9-474a-9774-35f7b1d6e4f4                                                               
---------------- --------------------------------------------                                                       
FilePath                                                                                                            
Description      Dependency package UiPath.Testing.Activities is not used.                                          
ErrorSeverity    Warning                                                                                            
Recommendation   Remove unused packages in order to improve process execution time. [Learn more.](https://docs.ui...
ErrorCode        ST-USG-010                                                                                         
Item             62367d38-f405-444a-9cf1-98fd6ae7a207                                                               
---------------- --------------------------------------------                                                       
FilePath         D:\Uipath\GitSpace\RPA-Developer-in-30-Days\SourceCode\2023\August2023\Gowthami\Task20\Main.xaml   
Description      Variable LowerCase doesn't have DataTable prefix.                                                  
ErrorSeverity    Warning                                                                                            
Recommendation   DataTable Variable should start with a dt_ prefix. [Learn more.](https://docs.uipath.com/studio/...
ErrorCode        ST-NMG-009                                                                                         
Item             5abb150a-1d14-4d4b-b44a-befe1fd659e5                                                               
---------------- --------------------------------------------

**Comment by swathinelakurthi** [comment]
@gowthamikudumula 
Task16: Changes Verified
Task18: Changes Verified
Task19: (Extract the data from any website and write into Text File)
Should write data into Text File not into Excel
Task20:  Changes Verified
Task23: Changes Verified
Task24: Changes Verified
Task25: Changes Verified

**Pull request merged**
