### PR TITLE
Task10

### PR DESCRIPTION
**Pull request by ShashiRPA**

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Shashi/Tak10/project.json
# Comments for NoFile

1. Your project lacks an Automation Hub URL. Go to 'Project Settings' to fix this.

2. You've got unused packages like UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities. This slows down task running. Remove 'em.

# Comments for Main.xaml

1. I don't see any 'Log Message' in 'Main' workflow. They're handy during development and maintenance. Helps figure out source of errors. Include some.

2. The name 'MessageBox' is overused, 5 times. Aim for unique names; they're less confusing. Correct this.

3. The 'Input Dialog' activity keeps its default name. Make it descriptive, it's easier to understand.

4. Same issue for the 'Switch' activity. Work on its name too.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Shashi/Task12/project.json
For the `NoFile`:

1. Missing Automation Hub URL: In the "Project Settings", add the Automation Hub URL.
2. Unnecessary Packages: You have included packages in your project that aren't being used. Get rid of these as they might slow things down. Unused packages includes: UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.System.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities.

For `Main.xaml`:

1. Missing Log Message: Start using 'Log Message' activities. They are good for debugging and understanding the workflow, especially when things go wrong.
2. Empty Main File: Unless you need an empty file, delete it. Save some space.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Shashi/Task13/project.json
**NoFile**

1. **Automation Hub URL is missing.** Add it under Project Settings.
2. **Unused dependency packages.** UiPath.Mail.Activities, UiPath.System.Activities, UiPath.Testing.Activities, UiPath.UIAutomation.Activities are not used. Removing unused packages improves process run time.

**Main.xaml**

1. **Log Message not used.** Helps a lot during development and error handling. Recommend to use it.
2. **Unused variable Dt_Data.** Remove it to keep the workflow tidy.
3. **Redundant sequence Sequence.** You don't need it. Removing such sequences makes workflow less cluttered. Use Remove Surrounding Sequence option of the Context Menu in UiPath Studio.
4. **Issue with variable Dt_Data.** DataTable Variables should start with a dt_ prefix. Make sure naming convention is respected: ^(dt_)?([A-Z]|[a-z])+([0-9])*$.
5. **Issue with variable Dt_data1.** Remember our naming convention: DataTable Variables should start with a dt_ prefix. Respect pattern: ^(dt_)?([A-Z]|[a-z])+([0-9])*$.

**Comment by vajrang-b** [comment]
SourceCode/2023/Sep2023/Basics/Shashi/Task14/project.json
Under "NoFile":

1. Mate, you need to add your Automation Hub URL in your project settings. It's a must.
2. I see a lot of packages that you're not using - UiPath.Excel.Activities, UiPath.Mail.Activities, UiPath.System.Activities, UiPath.Testing.Activities, and UiPath.UIAutomation.Activities. Get rid of them. Your process will run faster.

Under "Main.xaml":

1. Use the Log Message in your Main workflow. This helps understand what's going on during development and makes it easier to find and fix errors after release.

**Comment by krish952-creator** [comment]
@ShashiRPA 
Update tracker with PR number in respective tasks
Task -10
Code Verified. Default activity names and give annotations
Task -12&14
Empty file and no code on( Main.xmal)
Task -13
Find the differences between excel and workbook
You used only excel activity and need to use workbook activity also. Check it

**Pull request merged**
