### PR TITLE
task 31 to task 34

### PR DESCRIPTION
**Pull request by hasini94D**

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2024/Basics-April2024/hasini/task 31/project.json
**Main.xaml**
The workflow should include log messages to help with understanding the flow and identifying errors during development and maintenance.

**Variables.xaml**
The `mail_messages` variable does not follow the naming convention. Please ensure that all variables respect the pattern `(dt_)?(A-Z|a-z)+(0-9)*$|_out_A-Za-zA-Za-z0-9_*`.

**Activities.xaml**
The following activities have default names:
* Get Password: Consider adding a more descriptive title to make it easier to understand what the activity does.
* Get IMAP Mail Messages: Consider adding a more descriptive title to make it easier to understand what the activity does.
* Message Box: Consider adding a more descriptive title to make it easier to understand what the activity does.
* For Each: Consider adding a more descriptive title to make it easier to understand what the activity does.

**Score: 4/5**

Note: I've grouped the issues based on file names, and provided a score at the end without individual scoring.

**Comment by vajrang-b** [comment]
SourceCode/2024/Basics-April2024/hasini/task 32/project.json
**Main.xaml**
We have some nice log messages in here, but we're not using them! Log messages are super helpful for understanding how our workflow flows (pun intended). They can help us identify where an error occurred or make it easier to maintain the code. Can you add more log messages throughout the workflow?

**Assign display name is defined many times**
We have a lot of activities with default names. That's okay, but we should try to give them more descriptive titles so it's clear what each activity does. For example, instead of "Assign", maybe something like "Set User Information"? We're using this activity 3 times, so let's rename one or all of them to make the code easier to read.

**Activity Assign**
This activity has a default name... Can you add a more descriptive title? For example, "Assign User Credentials"?

**Activity Get Password**
Same here! Can you give it a more descriptive title like "Get Login Credentials"?

**Activity Get IMAP Mail Messages**
How about something like "Fetch Email Messages"?

**Activity Build Data Table**
What does this activity do? Maybe something like "Create User Information Table"?

**Activity For Each**
This one has a default name... What's the purpose of this loop? Can you give it a more descriptive title like "Process All Users"?

**Activity Assign (x2)**
Same as before! Let's rename these to make the code clearer.

**Activity Add Data Row**
What does this activity do? Maybe something like "Insert User Information into Table"?

Score: 4/5

**Comment by vajrang-b** [comment]
SourceCode/2024/Basics-April2024/hasini/task 33/project.json
```
**Main.xaml**
Workflow `Main` should include log messages for better understanding and debugging purposes.
```



```
**Argument argument1**
The naming convention for arguments should be followed. The pattern is `^in_(dt_)?(A-Z|a-z)+(0-9)*$`.
```



```
**Variable pdf_file**
The variable `pdf_file` does not follow the set naming convention. The pattern is `^(dt_)?(A-Z|a-z)+(0-9)*$|_out_A-Za-zA-Za-z0-9_*$. 
```



```
**Activity Send SMTP Mail Message, Activity Assign, and Activity Get Password**
These activities should have more descriptive titles for better understanding of what they do.
```



```
**Variable pdf_file is not used**
Remove variables that are not used to declutter the code and improve readability.
```


Score: 5/5

**Comment by krish952-creator** [comment]
@hasini94D 
Task -31
Code verified.
Task -32
Code verified.
Task -33
Code verified.
Task -34
Code verified.

**Pull request merged**
