### PR TITLE
Task 019,020,021,022

### PR DESCRIPTION
**Pull request by Sudheer2331**
Task completed with all the parameters plz do check

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Sudheer Devabattula/Task019/project.json
File - NoFile
1. You need to add the Automation Hub URL through Project Settings.
2. The UiPath.Excel.Activities package isn't being used. Get rid of it to boost the speed of your process.

Score:
Code Completion - 1.5
Execution - 1.5
Annotations and Comments - 0.5

File - Main.xaml
1. The sequences "Extracting data from a website" and "Datascraping from a website" are extra. Remove them to simplify your workflow. Follow these steps: right-click > Remove Surrounding Sequence.
2. "Data Converting Task" and "Do" are displaying too many times. Use unique and explicit names for clarity.
3. Prefix your DataTable variable "ExtractDataTable" with "dt_" for consistency.

Score:
Code Completion - 1
Execution - 1
Annotations and Comments - 0.5

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Sudheer Devabattula/Task020/project.json
For file: NoFile
1. Please add the Automation Hub URL to your project settings. Your organization needs this.
2. You've included the UiPath.Testing.Activities package but it doesn't look like you're using it. Removing it could help your process run faster.

For file: Main.xaml
1. I noticed "Uppercase to Lowercase" sequence is redundant. Redundant sequences can make the workflow unclear. You can remove it with the "Remove Surrounding Sequence" option.
2. The display name "Information" is used more than once, it's better to have unique names for better understanding what each part is doing. Please change it.
3. The variable 'inputdata' should be prefixed with 'dt_' as it's a DataTable. This helps keep things clear.

Scores (Out of 2 for code completion and execution, 1 for annotations and comments):
Code completion: 1.5
Execution: 1.5
Annotations and Comments: 0.5

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Sudheer Devabattula/Task022/project.json
For "NoFile":
1) Your project is missing an Automation Hub URL definition. In the "Project Settings", please input this information.
Score: Code completion 1/2, Execution 1/2, annotations and comments 1/1

2) The UiPath.Testing.Activities package isn't utilized. To improve process runtime, please eliminate unused packages.
Score: Code completion 2/2, Execution 2/2, annotations and comments 1/1

For "Main.xaml":
1) The sequence "Uppercase lowercase using builddatatable" isn't necessary. Avoid redundancy to keep your workflow concise. Remove these sequences through the UiPath Studio's Context Menu's "Remove Surrounding Sequence" option.
Score: Code completion 1/2, Execution 1/2, annotations and comments 0/1

2) You've repetitively defined the display name "information". The allowed limit is 1 but currently, there are 2 instances. For the sake of clarity, avoid duplicate names and generic default names.
Score: Code completion 1/2, Execution 1/2, annotations and comments 0/1

3 and 4) Variables "Output_data" and "input" don

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Sudheer Devabattula/Task019/project.json
**Main.xaml**

1. Your sequences 'Extracting data from a website' and 'Datascraping from a website' appear to be doing the same thing. Cut one of them out. Otherwise, it just makes your workflow confusing.  
2. You've defined 'Data Converting Task' and 'Do' twice. Try to make your names more specific to avoid duplicates.
3. Your 'ExtractDataTable' variable needs to start with 'dt_'. Change it!

**Score:**
Code Completion: 1.5/2
Execution: 1/2
Annotations and Comments: 0.5/1

**NoFile**
1. Seems like you're missing an Automation Hub URL in your project settings. Get that fixed in the "Project Settings".

**Score:**  
Code Completion: -/2
Execution: -/2
Annotations and Comments: -/1

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Sudheer Devabattula/Task020/project.json
**Main.xaml:**

1. Sequence 'Uppercase to Lowercase' is redundant. Simply unnecessary - cut it out. In UiPath Studio, you've got an option 'Remove Surrounding Sequence' in the Context Menu. Use that.
    
2. 'Information' display name is a repeat offender here. You've used it twice - we only allow it once. Make sure activity names actually tell us what they're doing. Don't just stick with the defaults - they're usually too vague. No duplicates, please.
    
3. 'inputdata' falls short. DataTable Variables should start with a 'dt_' prefix. It's missing here.

**NoFile:**

1. Your project doesn't have an Automation Hub URL. Your outfit insists on it. Go to 'Project Settings', and stick it in there.

Scores: Code Completion - 1, Execution - 2, Annotations & Comments - 1.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Sudheer Devabattula/Task019/project.json
- Main.xaml
1. Extracting data from a website: This is repeated and unneeded. Delete it. Make the process simpler.
2. Data scraping from the website: This is also a repeat and not required. Remove it.
3. Data Converting Task: You're using this name too many times. You used it twice. Use it once to avoid confusion.
4. Do: This name is also repeated twice. Try to only use it once for clarity.
5. ExtractDataTable: Add a 'dt_' at the start of this variable. This rule needs to be followed for DataTable type variables.

- NoFile
1. Your project is missing an Automation Hub URL. Go to Project Settings and put it in.

Now let's talk about the score. 

1. Code completion: 1 out of 2. The code you wrote has some repeated and unneeded steps. Try to write cleaner and more efficient code.
2. Execution: 2 out of 2. Your code works and does what it should. Good job on that.
3. Annotations and comments: 0 out of 1. Your code is missing comments or explanations that would make it easier to understand. 

You should remember to always make your code simple and easy to

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Sudheer Devabattula/Task020/project.json
Main.xaml

1. The sequence Uppercase to Lowercase is redundant. Simpler is always better. More sequences clutter up the workflow. You can get rid of redundant sequences by using the Remove Surrounding Sequence option of the Context Menu in UiPath Studio.

2. You've defined Information display name multiple times. Currently, you've done this two times, but you should only do it once. Activity names need to be more specific to their function. Generic default names won't cut it. Stop duplicating names.

3. The variable inputdate isn't prefixed with DataTable. Try using the prefix dt_.

Score: Completion 1, Execution 1, Annotations and comments 0.

NoFile

1. Your project is supposed to have an Automation Hub URL according to your organization's rules. Go to "Project Settings" and add the missing details.

Score: Completion 0, Execution 0, Annotations and comments 0.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Sudheer Devabattula/Task022/project.json
## Main.xaml

1. The sequence `Uppercase lowercase using builddatatable` seems to be redundant. Such sequences just add clutter to your workflow. To avoid this, use the 'Remove Surrounding Sequence' option from the context menu in UiPath Studio.

2. The display name 'information' is declared multiple times in your workflow (currently 2 times). Make sure the names of your activities are unique and give a clear indication of what they're doing.

3. The variable `Output_data` lacks the `DataTable` prefix. Following a naming convention enhances readability and understanding of the code. Please rename the variable with 'dt_' prefix.

4. Same goes for the variable `input`. It should also start with 'dt_'.

5. The variable `Output_data` does not follow the set pattern `^(dt_)?([A-Z]|[a-z])+([0-9])*$`. Please revise the variable name to follow this pattern.

## NoFile

6. Your project is required to have an Automation Hub URL defined according to your organization's preferences. To add this, go to 'Project Settings'.

**Review Score**
- Code Completion: 1/2 (Main points 1,3,4,5 need attention

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Sudheer Devabattula/Task023/project.json
# PR Review Summary

Observations and suggested solutions are as follows:

### General  
1. **Automation Hub URL is undefined.** Define it in "Project Settings". 

2. **Unused package `UiPath.UIAutomation.Activities`.** Unused packages may slow down process execution. Remove any you're not using.

### Main.xaml
1. **The workflow `Main` does not use Log Message.** These can help understand the flow path which is useful for maintenance and for finding errors. Consider using Log Message activities.

2. **The sequence `Data Manupulation using strings` is redundant.** Redundant sequences just make the workflow cluttered. Use the `Remove Surrounding Sequence` option in the context menu of UiPath Studio to remove it.

# Ratings (out of 2)
* **Code Completion** - 1.5
* **Execution** - 1.5
* **Annotations and Comments** - 0.5

# Note
Your project needs polishing. Please make adjustments to reflect these recommendations.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Sudheer Devabattula/Task019/project.json
Score:
- Code Completion: 1.5/2 - Most of the code seems fine, but there are redundant sequences and duplicate activity names, which you should avoid.
- Execution: 2/2 - No info provided to score this aspect.
- Annotations and Comments: 0.5/1 - There seems to be lack of annotations and comments.

GitHub Comments:
- Main.xaml:
1. The sequences 'Extracting data from a website' and 'Datascraping from a website' seem redundant. Remove it to tidy work flow.
2. You've used 'Data Converting Task' and 'Do', these display names, more than once. Try to use unique names to avoid confusion.
3. Prefix your DataTable variable 'ExtractDataTable' with 'dt_'.

- No File:
1. It seems your project is missing an Automation Hub URL. Go to 'Project Settings' to add this info.
   
Apply above changes to improve your code.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Sudheer Devabattula/Task020/project.json
# Main.xaml

### Review Points:

**1)** There is a sequence named 'Uppercase to Lowercase'. You've used it multiple times which is redundant and makes the code cluttered. 

**Solution:** Remove the surrounding sequences that are not needed. You can achieve this by using the 'Remove Surrounding Sequence' option from the context menu in UiPath Studio.

**Score: 1/2**

**2)** It appears that you have defined 'Information' display name more than once. Remember, you should only define it once. 

**Solution:** It's important to use unique and descriptive names for your activities. This makes your code easy to understand. So, avoid using duplicate names.

**Score: 1/2**

**3)** I noticed that the variable 'inputdata' doesn't have the DataTable prefix 'dt_'. 

**Solution:** DataTable variables should start with 'dt_'. Renaming 'inputdata' to 'dt_inputdata' should solve this problem.

**Score: 1/2**

## Execution: 1.5/2
## Code Completion: 1/2
## Annotations and Comments: 0.5/1

# NoFile

### Review Points:

**1)** Your project

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Sudheer Devabattula/Task021/project.json
Score:

Code Completion: 1.5/2 - Remove redundant sequences and unused packages to enhance the performance.

Execution: 1.5/2 - Default names are too generic, avoid duplicate names and maintaining naming conventions enhances the project execution.

Annotations and Comments: 0.5/1 - Lack of annotations and Comments, reduces the understandability of your code. Make sure you use enough comments for each complex task.

So, the overall score: 3.5/5

# Review:

## Main.xaml

- **Issue-1**: Several sequences such as 'Temparatures of the cities' and 'Data scraping' are redundant and clutter the workflow. Not necessary, cut them out.
  - **Solution**: Delete these sequences, they are not helping.

- **Issue-2**: You are repeating activity names like 'Task021' & 'Do'. Be unique!
  - **Solution**: Rename those activities, ensure each name is different and reflects what actually takes place in that activity.

- **Issue-3**: I noticed that the variable 'ExtractDataTable' doesn't use the 'dt_' prefix.
  - **Solution**: Rename 'ExtractDataTable' to 'dt_ExtractDataTable'. Always start your DataTable variables with 'dt_'.

##

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Sudheer Devabattula/Task022/project.json
Score:

Code Completion: 1.5, Execution: 1.5, Annotations and Comments: 0.5

Comments:

Main.xaml:
- There seems to be a redundant sequence used ("Uppercase lowercase using builddatatable"). Turn to using the 'Remove Surrounding Sequence' option in the UiPath Studio.
- Your activity name 'information display' duplicates. Please rename the activity to make it precise.
- Both 'Output_data' and 'input' variables do not have the DataTable prefix 'dt_'. Please add it before the variable names.
- Naming conventions are key. You are not following them diligently. Variable 'Output_data' is an example.

NoFile:
- Project lacks an Automation Hub URL. Go to your 'Project Settings' and mend this.

Please do fix these issues. I reckon they should help improve your code quality.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Sudheer Devabattula/Task023/project.json
## Scores

- Code Completion: 1.5/2
- Code Execution: 2/2
- Annotations and comments: 0.5/1

## File: NoFile

- Your project currently has no Automation Hub URL defined, this could be in breach of your organization's requirements. To solve this, go to "Project Settings" and add the necessary info. 
- It appears that the UiPath.UIAutomation.Activities dependency package is not being used. To improve process execution time, unnecessary packages should be removed.

## File: Main.xaml

- I've noticed that there are no Log Message activities used in the Main workflow. They are crucial for the development and debugging stages as they help you understand the flow and find errors easily. Please consider including them.
- The sequence "Data Manupulation using strings" appears to be redundant. It's recommended to avoid using redundant sequences as they can make the workflow cluttered and more difficult to read. Please remove unnecessary sequences by using the Remove Surrounding Sequence option in the Context Menu in UiPath Studio.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Sudheer Devabattula/Task024/project.json
## Review Scores: 

- **Code Completion**: 1.5/2 
- **Execution**: 1.5/2 
- **Annotations and Comments**: 0.5/1 

## Review Comments:

### NoFile: 
1. You've missed the Automation Hub URL in project settings. Go to 'Project Settings' and fix this.
2. You've added 'UiPath.Testing.Activities' and 'UiPath.UIAutomation.Activities' packages but they're not being used. This increases process execution time. Just remove them.

### Main.xaml:
1. You've used a WriteLine activity at Output1 and Output. It's better to replace WriteLine with tracepoints during debugging, and remove them before publishing. If needed, use Log Message for debugging purposes.
2. 'Replacing words' sequence is redundant which causes workflow clutter. To clean this up, remove the surrounding sequence using the Context Menu in UiPath Studio.
3. The name 'Task024' is used multiple times here. Each activity should have a clear, unique name. Please avoid duplicate names.

**Comment by krish952-creator** [comment]
@Sudheer2331 
Task -19
Code verified. 
Task -20
Code verified. 
Task -21
Need to change the code and check the output.
Task -22
Code verified. 
Task -23
Code verified. 
Task -24
Code verified.

**Pull request merged**
