### PR TITLE
Task 16

### PR DESCRIPTION
**Pull request by Bhavyajetty2**
Build the DataTable and write in the Excel.

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Bhavya/Task 16/project.json
**Main.xaml**
Variable `Result` does not respect the set pattern `^(dt_)?(A-Z|a-z)+(0-9)*$|_out_[A-Za-z0-9]*$. Make sure all the variables follow the naming convention.

**Please re-name the variable to something like `dt_Result` or `_out_Result`**

**Variable Marks_Result does not respect the set pattern ^((dt_)?(A-Z|a-z)+(0-9)*$|_out_[A-Za-z0-9]*$**: Make sure all the variables follow the naming convention.

**Please re-name the variable to something that follows the pattern**

4/5

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Bhavya/Task 16/project.json
Here are the code review comments:

**Main.xaml**
* Variable `Result` doesn't have `DataTable` prefix: DataTable variable should start with a `dt_` prefix.
* Variable `Marks_Result` does not respect the set pattern `^(dt_)?(A-Z|a-z)+(0-9)*$|_out_[A-Za-z0-9]*$: Make sure all variables follow the naming convention.

**Score: 5/5**

Please note that these are just suggestions and you may need to adjust according to your project's requirements.

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Bhavya/Task 16/project.json
**Main.xaml**
Variable `Result` doesn't have a `DataTable` prefix.
Please rename it to `dt_Result` following the standard naming convention.

**Variable Naming Convention**
The variable `Marks_ Result` does not respect the set pattern `^(dt_)?(A-Z|a-z)+(0-9)*$|_out_[A-Za-z0-9]*$`. Make sure all variables follow this naming convention to avoid confusion and improve readability.

**Project Settings**
NoFile: Your organization requires your project to have an Automation Hub URL defined. Please add the missing information in the Project Settings.

Score: 4/5

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Bhavya/Task 16/project.json
**Main.xaml**
Variable out_Result does not respect the set pattern ^((dt_)?)?(A-Z|a-z)+(0-9)*$: Make sure all the variables follow the naming convention.

This issue is related to variable naming conventions in your Main.xaml file. The problem is that the `out_ Result` variable does not follow the specified naming pattern. To resolve this, please rename the variable to match the required format.

**Score: 5/5**

Please let me know if you have any further questions or concerns!

**Comment by krish952-creator** [comment]
@Bhavyajetty2 
Task -16
Code verified.
Task -17
Code verified.
Task -18
Code verified.

**Pull request merged**
