### PR TITLE
Task 1 & 2 are completed

### PR DESCRIPTION
**Pull request by Sachinrawal1109**

### CODE REVIEW

**Comment by krish952-creator** [comment]
@Sachinrawal1109 
Task -1
Code verified. Default activity names 
 
image

Task -2
Code verified. Default activity names 
 
image

**Comment by Sachinrawal1109** [comment]
Default activity names are updated in Task 1 & Task 2

**Comment by krish952-creator** [comment]
@Sachinrawal1109 
Task -1
Code verified. 
Task -2
Code verified. 
Task -3
Code verified. 
Task -4
Code verified. Default activity names
image

**Comment by krish952-creator** [comment]
@Sachinrawal1109 
Task -4
Code verified.
Task -5
Code verified.
Task -6
Code verified.
Task -7
Code verified.
Task -8
Code verified.
Task -9
Code verified.

**Pull request closed without merging**
