### PR TITLE
Task 12 and 14 Completed

### PR DESCRIPTION
**Pull request by Nazeernrb**
Task 12,14 Check Once again

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nazeer/Task12/project.json
File: NoFile

1. "Your organization requires your project to have an Automation Hub URL defined."
- Simple solution is to navigate to your 'Project Settings' within UiPath Studio. From there, you can input the necessary Automation Hub URL. Don't leave the field blank, mate.

2. "Dependency package UiPath.Testing.Activities is not used."
- Seems like you've excess baggage here! Go ahead and remove the 'UiPath.Testing.Activities' package. It's not doing you any good if you aren't using it. This will speed up your process execution.

3. "Dependency package UiPath.UIAutomation.Activities is not used."
- Same goes for the 'UiPath.UIAutomation.Activities' package, pal. If you're not using it, take it out. You don't want unnecessary packages slowing things down.

Score Distribution:

- Code Completion: 1.5/2 (URL lack is an important project setting)
- Execution: 1/2 (Unused dependencies may impact execution speed)
- Annotations and Comments: 0.5/1 (Always clearly state your dependencies) 

Total Score: 3/5

Just a bit more attention to details, mate, and you'll be good to go!

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nazeer/Task14/project.json
Scores: Code completion - 1.5, Execution - 1.5, Annotations and comments - 1. 

Review:
1. NoFile: You need to have an Automation Hub URL defined in your project settings. This is an organization requirement. You can do this by navigating to 'Project Settings' and adding the necessary information.

2. Unnecessary dependencies: It seems like you have the package 'UiPath.Testing.Activities' included but it's not being used in your code. It's a good practice to remove unused dependencies in your project as it can speed up execution time.
   
Remember, less is more. Let's improve on this.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nazeer/Task18/project.json
For the files in the conversation: 

1. NoFile:
   - Add Automation Hub URL via Project Settings.
   - Unlink UiPath.Mail.Activities, UiPath.Testing.Activities and UiPath.UIAutomation.Activities packages if they aren’t needed for better execute time.

2. Main.xaml:
   - Use Log Message to record process path and errors, which helps maintenance.
   - Label activities "Build Data Table", "Multiple Assign", "Assign", and "Add Data Row" to help in better understanding their purpose.

Scores:
- Code Completion: 1.5/2 (few activities with default names)
- Execution: 1.5/2 (omitted packages)
- Annotations and Comments: 0.5/1 (no logs and unnamed activities)

Overall Score: 3.5 out of 5. Please work on the mentioned points before next review.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nazeer/Task20/project.json
Code Completion Score: 1.5
Several activities and variables have default or incorrect names that do not follow the pattern. Renaming these will make the workflow easier to understand.

Execution Score: 1.5
Two of your packages are not in use. Unused packages can affect process execution time, therefore, they should be removed.

Annotations and Comments Score: 0.5
Your workflow "Main" is absent of Log Message activities. These are essential in both the development and post-release stages for error debugging and maintaining the workflow.

Respective Fixes:
1. In 'Project Settings', define the Automation Hub URL.
2. Remove unused packages 'UiPath.Mail.Activities' and 'UiPath.Testing.Activities' for improved execution speed.
3. Add Log Message activities in the Main workflow for better debugging and maintenance.
4. Correct the naming of variables 'ExcelSheet' and 'Cell_ID' to follow the naming convention.
5. Rename default-named activities 'For Each Row in Data Table' and 'Assign' to make their functions clearer.

Once these recommended changes are implemented, your workflow's design and execution should significantly improve. It's important to keep these points in mind as you continue to develop.

**Comment by krish952-creator** [comment]
@Nazeernrb 
Task -12 &14
code verified.

**Pull request merged**
