### PR TITLE
Task - 6

### PR DESCRIPTION
**Pull request by ramkumar566**
Array

### CODE REVIEW

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ]
}

**Comment by vajrang-b** [comment]
{
    "~Main.xaml":  [
                       {
                           "Display the Array item display name is defined many times. Current allowed threshold is 1. Code contains 2.":  "Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names. "
                       }
                   ],
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Variable variable1 is not used.":  "Remove variables that are not used. "
                      },
                      {
                          "Display the Array item display name is defined many times. Current allowed threshold is 1. Code contains 2.":  "Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ],
    "Main.xaml":  [
                      {
                          "Activity Log Message has a default name.":  "Check if it could be easier to understand what the activity does by adding a more descriptive title. "
                      }
                  ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ]
}

**Comment by vajrang-b** [comment]
{
    "NoFile":  [
                   {
                       "Your organization requires your project to have an Automation Hub URL defined.":  "Use \"Project Settings\" to add the missing information. "
                   },
                   {
                       "Dependency package UiPath.Excel.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   },
                   {
                       "Dependency package UiPath.Mail.Activities is not used.":  "Remove unused packages in order to improve process execution time. "
                   }
               ]
}

**Comment by krish952-creator** [comment]
@ramkumar566 
Task -6
Code verified.
Task -7
Code verified.
Task -8
Code verified.
Task -9
Code verified.

**Pull request merged**
