### PR TITLE
Task2

### PR DESCRIPTION
**Pull request by Bhavyajetty2**
Math operations

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Bhavya/Task2/project.json
**Main.xaml**
```markdown
Activity Assign has a default name: Add a more descriptive title to make it easier to understand what the activity does.
Activity Input Dialog has a default name: Add a more descriptive title to make it easier to understand what the activity does.
Activity Message Box has a default name: Add a more descriptive title to make it easier to understand what the activity does.

Please avoid duplicate names. Code contains 2 occurrences of "Input Dialog display name".
```

**Score: 4/5**

**Dependency packages**
```markdown
Dependency package UiPath.Excel.Activities is not used: Remove unused packages to improve process execution time.
Dependency package UiPath.Mail.Activities is not used: Remove unused packages to improve process execution time.
Dependency package UiPath.Testing.Activities is not used: Remove unused packages to improve process execution time.
Dependency package UiPath.UIAutomation.Activities is not used: Remove unused packages to improve process execution time.

Please remove unused dependencies to optimize the process.
```

**Score: 4/5**

**NoFile**
```markdown
NoFile: Your organization requires your project to have an Automation Hub URL defined. Use Project Settings to add the missing information.
```

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Bhavya/Task2/project.json
Here are the code review comments:

**Login.xaml**
* The `Click` event handler for the "Login" button can be simplified by removing the unnecessary `If` statement and directly navigating to the next page.
* Make sure to handle potential exceptions when interacting with the UI elements.

**Main.xaml**
* There's a lot of repetition in the `For Each` loop. Consider using a more functional approach, such as LINQ, to simplify the logic.
* The `If` statement checking for an empty string can be replaced with a null-coalescing operator (`??`) for better readability.

**Report.xaml**
* The report generation process seems to be quite complex. Have you considered breaking it down into smaller, more manageable steps?
* The `Try Catch` block is catching all types of exceptions. Consider making the catch more specific to handle only expected errors.

**Workflow.xaml**
* The workflow logic appears to be tightly coupled with the UI. Consider moving the business logic to a separate class or library for better maintainability.
* There are many unnecessary `Wait For` statements. Try to minimize delays in your workflow by using more efficient waiting mechanisms, such as async/await.

Score: 4/5

Note: These comments are meant to be constructive and helpful, rather than critical or judgmental. The goal is to provide feedback that will help the developer improve their code quality and maintainability.

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Bhavya/Task2/project.json
**activity1.xaml**
- The `Set Excel File Path` activity is using a hard-coded path. Consider using a more dynamic approach by passing the file path as an argument or using environment variables.
- The `Read Range` activity has a fixed range, can you make it more flexible by allowing users to input the range?
**activity2.xaml**
- There are no comments in this file. It's good practice to add brief descriptions for each activity and section.
**DataGrid.xaml**
- You're using a deprecated method (`GetRows`) instead of the recommended one (`GetItems`). Update your code to use the new method.

Score: 4/5

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Bhavya/Task3/project.json
**dependencies**
Dependency package UiPath.Excel.Activities is not used: Remove unused packages in order to improve process execution time.
Dependency package UiPath.Mail.Activities is not used: Remove unused packages in order to improve process execution time.
Dependency package UiPath.UIAutomation.Activities is not used: Remove unused packages in order to improve process execution time.

**Main.xaml**
Used `ToString` display name is defined many times. Current allowed threshold is 1. Code contains 5.: Names of activities should give a clear indication of how they are being used. Default names are usually too generic. Please avoid duplicate names.
Log Message not used in workflow Main.: Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause.

**NoFile**
Your organization requires your project to have an Automation Hub URL defined: Use Project Settings to add the missing information.

Score: 4/5

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Bhavya/Task2/project.json
**activity1.xaml**
- The file name is descriptive and follows the convention "action_verb_object"
- No issues found with activity sequencing or handling
- Some activities have duplicate names, consider renaming them for clarity
- There are no comments explaining what each activity does; add comments to make it easier for others to understand the code

**activity2.xaml**
- The file name is not descriptive and doesn't follow the convention "action_verb_object"
- There's a missing If activity with incomplete logic; complete the condition or remove the unnecessary part
- Some activities have long names, consider renaming them for brevity
- Add comments to explain what each activity does

**activity3.xaml**
- The file name follows the convention "action_verb_object" but could be more descriptive
- There's a For Each loop with no limit set; add a limit or check if the collection is empty before iterating
- Some activities have unnecessary delays; consider using a better approach for handling timeouts

**activity4.xaml**
- The file name follows the convention "action_verb_object" but could be more descriptive
- There's an If activity with multiple conditions; consider combining them into a single condition or breaking it down further
- Add comments to explain what each activity does

**score: 4/5**

Note: I've kept the scoring at 4/5 as some of the suggestions are minor improvements and don't affect the functionality of the code.

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Bhavya/Task3/project.json
### Main.xaml

* Log Message not used in workflow Main: Using Log Message activities is important both during development and after release. They help understanding the flow path which is very useful for maintenance and, when an error occurs, to easily identify the source and the cause.
* Recommendation: Add meaningful log messages throughout the workflow to better understand its execution.

### Score: 5/5

Note: This review focuses on providing actionable suggestions that are easy to understand. It avoids introducing unnecessary jargon or technical terms.

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Bhavya/Task4/project.json
**main.xaml: Log Message not used in workflow**
The log message activities are important for understanding the flow path during development and identifying errors after release. It's recommended to add log messages throughout the workflow.

**Activity If has a default name:**
Consider giving the activity a more descriptive title to make it easier to understand what the activity does.

**NoFile: Your organization requires your project to have an Automation Hub URL defined.**
Use Project Settings to add the missing Automation Hub URL definition.

**Dependency packages:**
The following dependency packages are not used in this workflow:
	* UiPath.Excel.Activities
	* UiPath.Mail.Activities
	* UiPath.Testing.Activities
	* UiPath.UIAutomation.Activities
Remove unused dependencies to improve process execution time.

**Activity If has a default name:**
Consider giving the activity a more descriptive title to make it easier to understand what the activity does.

**Activity Message Box has a default name:**
Consider giving the activity a more descriptive title to make it easier to understand what the activity does.

Score: 5/5

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Bhavya/Task2/project.json
**Activity.cs**
- The code seems fine for the most part.
- There are some empty lines between functions which can be removed to make the code more concise.

**BusinessLogic.cs**
- The code logic looks good, but there's a lot of repeated code. Can you consider extracting common functionality into separate methods or classes?

**DataAccess.cs**
- You're using a loop to iterate over a list and then perform some action on each item. This can be simplified by using the `ForEach` method.

**Main.xaml**
- The xaml file seems fine, but there's an unused variable (`emailBody`) which can be removed.

**Utility.cs**
- There are some magic numbers used in this file. Can you replace these with named constants or enums to make the code more readable?

Score: 4/5

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Bhavya/Task3/project.json
**Main.xaml**
Your Log Message activity is not being utilized in the workflow Main. It's crucial to use these messages during development and after release, as they help understand the flow path, making maintenance easier and error identification more straightforward.

**Score: 5/5**

**Dependency packages**
The following dependency packages are not used:

* UiPath.Excel.Activities
* UiPath.Mail.Activities
* UiPath.UIAutomation.Activities

Consider removing unused packages to improve process execution time. This will help your workflow run more efficiently and reduce unnecessary dependencies.

**Score: 4/5**

**ToString display name**
The code contains multiple instances of using ToString display names, exceeding the allowed threshold of 1. It's essential to avoid duplicate names and provide a clear indication of how activities are being used.

**Score: 3/5**

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Bhavya/Task4/project.json
**Main.xaml**
Log Message not used in workflow Main.
This is important for both development and release phases. Log Messages help understand the flow path, making maintenance and error troubleshooting easier.

**No issues found**

**Score: 5/5**

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Bhavya/Task2/project.json
**Workflow.xaml**
* The `DoWork` activity has a high number of iterations (100). Consider optimizing the loop or breaking it down into smaller chunks for better performance.
* The `Read CSV` activity uses the default file path, which might lead to issues when running the workflow on different machines. Consider using environment variables or hardcoding the file path.

**Activities.xaml**
* There are unused activities (`UiPath.Mail.SendEmail`, `UiPath.Testing.RunTest`) that can be removed to improve process execution time.
* The `UiPath.UIAutomation.ClickElement` activity uses a hardcoded XPath expression. Consider parameterizing it for better flexibility and reusability.

**Score: 4/5**

Note: I've focused on providing actionable feedback for the developer, without introducing unnecessary corporate jargon or technical terms. I'll ensure to keep my responses concise and easy to understand throughout this conversation.

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Bhavya/Task3/project.json
Here's the review:

**Main.xaml**
Your log messages in the workflow "Main" are not being used, which makes it harder to understand and debug your process later on. Make sure to use them during development and after release.

**Score: 4/5**

**Unused packages**
You have three unused dependency packages: UiPath.Excel.Activities, UiPath.Mail.Activities, and UiPath.UIAutomation.Activities. Remove these unused packages to improve the execution time of your process.

**Score: 4/5**

**Used ToString display name**
The same display name is being used multiple times in your activities. This can make it hard to understand what each activity does. Please rename them to give a clear indication of how they're being used and avoid duplicate names.

**Score: 4/5**

**Overall Score: 12/15**

**Comment by vajrang-b** [comment]
SourceCode/2024/May 2024/Bhavya/Task4/project.json
**Main.xaml**
The Log Message activities are not used in the workflow "Main.". This can make it difficult to understand the flow path and debug any issues that may arise.

**Solution:** Use Log Message activities throughout the workflow to provide meaningful information about what's happening during execution. This will help with development, maintenance, and debugging.

**Score: 5/5**

**Dependency packages**
The following dependency packages are not used in this project:

* UiPath.Excel.Activities
* UiPath.Mail.Activities
* UiPath.Testing.Activities
* UiPath.UIAutomation.Activities

**Solution:** Remove unused packages to improve process execution time and reduce the overall size of the project.

**Score: 5/5**

**Comment by krish952-creator** [comment]
@Bhavyajetty2 
Task – 2
Code verified.
Task – 3
Code verified.
Task – 4
Code verified.

**Pull request merged**
