### PR TITLE
Task_6 completed.

### PR DESCRIPTION
**Pull request by Nihar-11**
Added list of Color

### CODE REVIEW

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nihar/Task_6/project.json
Scores: 
1. Code Completion: 1.5/2 - The project is missing required information in the project settings, and there's a redundant sequence that needs to be removed. Other than these, the code seems to be complete. 
2. Execution: 1.5/2 - There's an unused dependency package which would impact the execution time. Removing it could improve the execution score.  
3. Annotations & Comments: 0.5/1 - Several activities have default names. Adding descriptive titles would make it easier to understand the purpose of these activities.

Solutions:
- Use the "Project Settings" option to define the Automation Hub URL.
- Remove the UiPath.UIAutomation.Activities package if it's not being used in your project. 
- Get rid of the Sequence_List_Colours if it's redundant. You can use the "Remove Surrounding Sequence" option in UiPath Studio.
- Replace the default names for your activities with more descriptive ones. This will make your code easier to understand.

Please implement these changes for improving the quality of your code.

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nihar/Task_6/project.json
Based on the review:

For 'NoFile':
- Score: 1.5 / 2 - The Automation Hub URL is missing. You can add this using the 'Project Settings'. 
- Score: 2 / 2 - You've included UiPath.UIAutomation.Activities package which isn't used. Removing unused packages will better the execution time. 

For 'Main.xaml':
- Score: 1.5 / 2 - The Sequence_List_Colours is redundant. Try and remove redundant ones for better workflow. You can do this using the 'Remove Surrounding Sequence' option in UiPath Studio's Context Menu.
- Score: 2 / 2 - The Activity For Each and Append Line has default names. It could improve comprehension if you title them based on what they do.

As for the annotations and comments, you didn't provide any. Adding them can greatly improve understanding of the code and helps during reviews or debugging. 
- Score: 0 / 1

Based on the scores,
- Code Completion Score: 4 / 6
- Execution Score: 4 / 4
- Annotations And Comments Score: 0 / 1

Consider these comments to ace the next review!

**Comment by vajrang-b** [comment]
SourceCode/2023/Oct2023/Basics/Nihar/Task_7/project.json
For the files you've shared, here are the main pointers located for your review.

**NoFile**:

- Your Association needs a defined Automation Hub URL. Go to 'Project Settings' and add this in.

- There are some redundant inclusion of packages like UiPath.Testing.Activities and UiPath.UIAutomation.Activities. Check them out and remove if not in use. This can help speed up process execution time.

**Main.xaml**:

- Within Sequence_List there's redundancy detected. Unnecessary sequences just add clutter. To clean it up, use the Remove Surrounding Sequence option in UiPath Studio.

- It seems 'Display the Index of the Assigned Values' is defined more than required. Keep it once, avoid repetition.

- Two activities - 'Assign' and 'Log Message' - have default names. Maybe we can fix this by making titles more illustrative and helpful. 

Scores:
Code Completion 2,
Execution 2,
Annotations and comments(1): Please put in effort in annotating your code with helpful names and comments.

**Comment by krish952-creator** [comment]
@Nihar-11 
Task-6
Code verified. Default activity names
 
image

Task-7
Code verified. Default activity names
 
image

Task-8
Code verified. Default activity names
image

**Pull request merged**
